<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AclRolePrivilege
  */
namespace DBCore\Bizjadmin;

use phpr\Database\Model;

class AclRolePrivilege extends Model {

    const SCHEMA = 'bizjadmin';
    const TABLE = 'acl_role_privilege';
    const AUTO_INCREMENT_COLUMN = 'acl_role_privilege_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'acl_role_privilege_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'acl_role_privilege_id',
          1 => 'acl_role_id',
          2 => 'acl_resource_id',
          3 => 'privilege',
          4 => 'mode',
          5 => 'created_at',
          6 => 'updated_at',
        );

    public $acl_role_privilege_id = NULL;
    public $acl_role_id = NULL;
    public $acl_resource_id = NULL;
    public $privilege = NULL;
    public $mode = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'acl_role_privilege_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'acl_role_id' => 
          array (
          ),
          'acl_resource_id' => 
          array (
          ),
          'privilege' => 
          array (
          ),
          'mode' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>