<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AuditLog
  */
namespace DBCore\Bizjadmin;

use phpr\Database\Model;

class AuditLog extends Model {

    const SCHEMA = 'bizjadmin';
    const TABLE = 'audit_log';
    const AUTO_INCREMENT_COLUMN = 'log_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'log_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'log_id',
          1 => 'email',
          2 => 'created_at',
          3 => 'priority',
        );

    public $log_id = NULL;
    public $email = NULL;
    public $created_at = NULL;
    public $priority = NULL;
    public $module = NULL;
    public $controller = NULL;
    public $action = NULL;
    public $message = NULL;
    public $ip_address = NULL;
    public $resource_id = NULL;
    public $url = NULL;
    public $DBColumnsArray = 
        array (
          'log_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'email' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'priority' => 
          array (
          ),
          'module' => 
          array (
          ),
          'controller' => 
          array (
          ),
          'action' => 
          array (
          ),
          'message' => 
          array (
          ),
          'ip_address' => 
          array (
          ),
          'resource_id' => 
          array (
          ),
          'url' => 
          array (
          ),
        );




}

?>