<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in User
  */
namespace DBCore\Bizjadmin;

use phpr\Database\Model;

class User extends Model {

    const SCHEMA = 'bizjadmin';
    const TABLE = 'user';
    const AUTO_INCREMENT_COLUMN = 'user_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'email',
          2 => 'use_ldap',
          3 => 'created_at',
          4 => 'updated_at',
        );

    public $user_id = NULL;
    public $email = NULL;
    public $password = NULL;
    public $use_ldap = NULL;
    public $expires = NULL;
    public $modified_by = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'email' => 
          array (
          ),
          'password' => 
          array (
          ),
          'use_ldap' => 
          array (
          ),
          'expires' => 
          array (
          ),
          'modified_by' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>