<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AdminUsers
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class AdminUsers extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'admin_users';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $login = NULL;
    public $name = NULL;
    public $email = NULL;
    public $crypted_password = NULL;
    public $salt = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $remember_token = NULL;
    public $remember_token_expires_at = NULL;
    public $api_id = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'login' => 
          array (
          ),
          'name' => 
          array (
          ),
          'email' => 
          array (
          ),
          'crypted_password' => 
          array (
          ),
          'salt' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'remember_token' => 
          array (
          ),
          'remember_token_expires_at' => 
          array (
          ),
          'api_id' => 
          array (
          ),
        );




}

?>