<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Carts
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class Carts extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'carts';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $department_id = NULL;
    public $customer_id = NULL;
    public $coupon_id = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $display_locale = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'department_id' => 
          array (
          ),
          'customer_id' => 
          array (
          ),
          'coupon_id' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'display_locale' => 
          array (
          ),
        );




}

?>