<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Customers
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class Customers extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'customers';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $account_id = NULL;
    public $email = NULL;
    public $discount_points = NULL;
    public $use_billing = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'account_id' => 
          array (
          ),
          'email' => 
          array (
          ),
          'discount_points' => 
          array (
          ),
          'use_billing' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>