<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DigitalSubscriptions
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class DigitalSubscriptions extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'digital_subscriptions';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $country = NULL;
    public $email_address = NULL;
    public $end_date = NULL;
    public $family_name = NULL;
    public $given_name = NULL;
    public $yudu_id = NULL;
    public $notes = NULL;
    public $number_of_computers_allowed = NULL;
    public $password = NULL;
    public $region = NULL;
    public $start_date = NULL;
    public $subscribed_node_id = NULL;
    public $subscribed_node_name = NULL;
    public $town = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'country' => 
          array (
          ),
          'email_address' => 
          array (
          ),
          'end_date' => 
          array (
          ),
          'family_name' => 
          array (
          ),
          'given_name' => 
          array (
          ),
          'yudu_id' => 
          array (
          ),
          'notes' => 
          array (
          ),
          'number_of_computers_allowed' => 
          array (
          ),
          'password' => 
          array (
          ),
          'region' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'subscribed_node_id' => 
          array (
          ),
          'subscribed_node_name' => 
          array (
          ),
          'town' => 
          array (
          ),
        );




}

?>