<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Inventories
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class Inventories extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'inventories';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $department_id = NULL;
    public $product_id = NULL;
    public $quantity = NULL;
    public $is_reorderable = NULL;
    public $is_unlimited = NULL;
    public $min_inventory_level = NULL;
    public $inventory_warning_level = NULL;
    public $allocated = NULL;
    public $restock_delay = NULL;
    public $reorder_lot_size = NULL;
    public $min_reorder_qty = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'department_id' => 
          array (
          ),
          'product_id' => 
          array (
          ),
          'quantity' => 
          array (
          ),
          'is_reorderable' => 
          array (
          ),
          'is_unlimited' => 
          array (
          ),
          'min_inventory_level' => 
          array (
          ),
          'inventory_warning_level' => 
          array (
          ),
          'allocated' => 
          array (
          ),
          'restock_delay' => 
          array (
          ),
          'reorder_lot_size' => 
          array (
          ),
          'min_reorder_qty' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>