<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in OrderTransactions
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class OrderTransactions extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'order_transactions';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $order_id = NULL;
    public $amount = NULL;
    public $success = NULL;
    public $reference = NULL;
    public $message = NULL;
    public $action = NULL;
    public $params = NULL;
    public $payment = NULL;
    public $test = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $vsorigid = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'order_id' => 
          array (
          ),
          'amount' => 
          array (
          ),
          'success' => 
          array (
          ),
          'reference' => 
          array (
          ),
          'message' => 
          array (
          ),
          'action' => 
          array (
          ),
          'params' => 
          array (
          ),
          'payment' => 
          array (
          ),
          'test' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'vsorigid' => 
          array (
          ),
        );




}

?>