<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Purchases
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class Purchases extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'purchases';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $product_id = NULL;
    public $order_id = NULL;
    public $quantity = NULL;
    public $discount_points = NULL;
    public $gift = NULL;
    public $subscriber = NULL;
    public $gift_salutation = NULL;
    public $gift_message = NULL;
    public $gift_footer = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'product_id' => 
          array (
          ),
          'order_id' => 
          array (
          ),
          'quantity' => 
          array (
          ),
          'discount_points' => 
          array (
          ),
          'gift' => 
          array (
          ),
          'subscriber' => 
          array (
          ),
          'gift_salutation' => 
          array (
          ),
          'gift_message' => 
          array (
          ),
          'gift_footer' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>