<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Reviews
  */
namespace DBCore\SceneDaily;

use phpr\Database\Model;

class Reviews extends Model {

    const SCHEMA = 'scene_daily';
    const TABLE = 'reviews';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $account_id = NULL;
    public $product_id = NULL;
    public $title = NULL;
    public $content = NULL;
    public $rating = NULL;
    public $flagged_for_review = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'account_id' => 
          array (
          ),
          'product_id' => 
          array (
          ),
          'title' => 
          array (
          ),
          'content' => 
          array (
          ),
          'rating' => 
          array (
          ),
          'flagged_for_review' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>