<div class="modal hide span8 in" id="crop-modal">
    <div class="modal-header">
        <button data-dismiss="modal" class="close modal-close" type="button">&times;</button>
        <h3>Edit Crop</h3>
    </div>
    <div class="modal-body">
        <img src="img/ajax-loader.gif">
        <img id="thumbnail-crop" style="display: none" src="<?php echo $this->media['crop_url'] ?>">
    </div>
    <div class="modal-footer">
        <a data-dismiss="modal" class="btn btn-primary modal-close modal-finish" href="#">Insert Photo</a>
    </div>
</div>
