<div class="modal hide span12" id="select-photo-modal">
    <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button" id="select-photo-modal-close-x">&times;</button>
        <h3>Select Photo</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span9">
                <div class="modal-body__primary">
<?php echo $this->render('partial/search/media/fields') ?>
                    <div id="content-list">
                        <table class="table table-striped table--select" data-items="5">
                            <thead>
                                <tr>
                                    <th class="column-preview">Preview</th>
                                    <th>Title</th>
<?php if ($this->show_select): ?>
                                    <th></th>
<?php endif ?>
                                </tr>
                            </thead>
                            <tbody>
<?php echo $this->partial('api/medialibrary/search-results', array('media' => $this->media, 'modal_ref' => $this->modal_ref, 'show_select' => $this->show_select)) ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="modal-body__secondary">
<?php echo $this->render('partial/search/media/filters') ?>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button data-dismiss="modal" class="btn" id="select-photo-modal-close" >Close</button>
    </div>
</div>
