<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in FecCommitteeCategoryMeta
  */
namespace DBCore\Bizjfed;

use phpr\Database\Model;

class FecCommitteeCategoryMeta extends Model {

    const SCHEMA = 'bizjfed';
    const TABLE = 'fec_committee_category_meta';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'category',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'category',
        );

    public $category = NULL;
    public $description = NULL;
    public $DBColumnsArray = 
        array (
          'category' => 
          array (
            0 => 1,
          ),
          'description' => 
          array (
          ),
        );




}

?>