<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in FecCommitteeToCandidateContributions
  */
namespace DBCore\Bizjfed;

use phpr\Database\Model;

class FecCommitteeToCandidateContributions extends Model {

    const SCHEMA = 'bizjfed';
    const TABLE = 'fec_committee_to_candidate_contributions';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'sub_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'committee_id',
          1 => 'sub_id',
        );

    public $committee_id = NULL;
    public $race = NULL;
    public $amendment_indicator = NULL;
    public $report_type = NULL;
    public $transaction_pgi = NULL;
    public $image_num = NULL;
    public $transaction_type = NULL;
    public $entity_type = NULL;
    public $recipient_or_payee = NULL;
    public $city = NULL;
    public $state = NULL;
    public $zip_code = NULL;
    public $employer = NULL;
    public $occupation = NULL;
    public $transaction_date = NULL;
    public $transaction_amount = NULL;
    public $other_id = NULL;
    public $candidate_id = NULL;
    public $transaction_id = NULL;
    public $file_number = NULL;
    public $memo_code = NULL;
    public $memo_text = NULL;
    public $sub_id = NULL;
    public $DBColumnsArray = 
        array (
          'committee_id' => 
          array (
          ),
          'race' => 
          array (
          ),
          'amendment_indicator' => 
          array (
          ),
          'report_type' => 
          array (
          ),
          'transaction_pgi' => 
          array (
          ),
          'image_num' => 
          array (
          ),
          'transaction_type' => 
          array (
          ),
          'entity_type' => 
          array (
          ),
          'recipient_or_payee' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'zip_code' => 
          array (
          ),
          'employer' => 
          array (
          ),
          'occupation' => 
          array (
          ),
          'transaction_date' => 
          array (
          ),
          'transaction_amount' => 
          array (
          ),
          'other_id' => 
          array (
          ),
          'candidate_id' => 
          array (
          ),
          'transaction_id' => 
          array (
          ),
          'file_number' => 
          array (
          ),
          'memo_code' => 
          array (
          ),
          'memo_text' => 
          array (
          ),
          'sub_id' => 
          array (
            0 => 1,
          ),
        );




}

?>