<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in FecCandidateIncumbentChallengerStatusMeta
  */
namespace DBCore\Bizjfed;

use phpr\Database\Model;

class FecCandidateIncumbentChallengerStatusMeta extends Model {

    const SCHEMA = 'bizjfed';
    const TABLE = 'fec_candidate_incumbent_challenger_status_meta';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'incumbent_challenger_status',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'incumbent_challenger_status',
        );

    public $incumbent_challenger_status = NULL;
    public $description = NULL;
    public $DBColumnsArray = 
        array (
          'incumbent_challenger_status' => 
          array (
            0 => 1,
          ),
          'description' => 
          array (
          ),
        );




}

?>