<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EdwinCommandLog
  */
namespace DBCore\Email;

use phpr\Database\Model;

class EdwinCommandLog extends Model {

    const SCHEMA = 'email';
    const TABLE = 'edwin_command_log';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'command_id',
          2 => 'event',
          3 => 'is_error',
          4 => 'created_at',
        );

    public $id = NULL;
    public $command_id = NULL;
    public $event = NULL;
    public $processed_at = NULL;
    public $is_error = NULL;
    public $command = NULL;
    public $output = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'command_id' => 
          array (
          ),
          'event' => 
          array (
          ),
          'processed_at' => 
          array (
          ),
          'is_error' => 
          array (
          ),
          'command' => 
          array (
          ),
          'output' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>