<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EmailAds
  */
namespace DBCore\Email;

use phpr\Database\Model;

class EmailAds extends Model {

    const SCHEMA = 'email';
    const TABLE = 'email_ads';
    const AUTO_INCREMENT_COLUMN = 'ad_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'ad_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'ad_id',
          1 => 'start_date',
          2 => 'end_date',
          3 => 'c_time',
        );

    public $ad_id = NULL;
    public $product_id = NULL;
    public $placement = NULL;
    public $start_date = NULL;
    public $end_date = NULL;
    public $sponsor_name = NULL;
    public $sponsor_link = NULL;
    public $tracking_pixel = NULL;
    public $image_url = NULL;
    public $ad_headline = NULL;
    public $ad_text = NULL;
    public $call_to_action = NULL;
    public $approval = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'ad_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'product_id' => 
          array (
          ),
          'placement' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'end_date' => 
          array (
          ),
          'sponsor_name' => 
          array (
          ),
          'sponsor_link' => 
          array (
          ),
          'tracking_pixel' => 
          array (
          ),
          'image_url' => 
          array (
          ),
          'ad_headline' => 
          array (
          ),
          'ad_text' => 
          array (
          ),
          'call_to_action' => 
          array (
          ),
          'approval' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>