<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EmailSendStats
  */
namespace DBCore\Email;

use phpr\Database\Model;

class EmailSendStats extends Model {

    const SCHEMA = 'email';
    const TABLE = 'email_send_stats';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'job_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'job_id',
          1 => 'product_id',
          2 => 'send_time',
        );

    public $job_id = NULL;
    public $product_id = NULL;
    public $send_time = NULL;
    public $sent = NULL;
    public $bounced = NULL;
    public $delivered = NULL;
    public $deliverablity_rate = NULL;
    public $open_unique = NULL;
    public $open_unique_rate = NULL;
    public $open_cumulative = NULL;
    public $open_cumulative_rate = NULL;
    public $click_unique = NULL;
    public $click_unique_rate = NULL;
    public $click_cumulative = NULL;
    public $click_cumulative_rate = NULL;
    public $DBColumnsArray = 
        array (
          'job_id' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
          ),
          'send_time' => 
          array (
          ),
          'sent' => 
          array (
          ),
          'bounced' => 
          array (
          ),
          'delivered' => 
          array (
          ),
          'deliverablity_rate' => 
          array (
          ),
          'open_unique' => 
          array (
          ),
          'open_unique_rate' => 
          array (
          ),
          'open_cumulative' => 
          array (
          ),
          'open_cumulative_rate' => 
          array (
          ),
          'click_unique' => 
          array (
          ),
          'click_unique_rate' => 
          array (
          ),
          'click_cumulative' => 
          array (
          ),
          'click_cumulative_rate' => 
          array (
          ),
        );




}

?>