<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EmailContentVersion
  */
namespace DBCore\Email;

use phpr\Database\Model;

class EmailContentVersion extends Model {

    const SCHEMA = 'email';
    const TABLE = 'email_content_version';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'content_id',
          1 => 'version',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'content_id',
          1 => 'created_at',
          2 => 'updated_at',
          3 => 'version',
        );

    public $content_id = NULL;
    public $product_id = NULL;
    public $content_html = NULL;
    public $content_text = NULL;
    public $author = NULL;
    public $m_time = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $version = NULL;
    public $DBColumnsArray = 
        array (
          'content_id' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
          ),
          'content_html' => 
          array (
          ),
          'content_text' => 
          array (
          ),
          'author' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'version' => 
          array (
            0 => 1,
          ),
        );




}

?>