<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EmailTypeHook
  */
namespace DBCore\Email;

use phpr\Database\Model;

class EmailTypeHook extends Model {

    const SCHEMA = 'email';
    const TABLE = 'email_type_hook';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'product_id',
          1 => 'hook_product_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'product_id',
          1 => 'hook_product_id',
          2 => 'hook_type',
        );

    public $product_id = NULL;
    public $hook_product_id = NULL;
    public $hook_type = NULL;
    public $DBColumnsArray = 
        array (
          'product_id' => 
          array (
            0 => 1,
          ),
          'hook_product_id' => 
          array (
            0 => 1,
          ),
          'hook_type' => 
          array (
          ),
        );




}

?>