<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EmailJob
  */
namespace DBCore\Email;

use phpr\Database\Model;

class EmailJob extends Model {

    const SCHEMA = 'email';
    const TABLE = 'email_job';
    const AUTO_INCREMENT_COLUMN = 'job_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'job_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'job_id',
          1 => 'c_time',
        );

    public $job_id = NULL;
    public $description = NULL;
    public $product_id = NULL;
    public $from_field = NULL;
    public $reply_to = NULL;
    public $sender_host = NULL;
    public $send_priority = NULL;
    public $message_count = NULL;
    public $message_sent_count = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'job_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'description' => 
          array (
          ),
          'product_id' => 
          array (
          ),
          'from_field' => 
          array (
          ),
          'reply_to' => 
          array (
          ),
          'sender_host' => 
          array (
          ),
          'send_priority' => 
          array (
          ),
          'message_count' => 
          array (
          ),
          'message_sent_count' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>