<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Console\Controller\AbstractActionController'        => __DIR__ . '/src/Console/Controller/AbstractActionController.php',
    'Console\Controller\ImportController'                => __DIR__ . '/src/Console/Controller/ImportController.php',
    'Console\Controller\IndexController'                 => __DIR__ . '/src/Console/Controller/IndexController.php',
    'Console\Controller\MeroveusController'              => __DIR__ . '/src/Console/Controller/MeroveusController.php',
    'Console\CsvIterator'                                => __DIR__ . '/src/Console/CsvIterator.php',
    'Console\Module'                                     => __DIR__ . '/Module.php',
    'Console\Record\Formatter\Exception\NotFound'        => __DIR__ . '/src/Console/Record/Formatter/Exception/NotFound.php',
    'Console\Record\Formatter\Factory'                   => __DIR__ . '/src/Console/Record/Formatter/Factory.php',
    'Console\Record\Formatter\FormatterTrait'            => __DIR__ . '/src/Console/Record/Formatter/FormatterTrait.php',
    'Console\Record\Formatter\Formatters\ImportMeroveus' => __DIR__ . '/src/Console/Record/Formatter/Formatters/importmeroveus.php',
    'Console\Record\Formatter\Formatters\Meroveus'       => __DIR__ . '/src/Console/Record/Formatter/Formatters/Meroveus.php',
    'Console\Record\Formatter\Formatters\Relevate'       => __DIR__ . '/src/Console/Record/Formatter/Formatters/relevate.php',
);
