<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Console\Controller\AbstractActionController' => __DIR__ . '/src/Console/Controller/AbstractActionController.php',
    'Console\Controller\BizbooksController'       => __DIR__ . '/src/Console/Controller/BizbooksController.php',
    'Console\Controller\IndexController'          => __DIR__ . '/src/Console/Controller/IndexController.php',
    'Console\Controller\MediaimportController'    => __DIR__ . '/src/Console/Controller/MediaimportController.php',
    'Console\Module'                              => __DIR__ . '/Module.php',
);
