<?php
/**
 * User: daveb
 * Date: 1/6/16
 * Time: 4:43 PM
 */

namespace Api\Controller;

use Zend\View\Model\JsonModel;
use Hub\Model\Company;

class CompanyController extends AbstractRestfulController
{
    public function indexAction($id = 0)
    {
        return $this->get($id);

//        $this->getServiceLocator()->get('Hub\Model\Company');

        return parent::get($id); // TODO: Change the autogenerated stub
    }

    public function get($id =0)
    {
        die('Company controller get action');
    }

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update($id, $data)
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }
}