<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Product
  */
namespace DBCore\Nascarillustrated;

use phpr\Database\Model;

class Product extends Model {

    const SCHEMA = 'nascarillustrated';
    const TABLE = 'product';
    const AUTO_INCREMENT_COLUMN = 'product_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'product_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'product_id',
          1 => 'category_id',
          2 => 'product_name',
          3 => 'is_active',
          4 => 'is_hidden',
          5 => 'is_subscription',
          6 => 'price',
          7 => 'domestic_charge',
          8 => 'ca_mx_charge',
          9 => 'international_charge',
        );

    public $product_id = NULL;
    public $category_id = NULL;
    public $sku_code = NULL;
    public $product_name = NULL;
    public $slug = NULL;
    public $issue_date = NULL;
    public $teaser = NULL;
    public $description = NULL;
    public $is_active = NULL;
    public $is_hidden = NULL;
    public $is_subscription = NULL;
    public $key_code = NULL;
    public $price = NULL;
    public $domestic_ratecode = NULL;
    public $domestic_charge = NULL;
    public $ca_mx_ratecode = NULL;
    public $ca_mx_charge = NULL;
    public $international_ratecode = NULL;
    public $international_charge = NULL;
    public $original_issue_id = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'product_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'category_id' => 
          array (
          ),
          'sku_code' => 
          array (
          ),
          'product_name' => 
          array (
          ),
          'slug' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'teaser' => 
          array (
          ),
          'description' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'is_hidden' => 
          array (
          ),
          'is_subscription' => 
          array (
          ),
          'key_code' => 
          array (
          ),
          'price' => 
          array (
          ),
          'domestic_ratecode' => 
          array (
          ),
          'domestic_charge' => 
          array (
          ),
          'ca_mx_ratecode' => 
          array (
          ),
          'ca_mx_charge' => 
          array (
          ),
          'international_ratecode' => 
          array (
          ),
          'international_charge' => 
          array (
          ),
          'original_issue_id' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>