<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Purchase
  */
namespace DBCore\Nascarillustrated;

use phpr\Database\Model;

class Purchase extends Model {

    const SCHEMA = 'nascarillustrated';
    const TABLE = 'purchase';
    const AUTO_INCREMENT_COLUMN = 'purchase_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'purchase_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'purchase_id',
          1 => 'is_complete',
          2 => 'amount',
          3 => 'first_name',
          4 => 'last_name',
          5 => 'email',
          6 => 'phone',
          7 => 'address1',
          8 => 'address2',
          9 => 'city',
          10 => 'state_province',
          11 => 'postal_code',
          12 => 'country',
          13 => 'has_billing_eq_shipping',
        );

    public $purchase_id = NULL;
    public $is_complete = NULL;
    public $merchandise_batch_file = NULL;
    public $subscription_batch_file = NULL;
    public $cart_id = NULL;
    public $amount = NULL;
    public $first_name = NULL;
    public $last_name = NULL;
    public $email = NULL;
    public $phone = NULL;
    public $address1 = NULL;
    public $address2 = NULL;
    public $city = NULL;
    public $state_province = NULL;
    public $postal_code = NULL;
    public $country = NULL;
    public $has_billing_eq_shipping = NULL;
    public $transaction_id = NULL;
    public $transaction_code = NULL;
    public $transaction_metadata = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'purchase_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'is_complete' => 
          array (
          ),
          'merchandise_batch_file' => 
          array (
          ),
          'subscription_batch_file' => 
          array (
          ),
          'cart_id' => 
          array (
          ),
          'amount' => 
          array (
          ),
          'first_name' => 
          array (
          ),
          'last_name' => 
          array (
          ),
          'email' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state_province' => 
          array (
          ),
          'postal_code' => 
          array (
          ),
          'country' => 
          array (
          ),
          'has_billing_eq_shipping' => 
          array (
          ),
          'transaction_id' => 
          array (
          ),
          'transaction_code' => 
          array (
          ),
          'transaction_metadata' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>