<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AuthorizationCode
  */
namespace DBCore\Authentication;

use phpr\Database\Model;

class AuthorizationCode extends Model {

    const SCHEMA = 'authentication';
    const TABLE = 'authorization_code';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'code',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'code',
          1 => 'client_id',
          2 => 'service_id',
          3 => 'expires_at',
          4 => 'created_at',
        );

    public $code = NULL;
    public $client_id = NULL;
    public $service_id = NULL;
    public $redirect_uri = NULL;
    public $expires_at = NULL;
    public $scope = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'code' => 
          array (
            0 => 1,
          ),
          'client_id' => 
          array (
          ),
          'service_id' => 
          array (
          ),
          'redirect_uri' => 
          array (
          ),
          'expires_at' => 
          array (
          ),
          'scope' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>