<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Client
  */
namespace DBCore\Authentication;

use phpr\Database\Model;

class Client extends Model {

    const SCHEMA = 'authentication';
    const TABLE = 'client';
    const AUTO_INCREMENT_COLUMN = 'client_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'client_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'client_id',
          1 => 'service_id',
          2 => 'public_key',
          3 => 'secret_key',
          4 => 'redirect_uri',
          5 => 'rate_limit',
          6 => 'client_name',
          7 => 'unit_id',
          8 => 'is_active',
          9 => 'created_at',
          10 => 'updated_at',
        );

    public $client_id = NULL;
    public $service_id = NULL;
    public $public_key = NULL;
    public $secret_key = NULL;
    public $redirect_uri = NULL;
    public $grant_types = NULL;
    public $scope = NULL;
    public $rate_limit = NULL;
    public $client_name = NULL;
    public $description = NULL;
    public $unit_id = NULL;
    public $is_active = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'client_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'service_id' => 
          array (
          ),
          'public_key' => 
          array (
          ),
          'secret_key' => 
          array (
          ),
          'redirect_uri' => 
          array (
          ),
          'grant_types' => 
          array (
          ),
          'scope' => 
          array (
          ),
          'rate_limit' => 
          array (
          ),
          'client_name' => 
          array (
          ),
          'description' => 
          array (
          ),
          'unit_id' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>