<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Assets
  */
namespace DBCore\Bizjphp;

use phpr\Database\Model;

class Assets extends Model {

    const SCHEMA = 'bizjphp';
    const TABLE = 'assets';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'filename',
          2 => 'content',
        );

    public $id = NULL;
    public $filename = NULL;
    public $content = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'filename' => 
          array (
          ),
          'content' => 
          array (
          ),
        );




}

?>