<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Invoices
  */
namespace DBCore\Bizjphp;

use phpr\Database\Model;

class Invoices extends Model {

    const SCHEMA = 'bizjphp';
    const TABLE = 'invoices';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'market_code',
          1 => 'subscription_number',
          2 => 'invoice_number',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'market_code',
          1 => 'subscription_number',
          2 => 'invoice_number',
          3 => 'zip',
          4 => 'invoice_date',
          5 => 'copies',
          6 => 'amount_due',
          7 => 'billing_data',
        );

    public $market_code = NULL;
    public $subscription_number = NULL;
    public $invoice_number = NULL;
    public $zip = NULL;
    public $invoice_date = NULL;
    public $copies = NULL;
    public $amount_due = NULL;
    public $billing_data = NULL;
    public $DBColumnsArray = 
        array (
          'market_code' => 
          array (
            0 => 1,
          ),
          'subscription_number' => 
          array (
            0 => 1,
          ),
          'invoice_number' => 
          array (
            0 => 1,
          ),
          'zip' => 
          array (
          ),
          'invoice_date' => 
          array (
          ),
          'copies' => 
          array (
          ),
          'amount_due' => 
          array (
          ),
          'billing_data' => 
          array (
          ),
        );




}

?>