<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Redirect
  */
namespace DBCore\Bizjphp;

use phpr\Database\Model;

class Redirect extends Model {

    const SCHEMA = 'bizjphp';
    const TABLE = 'redirect';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'redirect_from',
          2 => 'redirect_to',
          3 => 'created_at',
        );

    public $id = NULL;
    public $redirect_from = NULL;
    public $redirect_to = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'redirect_from' => 
          array (
          ),
          'redirect_to' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>