<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in History
  */
namespace DBCore\Medialibrary;

use phpr\Database\Model;

class History extends Model {

    const SCHEMA = 'medialibrary';
    const TABLE = 'history';
    const AUTO_INCREMENT_COLUMN = 'history_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'history_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'history_id',
          1 => 'object_type',
          2 => 'object_id',
          3 => 'created_at',
        );

    public $history_id = NULL;
    public $object_type = NULL;
    public $object_id = NULL;
    public $detail = NULL;
    public $note = NULL;
    public $username = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'history_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'object_type' => 
          array (
          ),
          'object_id' => 
          array (
          ),
          'detail' => 
          array (
          ),
          'note' => 
          array (
          ),
          'username' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>