<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in KrangMediaExport
  */
namespace DBCore\Medialibrary;

use phpr\Database\Model;

class KrangMediaExport extends Model {

    const SCHEMA = 'medialibrary';
    const TABLE = 'krang_media_export';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'media_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'media_id',
          1 => 'media_type_id',
        );

    public $media_id = NULL;
    public $media_type_id = NULL;
    public $mime_type = NULL;
    public $location_url = NULL;
    public $filename = NULL;
    public $title = NULL;
    public $caption = NULL;
    public $copyright = NULL;
    public $publish_date = NULL;
    public $DBColumnsArray = 
        array (
          'media_id' => 
          array (
            0 => 1,
          ),
          'media_type_id' => 
          array (
          ),
          'mime_type' => 
          array (
          ),
          'location_url' => 
          array (
          ),
          'filename' => 
          array (
          ),
          'title' => 
          array (
          ),
          'caption' => 
          array (
          ),
          'copyright' => 
          array (
          ),
          'publish_date' => 
          array (
          ),
        );




}

?>