<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MediaDeleted
  */
namespace DBCore\Medialibrary;

use phpr\Database\Model;

class MediaDeleted extends Model {

    const SCHEMA = 'medialibrary';
    const TABLE = 'media_deleted';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'media_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'media_id',
        );

    public $media_id = NULL;
    public $relative_path = NULL;
    public $filename = NULL;
    public $created_at = NULL;
    public $deleted_at = NULL;
    public $DBColumnsArray = 
        array (
          'media_id' => 
          array (
            0 => 1,
          ),
          'relative_path' => 
          array (
          ),
          'filename' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'deleted_at' => 
          array (
          ),
        );




}

?>