<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MediaLink
  */
namespace DBCore\Medialibrary;

use phpr\Database\Model;

class MediaLink extends Model {

    const SCHEMA = 'medialibrary';
    const TABLE = 'media_link';
    const AUTO_INCREMENT_COLUMN = 'link_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'link_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'link_id',
          1 => 'media_id',
          2 => 'pub_id',
          3 => 'use_source',
          4 => 'cms_id',
          5 => 'page_url',
          6 => 'created_at',
          7 => 'updated_at',
        );

    public $link_id = NULL;
    public $media_id = NULL;
    public $pub_id = NULL;
    public $use_source = NULL;
    public $cms_id = NULL;
    public $page_url = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'link_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'media_id' => 
          array (
          ),
          'pub_id' => 
          array (
          ),
          'use_source' => 
          array (
          ),
          'cms_id' => 
          array (
          ),
          'page_url' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>