<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NascarProductMedia
  */
namespace DBCore\Medialibrary;

use phpr\Database\Model;

class NascarProductMedia extends Model {

    const SCHEMA = 'medialibrary';
    const TABLE = 'nascar_product_media';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'product_id',
          2 => 'image_type',
        );

    public $id = NULL;
    public $product_id = NULL;
    public $image_type = NULL;
    public $mime_type = NULL;
    public $file_size = NULL;
    public $file_path = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'product_id' => 
          array (
          ),
          'image_type' => 
          array (
          ),
          'mime_type' => 
          array (
          ),
          'file_size' => 
          array (
          ),
          'file_path' => 
          array (
          ),
        );




}

?>