<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Tag
  */
namespace DBCore\Medialibrary;

use phpr\Database\Model;

class Tag extends Model {

    const SCHEMA = 'medialibrary';
    const TABLE = 'tag';
    const AUTO_INCREMENT_COLUMN = 'tag_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'tag_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'tag_id',
          1 => 'tag_name',
          2 => 'tag_type',
          3 => 'created_at',
        );

    public $tag_id = NULL;
    public $tag_name = NULL;
    public $tag_type = NULL;
    public $pub_id = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'tag_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'tag_name' => 
          array (
          ),
          'tag_type' => 
          array (
          ),
          'pub_id' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>