<?php

namespace DBCore\Datahub;

use Scoop\Database\Model;

/**
 * Class DatasetEntries
 * @package DBCore\Datahub
 * @author jrobinson (robotically)
 * @date 2016/07/05
 * @property mixed $id
 * @property mixed $dataset_id
 * @property mixed $ranked
 * @property mixed $companyInstanceId
 * @property mixed $meta
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Datahub\DatasetEntries
 */
class DatasetEntries extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'dataset_entries';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'companyInstanceId',
        );

    public static $dBColumnPropertiesArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'dataset_id' => 
          array (
          ),
          'ranked' => 
          array (
          ),
          'companyInstanceId' => 
          array (
          ),
          'meta' => 
          array (
          ),
        );
    public static $dBColumnDefaultValuesArray = 
        array (
          'id' => NULL,
          'dataset_id' => NULL,
          'ranked' => NULL,
          'companyInstanceId' => NULL,
          'meta' => NULL,
        );

}

?>