<?php

namespace DBCore\Datahub;

use Scoop\Database\Model;

/**
 * Class PageCrossref
 * @package DBCore\Datahub
 * @author jrobinson (robotically)
 * @date 2016/06/14
 * @property mixed $ref_id
 * @property mixed $page_id
 * @property mixed $ref_type
 * @property mixed $issue_date
 * @property mixed $ref_key
 * @property mixed $ref_value
 * @property mixed $ref_weight
 * @property mixed $created_at
 * @property mixed $updated_at
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Datahub\PageCrossref
 */
class PageCrossref extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'page_crossref';
    const AUTO_INCREMENT_COLUMN = 'ref_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'ref_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'ref_id',
          1 => 'page_id',
          2 => 'issue_date',
          3 => 'created_at',
          4 => 'updated_at',
        );

    public static $dBColumnPropertiesArray = 
        array (
          'ref_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'page_id' => 
          array (
          ),
          'ref_type' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'ref_key' => 
          array (
          ),
          'ref_value' => 
          array (
          ),
          'ref_weight' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );

    protected $dBValuesArray = 
        array (
          'ref_id' => NULL,
          'page_id' => NULL,
          'ref_type' => NULL,
          'issue_date' => NULL,
          'ref_key' => NULL,
          'ref_value' => NULL,
          'ref_weight' => NULL,
          'created_at' => NULL,
          'updated_at' => NULL,
        );

}

?>