<?php

namespace DBCore\Datahub;

use Scoop\Database\Model;

/**
 * Class SicCodeMeroveusIndustryMap
 * @package DBCore\Datahub
 * @author jrobinson (robotically)
 * @date 2016/05/20
 * @property mixed $sic
 * @property mixed $meroveus_industry_id
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Datahub\SicCodeMeroveusIndustryMap
 */
class SicCodeMeroveusIndustryMap extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'sic_code_meroveus_industry_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'sic',
          1 => 'meroveus_industry_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'sic',
          1 => 'meroveus_industry_id',
        );

    public static $dBColumnPropertiesArray = 
        array (
          'sic' => 
          array (
            0 => 1,
          ),
          'meroveus_industry_id' => 
          array (
            0 => 1,
          ),
        );

    protected $dBValuesArray = 
        array (
          'sic' => NULL,
          'meroveus_industry_id' => NULL,
        );

}

?>