<?php

namespace DBCore\Datahub;

use Scoop\Database\Model;

/**
 * Class State
 * @package DBCore\Datahub
 * @author jrobinson (robotically)
 * @date 2016/09/27
 * @property mixed $stateId
 * @property mixed $countryId
 * @property mixed $name
 * @property mixed $code
 * @property mixed $state_ap_style
 * @property mixed $is_active
 * @property mixed $ord
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Datahub\State
 */
class State extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'state';
    const AUTO_INCREMENT_COLUMN = 'stateId';
    const PRIMARY_KEYS = 
        array (
          0 => 'stateId',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'stateId',
          1 => 'code',
          2 => 'is_active',
          3 => 'ord',
        );

    public static $dBColumnPropertiesArray = 
        array (
          'stateId' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'countryId' => 
          array (
          ),
          'name' => 
          array (
          ),
          'code' => 
          array (
          ),
          'state_ap_style' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'ord' => 
          array (
          ),
        );
    public static $dBColumnDefaultValuesArray = 
        array (
          'stateId' => NULL,
          'countryId' => NULL,
          'name' => NULL,
          'code' => NULL,
          'state_ap_style' => NULL,
          'is_active' => '1',
          'ord' => '0',
        );

}

?>
