<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MaterialsFieldsList
  */
namespace DBCore\Bilt;

use phpr\Database\Model;

class MaterialsFieldsList extends Model {

    const SCHEMA = 'bilt';
    const TABLE = 'materials_fields_list';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'materials_fields_id',
          2 => 'name',
        );

    public $id = NULL;
    public $materials_fields_id = NULL;
    public $parent_id = NULL;
    public $name = NULL;
    public $is_default = NULL;
    public $is_default_filter = NULL;
    public $background_color = NULL;
    public $sort_order = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'materials_fields_id' => 
          array (
          ),
          'parent_id' => 
          array (
          ),
          'name' => 
          array (
          ),
          'is_default' => 
          array (
          ),
          'is_default_filter' => 
          array (
          ),
          'background_color' => 
          array (
          ),
          'sort_order' => 
          array (
          ),
        );




}

?>