<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MaterialsReports
  */
namespace DBCore\Bilt;

use phpr\Database\Model;

class MaterialsReports extends Model {

    const SCHEMA = 'bilt';
    const TABLE = 'materials_reports';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'materials_types_id',
          2 => 'name',
        );

    public $id = NULL;
    public $materials_types_id = NULL;
    public $users_groups_id = NULL;
    public $is_mandatory = NULL;
    public $type = NULL;
    public $name = NULL;
    public $display_in_dashboard = NULL;
    public $display_in_menu = NULL;
    public $fields_in_listing = NULL;
    public $sort_order = NULL;
    public $users_id = NULL;
    public $display_only_assigned = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'materials_types_id' => 
          array (
          ),
          'users_groups_id' => 
          array (
          ),
          'is_mandatory' => 
          array (
          ),
          'type' => 
          array (
          ),
          'name' => 
          array (
          ),
          'display_in_dashboard' => 
          array (
          ),
          'display_in_menu' => 
          array (
          ),
          'fields_in_listing' => 
          array (
          ),
          'sort_order' => 
          array (
          ),
          'users_id' => 
          array (
          ),
          'display_only_assigned' => 
          array (
          ),
        );




}

?>