<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MaterialsFields
  */
namespace DBCore\Bilt;

use phpr\Database\Model;

class MaterialsFields extends Model {

    const SCHEMA = 'bilt';
    const TABLE = 'materials_fields';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'materials_types_id',
          2 => 'name',
          3 => 'type',
          4 => 'form_tab_id',
        );

    public $id = NULL;
    public $materials_types_id = NULL;
    public $name = NULL;
    public $short_name = NULL;
    public $tooltip = NULL;
    public $type = NULL;
    public $form_tab_id = NULL;
    public $form_fieldset_id = NULL;
    public $form_field_position = NULL;
    public $form_sort_order = NULL;
    public $listing_status = NULL;
    public $listing_sort_order = NULL;
    public $display_in_comments = NULL;
    public $is_heading = NULL;
    public $is_required = NULL;
    public $default_sorting = NULL;
    public $required_message = NULL;
    public $css_style = NULL;
    public $settings = NULL;
    public $is_common_filter = NULL;
    public $use_for_filter = NULL;
    public $use_for_search = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'materials_types_id' => 
          array (
          ),
          'name' => 
          array (
          ),
          'short_name' => 
          array (
          ),
          'tooltip' => 
          array (
          ),
          'type' => 
          array (
          ),
          'form_tab_id' => 
          array (
          ),
          'form_fieldset_id' => 
          array (
          ),
          'form_field_position' => 
          array (
          ),
          'form_sort_order' => 
          array (
          ),
          'listing_status' => 
          array (
          ),
          'listing_sort_order' => 
          array (
          ),
          'display_in_comments' => 
          array (
          ),
          'is_heading' => 
          array (
          ),
          'is_required' => 
          array (
          ),
          'default_sorting' => 
          array (
          ),
          'required_message' => 
          array (
          ),
          'css_style' => 
          array (
          ),
          'settings' => 
          array (
          ),
          'is_common_filter' => 
          array (
          ),
          'use_for_filter' => 
          array (
          ),
          'use_for_search' => 
          array (
          ),
        );




}

?>