<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MaterialsTypesFormTabs
  */
namespace DBCore\Bilt;

use phpr\Database\Model;

class MaterialsTypesFormTabs extends Model {

    const SCHEMA = 'bilt';
    const TABLE = 'materials_types_form_tabs';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'materials_types_id',
          2 => 'name',
        );

    public $id = NULL;
    public $materials_types_id = NULL;
    public $parent_id = NULL;
    public $name = NULL;
    public $description = NULL;
    public $is_default = NULL;
    public $sort_order = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'materials_types_id' => 
          array (
          ),
          'parent_id' => 
          array (
          ),
          'name' => 
          array (
          ),
          'description' => 
          array (
          ),
          'is_default' => 
          array (
          ),
          'sort_order' => 
          array (
          ),
        );




}

?>