<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MaterialsFieldsValues
  */
namespace DBCore\Bilt;

use phpr\Database\Model;

class MaterialsFieldsValues extends Model {

    const SCHEMA = 'bilt';
    const TABLE = 'materials_fields_values';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'materials_fields_id',
        );

    public $id = NULL;
    public $materials_fields_id = NULL;
    public $materials_id = NULL;
    public $users_id = NULL;
    public $value = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'materials_fields_id' => 
          array (
          ),
          'materials_id' => 
          array (
          ),
          'users_id' => 
          array (
          ),
          'value' => 
          array (
          ),
        );




}

?>