<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in WikiHistory
  */
namespace DBCore\Bilt;

use phpr\Database\Model;

class WikiHistory extends Model {

    const SCHEMA = 'bilt';
    const TABLE = 'wiki_history';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'wiki_id',
          2 => 'users_id',
        );

    public $id = NULL;
    public $wiki_id = NULL;
    public $materials_id = NULL;
    public $name = NULL;
    public $description = NULL;
    public $users_id = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'wiki_id' => 
          array (
          ),
          'materials_id' => 
          array (
          ),
          'name' => 
          array (
          ),
          'description' => 
          array (
          ),
          'users_id' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>