<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BrandingTemplates
  */
namespace DBCore\BizjmerchantTest;

use phpr\Database\Model;

class BrandingTemplates extends Model {

    const SCHEMA = 'bizjmerchant_test';
    const TABLE = 'branding_templates';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'merchant_id',
          2 => 'type',
          3 => 'image_dir',
          4 => 'stylesheet',
          5 => 'html_template',
        );

    public $id = NULL;
    public $merchant_id = NULL;
    public $type = NULL;
    public $image_dir = NULL;
    public $stylesheet = NULL;
    public $html_template = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'merchant_id' => 
          array (
          ),
          'type' => 
          array (
          ),
          'image_dir' => 
          array (
          ),
          'stylesheet' => 
          array (
          ),
          'html_template' => 
          array (
          ),
        );




}

?>