<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MerchantInvoices
  */
namespace DBCore\BizjmerchantTest;

use phpr\Database\Model;

class MerchantInvoices extends Model {

    const SCHEMA = 'bizjmerchant_test';
    const TABLE = 'merchant_invoices';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'merchant_id',
          2 => 'merchant_transaction_ref_id',
          3 => 'created_at',
          4 => 'updated_at',
        );

    public $id = NULL;
    public $merchant_id = NULL;
    public $merchant_transaction_ref_id = NULL;
    public $payment_amount = NULL;
    public $recurring_amount = NULL;
    public $billing_first = NULL;
    public $billing_middle = NULL;
    public $billing_last = NULL;
    public $billing_company = NULL;
    public $billing_address1 = NULL;
    public $billing_address2 = NULL;
    public $billing_city = NULL;
    public $billing_state = NULL;
    public $billing_zip = NULL;
    public $billing_country = NULL;
    public $billing_email = NULL;
    public $billing_phone = NULL;
    public $shipping_first = NULL;
    public $shipping_middle = NULL;
    public $shipping_last = NULL;
    public $shipping_company = NULL;
    public $shipping_address1 = NULL;
    public $shipping_address2 = NULL;
    public $shipping_city = NULL;
    public $shipping_state = NULL;
    public $shipping_zip = NULL;
    public $shipping_country = NULL;
    public $shipping_email = NULL;
    public $shipping_phone = NULL;
    public $cc_number = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'merchant_id' => 
          array (
          ),
          'merchant_transaction_ref_id' => 
          array (
          ),
          'payment_amount' => 
          array (
          ),
          'recurring_amount' => 
          array (
          ),
          'billing_first' => 
          array (
          ),
          'billing_middle' => 
          array (
          ),
          'billing_last' => 
          array (
          ),
          'billing_company' => 
          array (
          ),
          'billing_address1' => 
          array (
          ),
          'billing_address2' => 
          array (
          ),
          'billing_city' => 
          array (
          ),
          'billing_state' => 
          array (
          ),
          'billing_zip' => 
          array (
          ),
          'billing_country' => 
          array (
          ),
          'billing_email' => 
          array (
          ),
          'billing_phone' => 
          array (
          ),
          'shipping_first' => 
          array (
          ),
          'shipping_middle' => 
          array (
          ),
          'shipping_last' => 
          array (
          ),
          'shipping_company' => 
          array (
          ),
          'shipping_address1' => 
          array (
          ),
          'shipping_address2' => 
          array (
          ),
          'shipping_city' => 
          array (
          ),
          'shipping_state' => 
          array (
          ),
          'shipping_zip' => 
          array (
          ),
          'shipping_country' => 
          array (
          ),
          'shipping_email' => 
          array (
          ),
          'shipping_phone' => 
          array (
          ),
          'cc_number' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>