<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SfGuardUserProfile
  */
namespace DBCore\BizjmerchantTest;

use phpr\Database\Model;

class SfGuardUserProfile extends Model {

    const SCHEMA = 'bizjmerchant_test';
    const TABLE = 'sf_guard_user_profile';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $sf_guard_user_id = NULL;
    public $merchant_id = NULL;
    public $email = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'sf_guard_user_id' => 
          array (
          ),
          'merchant_id' => 
          array (
          ),
          'email' => 
          array (
          ),
        );




}

?>