<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BusinessLicenses
  */
namespace DBCore\Bizjleads;

use phpr\Database\Model;

class BusinessLicenses extends Model {

    const SCHEMA = 'bizjleads';
    const TABLE = 'business_licenses';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'proof_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'proof_id',
          1 => 'created_at',
          2 => 'updated_at',
        );

    public $proof_id = NULL;
    public $company = NULL;
    public $first_name = NULL;
    public $last_name = NULL;
    public $address = NULL;
    public $city = NULL;
    public $state = NULL;
    public $zip = NULL;
    public $business_type = NULL;
    public $rec_date = NULL;
    public $juris_id = NULL;
    public $subtype = NULL;
    public $sic_id = NULL;
    public $phone = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'proof_id' => 
          array (
            0 => 1,
          ),
          'company' => 
          array (
          ),
          'first_name' => 
          array (
          ),
          'last_name' => 
          array (
          ),
          'address' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'zip' => 
          array (
          ),
          'business_type' => 
          array (
          ),
          'rec_date' => 
          array (
          ),
          'juris_id' => 
          array (
          ),
          'subtype' => 
          array (
          ),
          'sic_id' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>