<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SicCategoryMap
  */
namespace DBCore\Bizjleads;

use phpr\Database\Model;

class SicCategoryMap extends Model {

    const SCHEMA = 'bizjleads';
    const TABLE = 'sic_category_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'sic_id',
          1 => 'category_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'sic_id',
          1 => 'category_id',
        );

    public $sic_id = NULL;
    public $category_id = NULL;
    public $DBColumnsArray = 
        array (
          'sic_id' => 
          array (
            0 => 1,
          ),
          'category_id' => 
          array (
            0 => 1,
          ),
        );




}

?>