<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in User
  */
namespace DBCore\Bizjstatus;

use phpr\Database\Model;

class User extends Model {

    const SCHEMA = 'bizjstatus';
    const TABLE = 'user';
    const AUTO_INCREMENT_COLUMN = 'user_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'password',
        );

    public $user_id = NULL;
    public $username = NULL;
    public $email = NULL;
    public $display_name = NULL;
    public $password = NULL;
    public $state = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'username' => 
          array (
          ),
          'email' => 
          array (
          ),
          'display_name' => 
          array (
          ),
          'password' => 
          array (
          ),
          'state' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>