<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AdviceLibraryStories
  */
namespace DBCore\Story;

use phpr\Database\Model;

class AdviceLibraryStories extends Model {

    const SCHEMA = 'story';
    const TABLE = 'advice_library_stories';
    const AUTO_INCREMENT_COLUMN = 'doc_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'doc_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'doc_id',
          1 => 'm_time',
        );

    public $doc_id = NULL;
    public $category = NULL;
    public $filename = NULL;
    public $headline = NULL;
    public $sidebar = NULL;
    public $doc = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $category_id = NULL;
    public $DBColumnsArray = 
        array (
          'doc_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'category' => 
          array (
          ),
          'filename' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'sidebar' => 
          array (
          ),
          'doc' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'category_id' => 
          array (
          ),
        );




}

?>