<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BreakingNews
  */
namespace DBCore\Story;

use phpr\Database\Model;

class BreakingNews extends Model {

    const SCHEMA = 'story';
    const TABLE = 'breaking_news';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'story_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'story_id',
          1 => 'expires',
          2 => 'display_order',
        );

    public $story_id = NULL;
    public $expires = NULL;
    public $display_order = NULL;
    public $DBColumnsArray = 
        array (
          'story_id' => 
          array (
            0 => 1,
          ),
          'expires' => 
          array (
          ),
          'display_order' => 
          array (
          ),
        );




}

?>