<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Company
  */
namespace DBCore\Story;

use phpr\Database\Model;

class Company extends Model {

    const SCHEMA = 'story';
    const TABLE = 'company';
    const AUTO_INCREMENT_COLUMN = 'company_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'company_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'company_id',
          1 => 'c_time',
          2 => 'company_name',
          3 => 'is_public',
        );

    public $company_id = NULL;
    public $c_time = NULL;
    public $company_name = NULL;
    public $is_public = NULL;
    public $symbol = NULL;
    public $stock_exchange = NULL;
    public $aka_company_id = NULL;
    public $DBColumnsArray = 
        array (
          'company_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'c_time' => 
          array (
          ),
          'company_name' => 
          array (
          ),
          'is_public' => 
          array (
          ),
          'symbol' => 
          array (
          ),
          'stock_exchange' => 
          array (
          ),
          'aka_company_id' => 
          array (
          ),
        );




}

?>