<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DemographicsChart
  */
namespace DBCore\Story;

use phpr\Database\Model;

class DemographicsChart extends Model {

    const SCHEMA = 'story';
    const TABLE = 'demographics_chart';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'report_id',
        );

    public $report_id = NULL;
    public $filename = NULL;
    public $chart_title = NULL;
    public $DBColumnsArray = 
        array (
          'report_id' => 
          array (
          ),
          'filename' => 
          array (
          ),
          'chart_title' => 
          array (
          ),
        );




}

?>