<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DemodailyData
  */
namespace DBCore\Story;

use phpr\Database\Model;

class DemodailyData extends Model {

    const SCHEMA = 'story';
    const TABLE = 'demodaily_data';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'chart_id',
          1 => 'story_id',
          2 => 'category',
        );

    public $chart_id = NULL;
    public $story_id = NULL;
    public $data_text = NULL;
    public $data_xls = NULL;
    public $title = NULL;
    public $chart_num = NULL;
    public $category = NULL;
    public $subcategory = NULL;
    public $DBColumnsArray = 
        array (
          'chart_id' => 
          array (
          ),
          'story_id' => 
          array (
          ),
          'data_text' => 
          array (
          ),
          'data_xls' => 
          array (
          ),
          'title' => 
          array (
          ),
          'chart_num' => 
          array (
          ),
          'category' => 
          array (
          ),
          'subcategory' => 
          array (
          ),
        );




}

?>