<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EditorialSpecial
  */
namespace DBCore\Story;

use phpr\Database\Model;

class EditorialSpecial extends Model {

    const SCHEMA = 'story';
    const TABLE = 'editorial_special';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'm_time',
        );

    public $id = NULL;
    public $feature_date = NULL;
    public $pos = NULL;
    public $m_time = NULL;
    public $description = NULL;
    public $special_id = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'feature_date' => 
          array (
          ),
          'pos' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'description' => 
          array (
          ),
          'special_id' => 
          array (
          ),
        );




}

?>