<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in FeatureHireVertical
  */
namespace DBCore\Story;

use phpr\Database\Model;

class FeatureHireVertical extends Model {

    const SCHEMA = 'story';
    const TABLE = 'feature_hire_vertical';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'm_time',
        );

    public $id = NULL;
    public $story_id = NULL;
    public $vertical_subtopic_id = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'story_id' => 
          array (
          ),
          'vertical_subtopic_id' => 
          array (
          ),
          'm_time' => 
          array (
          ),
        );




}

?>