<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in FeaturedBizresources
  */
namespace DBCore\Story;

use phpr\Database\Model;

class FeaturedBizresources extends Model {

    const SCHEMA = 'story';
    const TABLE = 'featured_bizresources';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $story_id = NULL;
    public $market = NULL;
    public $headline = NULL;
    public $subhead = NULL;
    public $teaser = NULL;
    public $pub_date = NULL;
    public $filename = NULL;
    public $page_type = NULL;
    public $page_date = NULL;
    public $c_time = NULL;
    public $image_id = NULL;
    public $biz_head = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'story_id' => 
          array (
          ),
          'market' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'subhead' => 
          array (
          ),
          'teaser' => 
          array (
          ),
          'pub_date' => 
          array (
          ),
          'filename' => 
          array (
          ),
          'page_type' => 
          array (
          ),
          'page_date' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'image_id' => 
          array (
          ),
          'biz_head' => 
          array (
          ),
        );




}

?>