<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in FeatureResourceCenter
  */
namespace DBCore\Story;

use phpr\Database\Model;

class FeatureResourceCenter extends Model {

    const SCHEMA = 'story';
    const TABLE = 'feature_resource_center';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'm_time',
        );

    public $id = NULL;
    public $section_string = NULL;
    public $feature_date = NULL;
    public $m_time = NULL;
    public $headline = NULL;
    public $teaser = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'section_string' => 
          array (
          ),
          'feature_date' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'teaser' => 
          array (
          ),
        );




}

?>