<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ImportDirectory
  */
namespace DBCore\Story;

use phpr\Database\Model;

class ImportDirectory extends Model {

    const SCHEMA = 'story';
    const TABLE = 'import_directory';
    const AUTO_INCREMENT_COLUMN = 'directory_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'directory_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'directory_id',
          1 => 'directory',
          2 => 'market',
          3 => 'story_date',
        );

    public $directory_id = NULL;
    public $directory = NULL;
    public $market = NULL;
    public $story_date = NULL;
    public $DBColumnsArray = 
        array (
          'directory_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'directory' => 
          array (
          ),
          'market' => 
          array (
          ),
          'story_date' => 
          array (
          ),
        );




}

?>