<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Journal
  */
namespace DBCore\Story;

use phpr\Database\Model;

class Journal extends Model {

    const SCHEMA = 'story';
    const TABLE = 'journal';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'market',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'market',
        );

    public $market = NULL;
    public $circ_mgr_first_name = NULL;
    public $circ_mgr_last_name = NULL;
    public $circ_mgr_title = NULL;
    public $sub_1_year_price = NULL;
    public $sub_2_year_price = NULL;
    public $sub_3_year_price = NULL;
    public $bol_price = NULL;
    public $bol_month_published = NULL;
    public $trial_sub_weeks = NULL;
    public $circ_phone = NULL;
    public $circ_fax = NULL;
    public $circ_mgr_email = NULL;
    public $bol_title = NULL;
    public $address_1 = NULL;
    public $address_2 = NULL;
    public $city_postal = NULL;
    public $state = NULL;
    public $zip = NULL;
    public $phone = NULL;
    public $fax = NULL;
    public $adv_mgr_first_name = NULL;
    public $adv_mgr_last_name = NULL;
    public $adv_mgr_title = NULL;
    public $adv_mgr_email = NULL;
    public $adv_phone = NULL;
    public $adv_fax = NULL;
    public $news_phone = NULL;
    public $news_fax = NULL;
    public $sales_tax = NULL;
    public $bol_price_includes_tax = NULL;
    public $sub_price_includes_tax = NULL;
    public $bol_ship_cost = NULL;
    public $bol_price_includes_ship_cost = NULL;
    public $bol_sales_tax_extra = NULL;
    public $sub_sales_tax_extra = NULL;
    public $bizrec_has_homeowner = NULL;
    public $bizrec_sample_prefix = NULL;
    public $publisher_first_name = NULL;
    public $publisher_last_name = NULL;
    public $publisher_email = NULL;
    public $city = NULL;
    public $DBColumnsArray = 
        array (
          'market' => 
          array (
            0 => 1,
          ),
          'circ_mgr_first_name' => 
          array (
          ),
          'circ_mgr_last_name' => 
          array (
          ),
          'circ_mgr_title' => 
          array (
          ),
          'sub_1_year_price' => 
          array (
          ),
          'sub_2_year_price' => 
          array (
          ),
          'sub_3_year_price' => 
          array (
          ),
          'bol_price' => 
          array (
          ),
          'bol_month_published' => 
          array (
          ),
          'trial_sub_weeks' => 
          array (
          ),
          'circ_phone' => 
          array (
          ),
          'circ_fax' => 
          array (
          ),
          'circ_mgr_email' => 
          array (
          ),
          'bol_title' => 
          array (
          ),
          'address_1' => 
          array (
          ),
          'address_2' => 
          array (
          ),
          'city_postal' => 
          array (
          ),
          'state' => 
          array (
          ),
          'zip' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'fax' => 
          array (
          ),
          'adv_mgr_first_name' => 
          array (
          ),
          'adv_mgr_last_name' => 
          array (
          ),
          'adv_mgr_title' => 
          array (
          ),
          'adv_mgr_email' => 
          array (
          ),
          'adv_phone' => 
          array (
          ),
          'adv_fax' => 
          array (
          ),
          'news_phone' => 
          array (
          ),
          'news_fax' => 
          array (
          ),
          'sales_tax' => 
          array (
          ),
          'bol_price_includes_tax' => 
          array (
          ),
          'sub_price_includes_tax' => 
          array (
          ),
          'bol_ship_cost' => 
          array (
          ),
          'bol_price_includes_ship_cost' => 
          array (
          ),
          'bol_sales_tax_extra' => 
          array (
          ),
          'sub_sales_tax_extra' => 
          array (
          ),
          'bizrec_has_homeowner' => 
          array (
          ),
          'bizrec_sample_prefix' => 
          array (
          ),
          'publisher_first_name' => 
          array (
          ),
          'publisher_last_name' => 
          array (
          ),
          'publisher_email' => 
          array (
          ),
          'city' => 
          array (
          ),
        );




}

?>