<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NeTopic
  */
namespace DBCore\Story;

use phpr\Database\Model;

class NeTopic extends Model {

    const SCHEMA = 'story';
    const TABLE = 'ne_topic';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'ne_topic_code',
          1 => 'ne_topic',
        );

    public $ne_topic_code = NULL;
    public $ne_topic = NULL;
    public $DBColumnsArray = 
        array (
          'ne_topic_code' => 
          array (
          ),
          'ne_topic' => 
          array (
          ),
        );




}

?>