<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NsteinConcept
  */
namespace DBCore\Story;

use phpr\Database\Model;

class NsteinConcept extends Model {

    const SCHEMA = 'story';
    const TABLE = 'nstein_concept';
    const AUTO_INCREMENT_COLUMN = 'concept_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'concept_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'concept_id',
          1 => 'concept',
          2 => 'is_complex_concept',
        );

    public $concept_id = NULL;
    public $concept = NULL;
    public $is_complex_concept = NULL;
    public $DBColumnsArray = 
        array (
          'concept_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'concept' => 
          array (
          ),
          'is_complex_concept' => 
          array (
          ),
        );




}

?>