<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PageDeletes
  */
namespace DBCore\Story;

use phpr\Database\Model;

class PageDeletes extends Model {

    const SCHEMA = 'story';
    const TABLE = 'page_deletes';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'story_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'story_id',
          1 => 'c_time',
          2 => 'issue_date',
          3 => 'pub',
          4 => 'slug',
        );

    public $story_id = NULL;
    public $c_time = NULL;
    public $issue_date = NULL;
    public $pub = NULL;
    public $slug = NULL;
    public $headline = NULL;
    public $DBColumnsArray = 
        array (
          'story_id' => 
          array (
            0 => 1,
          ),
          'c_time' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'pub' => 
          array (
          ),
          'slug' => 
          array (
          ),
          'headline' => 
          array (
          ),
        );




}

?>