<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PageSpecialCategory
  */
namespace DBCore\Story;

use phpr\Database\Model;

class PageSpecialCategory extends Model {

    const SCHEMA = 'story';
    const TABLE = 'page_special_category';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'story_id',
          1 => 'special_cat_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'story_id',
          1 => 'special_cat_id',
          2 => 'c_time',
        );

    public $story_id = NULL;
    public $special_cat_id = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'story_id' => 
          array (
            0 => 1,
          ),
          'special_cat_id' => 
          array (
            0 => 1,
          ),
          'c_time' => 
          array (
          ),
        );




}

?>