<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PageTag
  */
namespace DBCore\Story;

use phpr\Database\Model;

class PageTag extends Model {

    const SCHEMA = 'story';
    const TABLE = 'page_tag';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'story_id',
          1 => 'ord',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'story_id',
          1 => 'ord',
          2 => 'c_time',
        );

    public $story_id = NULL;
    public $ord = NULL;
    public $tag_name = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'story_id' => 
          array (
            0 => 1,
          ),
          'ord' => 
          array (
            0 => 1,
          ),
          'tag_name' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>