<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PollFieldType
  */
namespace DBCore\Story;

use phpr\Database\Model;

class PollFieldType extends Model {

    const SCHEMA = 'story';
    const TABLE = 'poll_field_type';
    const AUTO_INCREMENT_COLUMN = 'poll_field_type_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'poll_field_type_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'poll_field_type_id',
          1 => 'm_time',
        );

    public $poll_field_type_id = NULL;
    public $description = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'poll_field_type_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'description' => 
          array (
          ),
          'm_time' => 
          array (
          ),
        );




}

?>