<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SponsoredUrl
  */
namespace DBCore\Story;

use phpr\Database\Model;

class SponsoredUrl extends Model {

    const SCHEMA = 'story';
    const TABLE = 'sponsored_url';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'm_time',
        );

    public $id = NULL;
    public $market = NULL;
    public $url = NULL;
    public $link = NULL;
    public $m_time = NULL;
    public $active = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'url' => 
          array (
          ),
          'link' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'active' => 
          array (
          ),
        );




}

?>