<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in StoryExport
  */
namespace DBCore\Story;

use phpr\Database\Model;

class StoryExport extends Model {

    const SCHEMA = 'story';
    const TABLE = 'story_export';
    const AUTO_INCREMENT_COLUMN = 'export_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'export_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'export_id',
        );

    public $export_id = NULL;
    public $story_id = NULL;
    public $alt_headline = NULL;
    public $send_date = NULL;
    public $is_national = NULL;
    public $package_id = NULL;
    public $vertical_subtopic_id = NULL;
    public $partner_id = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'export_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'story_id' => 
          array (
          ),
          'alt_headline' => 
          array (
          ),
          'send_date' => 
          array (
          ),
          'is_national' => 
          array (
          ),
          'package_id' => 
          array (
          ),
          'vertical_subtopic_id' => 
          array (
          ),
          'partner_id' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>