<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in StoryDuRankMarket
  */
namespace DBCore\Story;

use phpr\Database\Model;

class StoryDuRankMarket extends Model {

    const SCHEMA = 'story';
    const TABLE = 'story_du_rank_market';
    const AUTO_INCREMENT_COLUMN = 'rank_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'rank_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'rank_id',
          1 => 'c_time',
        );

    public $rank_id = NULL;
    public $market = NULL;
    public $effective_date = NULL;
    public $story_id = NULL;
    public $rank = NULL;
    public $c_time = NULL;
    public $headline = NULL;
    public $issue_date = NULL;
    public $slug = NULL;
    public $story_type = NULL;
    public $default_skin = NULL;
    public $DBColumnsArray = 
        array (
          'rank_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'effective_date' => 
          array (
          ),
          'story_id' => 
          array (
          ),
          'rank' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'slug' => 
          array (
          ),
          'story_type' => 
          array (
          ),
          'default_skin' => 
          array (
          ),
        );




}

?>