<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in StoryVerticalExclude
  */
namespace DBCore\Story;

use phpr\Database\Model;

class StoryVerticalExclude extends Model {

    const SCHEMA = 'story';
    const TABLE = 'story_vertical_exclude';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'story_id',
          1 => 'vertical_subtopic_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'story_id',
          1 => 'vertical_subtopic_id',
        );

    public $story_id = NULL;
    public $vertical_subtopic_id = NULL;
    public $DBColumnsArray = 
        array (
          'story_id' => 
          array (
            0 => 1,
          ),
          'vertical_subtopic_id' => 
          array (
            0 => 1,
          ),
        );




}

?>