<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in StoryRefiledAsDaily
  */
namespace DBCore\Story;

use phpr\Database\Model;

class StoryRefiledAsDaily extends Model {

    const SCHEMA = 'story';
    const TABLE = 'story_refiled_as_daily';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'm_time',
        );

    public $original_story_id = NULL;
    public $new_story_id = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'original_story_id' => 
          array (
          ),
          'new_story_id' => 
          array (
          ),
          'm_time' => 
          array (
          ),
        );




}

?>