<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UswebStoryLinksArchive
  */
namespace DBCore\Story;

use phpr\Database\Model;

class UswebStoryLinksArchive extends Model {

    const SCHEMA = 'story';
    const TABLE = 'usweb_story_links_archive';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'c_time',
        );

    public $id = NULL;
    public $story_id = NULL;
    public $title = NULL;
    public $url = NULL;
    public $m_time = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
          ),
          'story_id' => 
          array (
          ),
          'title' => 
          array (
          ),
          'url' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>