<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in VerticalFeature
  */
namespace DBCore\Story;

use phpr\Database\Model;

class VerticalFeature extends Model {

    const SCHEMA = 'story';
    const TABLE = 'vertical_feature';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
        );

    public $vertical_topic_id = NULL;
    public $effective_date = NULL;
    public $DBColumnsArray = 
        array (
          'vertical_topic_id' => 
          array (
          ),
          'effective_date' => 
          array (
          ),
        );




}

?>