<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in VerticalStoryCountCache
  */
namespace DBCore\Story;

use phpr\Database\Model;

class VerticalStoryCountCache extends Model {

    const SCHEMA = 'story';
    const TABLE = 'vertical_story_count_cache';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
        );

    public $vertical_subtopic_id = NULL;
    public $story_date = NULL;
    public $story_count = NULL;
    public $DBColumnsArray = 
        array (
          'vertical_subtopic_id' => 
          array (
          ),
          'story_date' => 
          array (
          ),
          'story_count' => 
          array (
          ),
        );




}

?>