<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in VerticalSubtopicNeTopic
  */
namespace DBCore\Story;

use phpr\Database\Model;

class VerticalSubtopicNeTopic extends Model {

    const SCHEMA = 'story';
    const TABLE = 'vertical_subtopic_ne_topic';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'vertical_subtopic_id',
          1 => 'ne_topic_code',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'vertical_subtopic_id',
          1 => 'ne_topic_code',
        );

    public $vertical_subtopic_id = NULL;
    public $ne_topic_code = NULL;
    public $DBColumnsArray = 
        array (
          'vertical_subtopic_id' => 
          array (
            0 => 1,
          ),
          'ne_topic_code' => 
          array (
            0 => 1,
          ),
        );




}

?>