<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in WomenFeature
  */
namespace DBCore\Story;

use phpr\Database\Model;

class WomenFeature extends Model {

    const SCHEMA = 'story';
    const TABLE = 'women_feature';
    const AUTO_INCREMENT_COLUMN = 'feature_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'feature_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'feature_id',
          1 => 'm_time',
        );

    public $feature_id = NULL;
    public $headline = NULL;
    public $copy = NULL;
    public $feature_date = NULL;
    public $m_time = NULL;
    public $market = NULL;
    public $DBColumnsArray = 
        array (
          'feature_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'headline' => 
          array (
          ),
          'copy' => 
          array (
          ),
          'feature_date' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'market' => 
          array (
          ),
        );




}

?>