<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ContentWorkspace
  */
namespace DBCore\Bizjcms;

use phpr\Database\Model;

class ContentWorkspace extends Model {

    const SCHEMA = 'bizjcms';
    const TABLE = 'content_workspace';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'content_id',
          1 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'content_id',
          1 => 'user_id',
          2 => 'user_name',
        );

    public $content_id = NULL;
    public $user_id = NULL;
    public $user_name = NULL;
    public $DBColumnsArray = 
        array (
          'content_id' => 
          array (
            0 => 1,
          ),
          'user_id' => 
          array (
            0 => 1,
          ),
          'user_name' => 
          array (
          ),
        );




}

?>