<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ElasticRecovery
  */
namespace DBCore\Bizjcms;

use phpr\Database\Model;

class ElasticRecovery extends Model {

    const SCHEMA = 'bizjcms';
    const TABLE = 'elastic_recovery';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'action',
          2 => 'index_name',
          3 => 'type_name',
          4 => 'is_processed',
          5 => 'created_at',
        );

    public $id = NULL;
    public $action = NULL;
    public $index_name = NULL;
    public $type_name = NULL;
    public $elasticid = NULL;
    public $struct_data = NULL;
    public $is_processed = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'action' => 
          array (
          ),
          'index_name' => 
          array (
          ),
          'type_name' => 
          array (
          ),
          'elasticid' => 
          array (
          ),
          'struct_data' => 
          array (
          ),
          'is_processed' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>