<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Publication
  */
namespace DBCore\Bizjcms;

use phpr\Database\Model;

class Publication extends Model {

    const SCHEMA = 'bizjcms';
    const TABLE = 'publication';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'pub_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'pub_id',
          1 => 'pub_name',
          2 => 'short_name',
          3 => 'market_code',
          4 => 'publisher_config',
          5 => 'timezone',
          6 => 'default_copyright_notice',
          7 => 'created_at',
          8 => 'updated_at',
        );

    public $pub_id = NULL;
    public $pub_name = NULL;
    public $short_name = NULL;
    public $market_code = NULL;
    public $publisher_config = NULL;
    public $timezone = NULL;
    public $default_copyright_notice = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'pub_id' => 
          array (
            0 => 1,
          ),
          'pub_name' => 
          array (
          ),
          'short_name' => 
          array (
          ),
          'market_code' => 
          array (
          ),
          'publisher_config' => 
          array (
          ),
          'timezone' => 
          array (
          ),
          'default_copyright_notice' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>