<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PublishQueue
  */
namespace DBCore\Bizjcms;

use phpr\Database\Model;

class PublishQueue extends Model {

    const SCHEMA = 'bizjcms';
    const TABLE = 'publish_queue';
    const AUTO_INCREMENT_COLUMN = 'queue_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'queue_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'queue_id',
          1 => 'content_id',
          2 => 'version',
          3 => 'action',
          4 => 'run_at',
          5 => 'queued_by',
          6 => 'queued_at',
          7 => 'is_complete',
          8 => 'has_succeeded',
          9 => 'has_failed',
          10 => 'is_cancelled',
          11 => 'is_overridden',
        );

    public $queue_id = NULL;
    public $content_id = NULL;
    public $version = NULL;
    public $action = NULL;
    public $run_at = NULL;
    public $queued_by = NULL;
    public $queued_at = NULL;
    public $is_complete = NULL;
    public $completed_at = NULL;
    public $has_succeeded = NULL;
    public $has_failed = NULL;
    public $is_cancelled = NULL;
    public $is_overridden = NULL;
    public $override_auditlog_id = NULL;
    public $DBColumnsArray = 
        array (
          'queue_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'content_id' => 
          array (
          ),
          'version' => 
          array (
          ),
          'action' => 
          array (
          ),
          'run_at' => 
          array (
          ),
          'queued_by' => 
          array (
          ),
          'queued_at' => 
          array (
          ),
          'is_complete' => 
          array (
          ),
          'completed_at' => 
          array (
          ),
          'has_succeeded' => 
          array (
          ),
          'has_failed' => 
          array (
          ),
          'is_cancelled' => 
          array (
          ),
          'is_overridden' => 
          array (
          ),
          'override_auditlog_id' => 
          array (
          ),
        );




}

?>