<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Issues
  */
namespace DBCore\OldNascarSite;

use phpr\Database\Model;

class Issues extends Model {

    const SCHEMA = 'old_nascar_site';
    const TABLE = 'issues';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $title = NULL;
    public $summary = NULL;
    public $published_at = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $cover_file_name = NULL;
    public $cover_content_type = NULL;
    public $cover_file_size = NULL;
    public $cover_updated_at = NULL;
    public $state = NULL;
    public $slug = NULL;
    public $in_home_date = NULL;
    public $digital_edition_enabled = NULL;
    public $digital_edition_url = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'title' => 
          array (
          ),
          'summary' => 
          array (
          ),
          'published_at' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'cover_file_name' => 
          array (
          ),
          'cover_content_type' => 
          array (
          ),
          'cover_file_size' => 
          array (
          ),
          'cover_updated_at' => 
          array (
          ),
          'state' => 
          array (
          ),
          'slug' => 
          array (
          ),
          'in_home_date' => 
          array (
          ),
          'digital_edition_enabled' => 
          array (
          ),
          'digital_edition_url' => 
          array (
          ),
        );




}

?>