<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MerchantTransactionRefs
  */
namespace DBCore\Bizjmerchant;

use phpr\Database\Model;

class MerchantTransactionRefs extends Model {

    const SCHEMA = 'bizjmerchant';
    const TABLE = 'merchant_transaction_refs';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'merchant_id',
          2 => 'mtr_token',
          3 => 'payment_process_type',
          4 => 'status',
          5 => 'is_completed',
          6 => 'is_expired',
          7 => 'is_processed',
          8 => 'is_sent',
          9 => 'created_at',
        );

    public $id = NULL;
    public $merchant_id = NULL;
    public $mtr_token = NULL;
    public $payment_process_type = NULL;
    public $settlement_delay = NULL;
    public $status = NULL;
    public $is_completed = NULL;
    public $completed_at = NULL;
    public $is_expired = NULL;
    public $is_processed = NULL;
    public $processed_at = NULL;
    public $authorizing_payflow_pro_transaction_id = NULL;
    public $settling_payflow_pro_transaction_id = NULL;
    public $success_url = NULL;
    public $cancel_url = NULL;
    public $error_url = NULL;
    public $is_sent = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'merchant_id' => 
          array (
          ),
          'mtr_token' => 
          array (
          ),
          'payment_process_type' => 
          array (
          ),
          'settlement_delay' => 
          array (
          ),
          'status' => 
          array (
          ),
          'is_completed' => 
          array (
          ),
          'completed_at' => 
          array (
          ),
          'is_expired' => 
          array (
          ),
          'is_processed' => 
          array (
          ),
          'processed_at' => 
          array (
          ),
          'authorizing_payflow_pro_transaction_id' => 
          array (
          ),
          'settling_payflow_pro_transaction_id' => 
          array (
          ),
          'success_url' => 
          array (
          ),
          'cancel_url' => 
          array (
          ),
          'error_url' => 
          array (
          ),
          'is_sent' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>