<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SfGuardUserGroup
  */
namespace DBCore\Bizjmerchant;

use phpr\Database\Model;

class SfGuardUserGroup extends Model {

    const SCHEMA = 'bizjmerchant';
    const TABLE = 'sf_guard_user_group';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
          1 => 'group_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'group_id',
          2 => 'created_at',
          3 => 'updated_at',
        );

    public $user_id = NULL;
    public $group_id = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
          ),
          'group_id' => 
          array (
            0 => 1,
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>