<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MobileSubscription
  */
namespace DBCore\Bizjcommerce;

use phpr\Database\Model;

class MobileSubscription extends Model {

    const SCHEMA = 'bizjcommerce';
    const TABLE = 'mobile_subscription';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'market_code',
          2 => 'is_cancelled',
          3 => 'created_at',
          4 => 'product_code',
          5 => 'vendor_transaction_id',
          6 => 'vendor_receipt_data',
          7 => 'expires_at',
        );

    public $id = NULL;
    public $user_id = NULL;
    public $market_code = NULL;
    public $billing_data = NULL;
    public $is_cancelled = NULL;
    public $created_at = NULL;
    public $product_code = NULL;
    public $vendor_transaction_id = NULL;
    public $vendor_receipt_data = NULL;
    public $cancelled_at = NULL;
    public $expires_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_id' => 
          array (
          ),
          'market_code' => 
          array (
          ),
          'billing_data' => 
          array (
          ),
          'is_cancelled' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'product_code' => 
          array (
          ),
          'vendor_transaction_id' => 
          array (
          ),
          'vendor_receipt_data' => 
          array (
          ),
          'cancelled_at' => 
          array (
          ),
          'expires_at' => 
          array (
          ),
        );




}

?>