<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ProductBundleProduct
  */
namespace DBCore\Bizjcommerce;

use phpr\Database\Model;

class ProductBundleProduct extends Model {

    const SCHEMA = 'bizjcommerce';
    const TABLE = 'product_bundle_product';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'product_bundle_id',
          1 => 'product_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'product_bundle_id',
          1 => 'product_id',
          2 => 'is_primary',
          3 => 'is_marketed',
          4 => 'price',
        );

    public $product_bundle_id = NULL;
    public $product_id = NULL;
    public $is_primary = NULL;
    public $is_marketed = NULL;
    public $price = NULL;
    public $DBColumnsArray = 
        array (
          'product_bundle_id' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
            0 => 1,
          ),
          'is_primary' => 
          array (
          ),
          'is_marketed' => 
          array (
          ),
          'price' => 
          array (
          ),
        );




}

?>