<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ProductTypeBollistClassification
  */
namespace DBCore\Bizjcommerce;

use phpr\Database\Model;

class ProductTypeBollistClassification extends Model {

    const SCHEMA = 'bizjcommerce';
    const TABLE = 'product_type_bollist_classification';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'classification_name',
        );

    public $id = NULL;
    public $classification_name = NULL;
    public $parent_class_id = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'classification_name' => 
          array (
          ),
          'parent_class_id' => 
          array (
          ),
        );




}

?>