<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PromoCode
  */
namespace DBCore\Bizjcommerce;

use phpr\Database\Model;

class PromoCode extends Model {

    const SCHEMA = 'bizjcommerce';
    const TABLE = 'promo_code';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'promo_code_name',
          2 => 'description',
          3 => 'token',
          4 => 'is_active',
          5 => 'start_date',
          6 => 'end_date',
          7 => 'rebate_type',
          8 => 'fixed_rebate',
          9 => 'percentage_rebate',
          10 => 'quantity_limit',
          11 => 'uses_left',
          12 => 'is_per_item',
          13 => 'is_national',
          14 => 'report_addresses',
          15 => 'created_at',
          16 => 'updated_at',
        );

    public $id = NULL;
    public $promo_code_name = NULL;
    public $description = NULL;
    public $token = NULL;
    public $is_active = NULL;
    public $start_date = NULL;
    public $end_date = NULL;
    public $rebate_type = NULL;
    public $fixed_rebate = NULL;
    public $percentage_rebate = NULL;
    public $quantity_limit = NULL;
    public $uses_left = NULL;
    public $is_per_item = NULL;
    public $is_national = NULL;
    public $report_addresses = NULL;
    public $payment_resolution_type = NULL;
    public $parameters = NULL;
    public $last_updated_by = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'promo_code_name' => 
          array (
          ),
          'description' => 
          array (
          ),
          'token' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'end_date' => 
          array (
          ),
          'rebate_type' => 
          array (
          ),
          'fixed_rebate' => 
          array (
          ),
          'percentage_rebate' => 
          array (
          ),
          'quantity_limit' => 
          array (
          ),
          'uses_left' => 
          array (
          ),
          'is_per_item' => 
          array (
          ),
          'is_national' => 
          array (
          ),
          'report_addresses' => 
          array (
          ),
          'payment_resolution_type' => 
          array (
          ),
          'parameters' => 
          array (
          ),
          'last_updated_by' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>