<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ShoppingCart
  */
namespace DBCore\Bizjcommerce;

use phpr\Database\Model;

class ShoppingCart extends Model {

    const SCHEMA = 'bizjcommerce';
    const TABLE = 'shopping_cart';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'created_at',
          2 => 'updated_at',
        );

    public $id = NULL;
    public $token = NULL;
    public $promo_code_id = NULL;
    public $shipping_type = NULL;
    public $attributes = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'token' => 
          array (
          ),
          'promo_code_id' => 
          array (
          ),
          'shipping_type' => 
          array (
          ),
          'attributes' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>