<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Transaction
  */
namespace DBCore\Bizjcommerce;

use phpr\Database\Model;

class Transaction extends Model {

    const SCHEMA = 'bizjcommerce';
    const TABLE = 'transaction';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'shipping_first_name',
          2 => 'shipping_last_name',
          3 => 'shipping_address1',
          4 => 'shipping_address2',
          5 => 'shipping_city',
          6 => 'shipping_state',
          7 => 'shipping_zip',
          8 => 'shipping_country',
          9 => 'billing_first_name',
          10 => 'billing_last_name',
          11 => 'billing_address1',
          12 => 'billing_address2',
          13 => 'billing_city',
          14 => 'billing_state',
          15 => 'billing_zip',
          16 => 'billing_country',
          17 => 'email',
          18 => 'phone',
          19 => 'items_total',
          20 => 'taxes_total',
          21 => 'shipping_total',
          22 => 'rebate_total',
          23 => 'shipping_type',
          24 => 'status',
          25 => 'flags',
          26 => 'refund_total',
          27 => 'created_at',
          28 => 'updated_at',
        );

    public $id = NULL;
    public $user_id = NULL;
    public $promo_code_id = NULL;
    public $shipping_first_name = NULL;
    public $shipping_last_name = NULL;
    public $shipping_company = NULL;
    public $shipping_address1 = NULL;
    public $shipping_address2 = NULL;
    public $shipping_city = NULL;
    public $shipping_state = NULL;
    public $shipping_zip = NULL;
    public $shipping_country = NULL;
    public $billing_first_name = NULL;
    public $billing_last_name = NULL;
    public $billing_company = NULL;
    public $billing_address1 = NULL;
    public $billing_address2 = NULL;
    public $billing_city = NULL;
    public $billing_state = NULL;
    public $billing_zip = NULL;
    public $billing_country = NULL;
    public $email = NULL;
    public $phone = NULL;
    public $items_total = NULL;
    public $taxes_total = NULL;
    public $shipping_total = NULL;
    public $rebate_total = NULL;
    public $shipping_type = NULL;
    public $status = NULL;
    public $flags = NULL;
    public $refund_total = NULL;
    public $paid_at = NULL;
    public $authorization_reference = NULL;
    public $payment_reference = NULL;
    public $shopping_cart_id = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_id' => 
          array (
          ),
          'promo_code_id' => 
          array (
          ),
          'shipping_first_name' => 
          array (
          ),
          'shipping_last_name' => 
          array (
          ),
          'shipping_company' => 
          array (
          ),
          'shipping_address1' => 
          array (
          ),
          'shipping_address2' => 
          array (
          ),
          'shipping_city' => 
          array (
          ),
          'shipping_state' => 
          array (
          ),
          'shipping_zip' => 
          array (
          ),
          'shipping_country' => 
          array (
          ),
          'billing_first_name' => 
          array (
          ),
          'billing_last_name' => 
          array (
          ),
          'billing_company' => 
          array (
          ),
          'billing_address1' => 
          array (
          ),
          'billing_address2' => 
          array (
          ),
          'billing_city' => 
          array (
          ),
          'billing_state' => 
          array (
          ),
          'billing_zip' => 
          array (
          ),
          'billing_country' => 
          array (
          ),
          'email' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'items_total' => 
          array (
          ),
          'taxes_total' => 
          array (
          ),
          'shipping_total' => 
          array (
          ),
          'rebate_total' => 
          array (
          ),
          'shipping_type' => 
          array (
          ),
          'status' => 
          array (
          ),
          'flags' => 
          array (
          ),
          'refund_total' => 
          array (
          ),
          'paid_at' => 
          array (
          ),
          'authorization_reference' => 
          array (
          ),
          'payment_reference' => 
          array (
          ),
          'shopping_cart_id' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>