<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in TransactionItem
  */
namespace DBCore\Bizjcommerce;

use phpr\Database\Model;

class TransactionItem extends Model {

    const SCHEMA = 'bizjcommerce';
    const TABLE = 'transaction_item';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'transaction_id',
          2 => 'product_id',
          3 => 'price',
          4 => 'quantity',
          5 => 'parameters',
          6 => 'is_fulfilled',
          7 => 'updated_at',
        );

    public $id = NULL;
    public $transaction_id = NULL;
    public $product_id = NULL;
    public $price = NULL;
    public $quantity = NULL;
    public $parameters = NULL;
    public $is_fulfilled = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'transaction_id' => 
          array (
          ),
          'product_id' => 
          array (
          ),
          'price' => 
          array (
          ),
          'quantity' => 
          array (
          ),
          'parameters' => 
          array (
          ),
          'is_fulfilled' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>