<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Changesets
  */
namespace DBCore\DevRedmineBizj;

use phpr\Database\Model;

class Changesets extends Model {

    const SCHEMA = 'dev_redmine_bizj';
    const TABLE = 'changesets';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'repository_id',
          2 => 'revision',
          3 => 'committed_on',
        );

    public $id = NULL;
    public $repository_id = NULL;
    public $revision = NULL;
    public $committer = NULL;
    public $committed_on = NULL;
    public $comments = NULL;
    public $commit_date = NULL;
    public $scmid = NULL;
    public $user_id = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'repository_id' => 
          array (
          ),
          'revision' => 
          array (
          ),
          'committer' => 
          array (
          ),
          'committed_on' => 
          array (
          ),
          'comments' => 
          array (
          ),
          'commit_date' => 
          array (
          ),
          'scmid' => 
          array (
          ),
          'user_id' => 
          array (
          ),
        );




}

?>