<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Issues
  */
namespace DBCore\DevRedmineBizj;

use phpr\Database\Model;

class Issues extends Model {

    const SCHEMA = 'dev_redmine_bizj';
    const TABLE = 'issues';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'tracker_id',
          2 => 'project_id',
          3 => 'subject',
          4 => 'status_id',
          5 => 'priority_id',
          6 => 'author_id',
          7 => 'lock_version',
          8 => 'done_ratio',
          9 => 'is_private',
        );

    public $id = NULL;
    public $tracker_id = NULL;
    public $project_id = NULL;
    public $subject = NULL;
    public $description = NULL;
    public $due_date = NULL;
    public $category_id = NULL;
    public $status_id = NULL;
    public $assigned_to_id = NULL;
    public $priority_id = NULL;
    public $fixed_version_id = NULL;
    public $author_id = NULL;
    public $lock_version = NULL;
    public $created_on = NULL;
    public $updated_on = NULL;
    public $start_date = NULL;
    public $done_ratio = NULL;
    public $estimated_hours = NULL;
    public $parent_id = NULL;
    public $root_id = NULL;
    public $lft = NULL;
    public $rgt = NULL;
    public $is_private = NULL;
    public $closed_on = NULL;
    public $ir_position = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'tracker_id' => 
          array (
          ),
          'project_id' => 
          array (
          ),
          'subject' => 
          array (
          ),
          'description' => 
          array (
          ),
          'due_date' => 
          array (
          ),
          'category_id' => 
          array (
          ),
          'status_id' => 
          array (
          ),
          'assigned_to_id' => 
          array (
          ),
          'priority_id' => 
          array (
          ),
          'fixed_version_id' => 
          array (
          ),
          'author_id' => 
          array (
          ),
          'lock_version' => 
          array (
          ),
          'created_on' => 
          array (
          ),
          'updated_on' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'done_ratio' => 
          array (
          ),
          'estimated_hours' => 
          array (
          ),
          'parent_id' => 
          array (
          ),
          'root_id' => 
          array (
          ),
          'lft' => 
          array (
          ),
          'rgt' => 
          array (
          ),
          'is_private' => 
          array (
          ),
          'closed_on' => 
          array (
          ),
          'ir_position' => 
          array (
          ),
        );




}

?>