<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MemberRoles
  */
namespace DBCore\DevRedmineBizj;

use phpr\Database\Model;

class MemberRoles extends Model {

    const SCHEMA = 'dev_redmine_bizj';
    const TABLE = 'member_roles';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'member_id',
          2 => 'role_id',
        );

    public $id = NULL;
    public $member_id = NULL;
    public $role_id = NULL;
    public $inherited_from = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'member_id' => 
          array (
          ),
          'role_id' => 
          array (
          ),
          'inherited_from' => 
          array (
          ),
        );




}

?>