<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in News
  */
namespace DBCore\DevRedmineBizj;

use phpr\Database\Model;

class News extends Model {

    const SCHEMA = 'dev_redmine_bizj';
    const TABLE = 'news';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'title',
          2 => 'author_id',
          3 => 'comments_count',
        );

    public $id = NULL;
    public $project_id = NULL;
    public $title = NULL;
    public $summary = NULL;
    public $description = NULL;
    public $author_id = NULL;
    public $created_on = NULL;
    public $comments_count = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'project_id' => 
          array (
          ),
          'title' => 
          array (
          ),
          'summary' => 
          array (
          ),
          'description' => 
          array (
          ),
          'author_id' => 
          array (
          ),
          'created_on' => 
          array (
          ),
          'comments_count' => 
          array (
          ),
        );




}

?>