<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Wikis
  */
namespace DBCore\DevRedmineBizj;

use phpr\Database\Model;

class Wikis extends Model {

    const SCHEMA = 'dev_redmine_bizj';
    const TABLE = 'wikis';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'project_id',
          2 => 'start_page',
          3 => 'status',
        );

    public $id = NULL;
    public $project_id = NULL;
    public $start_page = NULL;
    public $status = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'project_id' => 
          array (
          ),
          'start_page' => 
          array (
          ),
          'status' => 
          array (
          ),
        );




}

?>