<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Contact
  */
namespace DBCore\Datahub;

use phpr\Database\Model;

class Contact extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'contact';
    const AUTO_INCREMENT_COLUMN = 'contact_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'contact_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'contact_id',
          1 => 'hub_id',
          2 => 'is_duplicate',
          3 => 'is_current_employee',
          4 => 'last_name',
          5 => 'created_at',
          6 => 'updated_at',
        );

    public $contact_id = NULL;
    public $hub_id = NULL;
    public $meroveus_id = NULL;
    public $relevate_id = NULL;
    public $is_duplicate = NULL;
    public $is_current_employee = NULL;
    public $first_name = NULL;
    public $middle_initial = NULL;
    public $last_name = NULL;
    public $suffix = NULL;
    public $honorific = NULL;
    public $job_title = NULL;
    public $job_position_id = NULL;
    public $email = NULL;
    public $phone = NULL;
    public $address1 = NULL;
    public $address2 = NULL;
    public $city = NULL;
    public $state = NULL;
    public $postal_code = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $deleted_at = NULL;
    public $DBColumnsArray = 
        array (
          'contact_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'hub_id' => 
          array (
          ),
          'meroveus_id' => 
          array (
          ),
          'relevate_id' => 
          array (
          ),
          'is_duplicate' => 
          array (
          ),
          'is_current_employee' => 
          array (
          ),
          'first_name' => 
          array (
          ),
          'middle_initial' => 
          array (
          ),
          'last_name' => 
          array (
          ),
          'suffix' => 
          array (
          ),
          'honorific' => 
          array (
          ),
          'job_title' => 
          array (
          ),
          'job_position_id' => 
          array (
          ),
          'email' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'postal_code' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'deleted_at' => 
          array (
          ),
        );




}

?>