<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MarketMsaPmsaMap
  */
namespace DBCore\Datahub;

use phpr\Database\Model;

class MarketMsaPmsaMap extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'market_msa_pmsa_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'market_id',
          1 => 'sa_code',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'market_id',
          1 => 'sa_code',
        );

    public $market_id = NULL;
    public $sa_code = NULL;
    public $DBColumnsArray = 
        array (
          'market_id' => 
          array (
            0 => 1,
          ),
          'sa_code' => 
          array (
            0 => 1,
          ),
        );




}

?>