<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PageMedia
  */
namespace DBCore\BizjPreview;

use phpr\Database\Model;

class PageMedia extends Model {

    const SCHEMA = 'bizj_preview';
    const TABLE = 'page_media';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'page_id',
          1 => 'ord',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'page_id',
          1 => 'ord',
          2 => 'media_host',
          3 => 'media_uri',
          4 => 'media_source',
          5 => 'media_type',
          6 => 'orig_height',
          7 => 'orig_width',
          8 => 'flag',
        );

    public $page_id = NULL;
    public $ord = NULL;
    public $media_host = NULL;
    public $media_uri = NULL;
    public $crop_data = NULL;
    public $media_source = NULL;
    public $external_id = NULL;
    public $media_type = NULL;
    public $title = NULL;
    public $caption = NULL;
    public $alt_text = NULL;
    public $link_url = NULL;
    public $art_credit = NULL;
    public $orig_height = NULL;
    public $orig_width = NULL;
    public $flag = NULL;
    public $additional_data = NULL;
    public $DBColumnsArray = 
        array (
          'page_id' => 
          array (
            0 => 1,
          ),
          'ord' => 
          array (
            0 => 1,
          ),
          'media_host' => 
          array (
          ),
          'media_uri' => 
          array (
          ),
          'crop_data' => 
          array (
          ),
          'media_source' => 
          array (
          ),
          'external_id' => 
          array (
          ),
          'media_type' => 
          array (
          ),
          'title' => 
          array (
          ),
          'caption' => 
          array (
          ),
          'alt_text' => 
          array (
          ),
          'link_url' => 
          array (
          ),
          'art_credit' => 
          array (
          ),
          'orig_height' => 
          array (
          ),
          'orig_width' => 
          array (
          ),
          'flag' => 
          array (
          ),
          'additional_data' => 
          array (
          ),
        );




}

?>