<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Poll
  */
namespace DBCore\BizjPreview;

use phpr\Database\Model;

class Poll extends Model {

    const SCHEMA = 'bizj_preview';
    const TABLE = 'poll';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'poll_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'poll_id',
          1 => 'start_time',
          2 => 'end_time',
          3 => 'active',
          4 => 'display_results',
          5 => 'has_comments',
          6 => 'has_sponsor',
          7 => 'featured',
        );

    public $poll_id = NULL;
    public $market = NULL;
    public $headline = NULL;
    public $teaser = NULL;
    public $start_time = NULL;
    public $end_time = NULL;
    public $active = NULL;
    public $display_results = NULL;
    public $recipients_final = NULL;
    public $recipients_daily = NULL;
    public $site_id = NULL;
    public $description = NULL;
    public $has_comments = NULL;
    public $has_sponsor = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $featured = NULL;
    public $site = NULL;
    public $path = NULL;
    public $meta_title = NULL;
    public $meta_description = NULL;
    public $meta_keywords = NULL;
    public $DBColumnsArray = 
        array (
          'poll_id' => 
          array (
            0 => 1,
          ),
          'market' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'teaser' => 
          array (
          ),
          'start_time' => 
          array (
          ),
          'end_time' => 
          array (
          ),
          'active' => 
          array (
          ),
          'display_results' => 
          array (
          ),
          'recipients_final' => 
          array (
          ),
          'recipients_daily' => 
          array (
          ),
          'site_id' => 
          array (
          ),
          'description' => 
          array (
          ),
          'has_comments' => 
          array (
          ),
          'has_sponsor' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'featured' => 
          array (
          ),
          'site' => 
          array (
          ),
          'path' => 
          array (
          ),
          'meta_title' => 
          array (
          ),
          'meta_description' => 
          array (
          ),
          'meta_keywords' => 
          array (
          ),
        );




}

?>