<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in StoryVerticalSubtopic
  */
namespace DBCore\BizjPreview;

use phpr\Database\Model;

class StoryVerticalSubtopic extends Model {

    const SCHEMA = 'bizj_preview';
    const TABLE = 'story_vertical_subtopic';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'story_id',
          1 => 'vertical_subtopic_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'story_id',
          1 => 'vertical_subtopic_id',
          2 => 'market',
          3 => 'story_date',
          4 => 'relevance',
          5 => 'is_daily',
        );

    public $story_id = NULL;
    public $vertical_subtopic_id = NULL;
    public $market = NULL;
    public $story_date = NULL;
    public $relevance = NULL;
    public $is_daily = NULL;
    public $DBColumnsArray = 
        array (
          'story_id' => 
          array (
            0 => 1,
          ),
          'vertical_subtopic_id' => 
          array (
            0 => 1,
          ),
          'market' => 
          array (
          ),
          'story_date' => 
          array (
          ),
          'relevance' => 
          array (
          ),
          'is_daily' => 
          array (
          ),
        );




}

?>