<?php

namespace DBCore\Datahub;

use Scoop\Database\Model;

/**
 * Class Address
 * @package DBCore\Datahub
 * @author jrobinson (robotically)
 * @date 2016/05/05
 * @property mixed $address_id
 * @property mixed $address1
 * @property mixed $address2
 * @property mixed $city
 * @property mixed $country
 * @property mixed $country_code
 * @property mixed $latitude
 * @property mixed $longitude
 * @property mixed $source_id
 * @property mixed $state
 * @property mixed $state_code
 * @property mixed $zip_code
 * @property mixed $created_at
 * @property mixed $updated_at
 * @property mixed $deleted_at
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Datahub\Address
 */
class Address extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'address';
    const AUTO_INCREMENT_COLUMN = 'address_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'address_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'address_id',
          1 => 'created_at',
          2 => 'updated_at',
        );
    public static $dBColumnPropertiesArray = 
        array (
          'address_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'country' => 
          array (
          ),
          'country_code' => 
          array (
          ),
          'latitude' => 
          array (
          ),
          'longitude' => 
          array (
          ),
          'source_id' => 
          array (
          ),
          'state' => 
          array (
          ),
          'state_code' => 
          array (
          ),
          'zip_code' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'deleted_at' => 
          array (
          ),
        );


    protected $dBValuesArray = 
        array (
          'address_id' => NULL,
          'address1' => NULL,
          'address2' => NULL,
          'city' => NULL,
          'country' => NULL,
          'country_code' => NULL,
          'latitude' => NULL,
          'longitude' => NULL,
          'source_id' => NULL,
          'state' => NULL,
          'state_code' => NULL,
          'zip_code' => NULL,
          'created_at' => NULL,
          'updated_at' => NULL,
          'deleted_at' => NULL,
        );



}

?>