<?php

namespace DBCore\Datahub;

use Scoop\Database\Model;

/**
 * Class Contact
 * @package DBCore\Datahub
 * @author jrobinson (robotically)
 * @date 2016/05/05
 * @property mixed $contact_id
 * @property mixed $relevate_id
 * @property mixed $is_duplicate
 * @property mixed $is_current_employee
 * @property mixed $first_name
 * @property mixed $middle_initial
 * @property mixed $last_name
 * @property mixed $suffix
 * @property mixed $honorific
 * @property mixed $job_title
 * @property mixed $job_position_id
 * @property mixed $email
 * @property mixed $phone
 * @property mixed $address1
 * @property mixed $address2
 * @property mixed $city
 * @property mixed $state
 * @property mixed $postal_code
 * @property mixed $created_at
 * @property mixed $updated_at
 * @property mixed $deleted_at
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Datahub\Contact
 */
class Contact extends Model {

    const SCHEMA = 'datahub';
    const TABLE = 'contact';
    const AUTO_INCREMENT_COLUMN = 'contact_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'contact_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'contact_id',
          1 => 'is_duplicate',
          2 => 'is_current_employee',
          3 => 'last_name',
          4 => 'created_at',
          5 => 'updated_at',
        );
    public static $dBColumnPropertiesArray = 
        array (
          'contact_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'relevate_id' => 
          array (
          ),
          'is_duplicate' => 
          array (
          ),
          'is_current_employee' => 
          array (
          ),
          'first_name' => 
          array (
          ),
          'middle_initial' => 
          array (
          ),
          'last_name' => 
          array (
          ),
          'suffix' => 
          array (
          ),
          'honorific' => 
          array (
          ),
          'job_title' => 
          array (
          ),
          'job_position_id' => 
          array (
          ),
          'email' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'postal_code' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'deleted_at' => 
          array (
          ),
        );


    protected $dBValuesArray = 
        array (
          'contact_id' => NULL,
          'relevate_id' => NULL,
          'is_duplicate' => NULL,
          'is_current_employee' => NULL,
          'first_name' => NULL,
          'middle_initial' => NULL,
          'last_name' => NULL,
          'suffix' => NULL,
          'honorific' => NULL,
          'job_title' => NULL,
          'job_position_id' => NULL,
          'email' => NULL,
          'phone' => NULL,
          'address1' => NULL,
          'address2' => NULL,
          'city' => NULL,
          'state' => NULL,
          'postal_code' => NULL,
          'created_at' => NULL,
          'updated_at' => NULL,
          'deleted_at' => NULL,
        );



}

?>