<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Classification
  */
namespace DBCore\Bolapi;

use phpr\Database\Model;

class Classification extends Model {

    const SCHEMA = 'bolapi';
    const TABLE = 'classification';
    const AUTO_INCREMENT_COLUMN = 'classification_uid';
    const PRIMARY_KEYS = 
        array (
          0 => 'classification_uid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'classification_uid',
          1 => 'classification',
          2 => 'super_class_uid',
        );

    public $classification_uid = NULL;
    public $classification = NULL;
    public $super_class_uid = NULL;
    public $DBColumnsArray = 
        array (
          'classification_uid' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'classification' => 
          array (
          ),
          'super_class_uid' => 
          array (
          ),
        );




}

?>