<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EbizDataColumns
  */
namespace DBCore\Bolapi;

use phpr\Database\Model;

class EbizDataColumns extends Model {

    const SCHEMA = 'bolapi';
    const TABLE = 'ebiz_data_columns';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'list_uid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'list_uid',
        );

    public $list_uid = NULL;
    public $employees = NULL;
    public $revenue = NULL;
    public $description = NULL;
    public $DBColumnsArray = 
        array (
          'list_uid' => 
          array (
            0 => 1,
          ),
          'employees' => 
          array (
          ),
          'revenue' => 
          array (
          ),
          'description' => 
          array (
          ),
        );




}

?>