<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Publication
  */
namespace DBCore\Bolapi;

use phpr\Database\Model;

class Publication extends Model {

    const SCHEMA = 'bolapi';
    const TABLE = 'publication';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'pub_uid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'pub_uid',
          1 => 'pub_id',
          2 => 'pub_name',
          3 => 'pub_state',
          4 => 'publication_title',
          5 => 'pub_city',
        );

    public $pub_uid = NULL;
    public $pub_id = NULL;
    public $pub_name = NULL;
    public $pub_state = NULL;
    public $publication_title = NULL;
    public $pub_city = NULL;
    public $start_date = NULL;
    public $end_date = NULL;
    public $true_year = NULL;
    public $is_external = NULL;
    public $DBColumnsArray = 
        array (
          'pub_uid' => 
          array (
            0 => 1,
          ),
          'pub_id' => 
          array (
          ),
          'pub_name' => 
          array (
          ),
          'pub_state' => 
          array (
          ),
          'publication_title' => 
          array (
          ),
          'pub_city' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'end_date' => 
          array (
          ),
          'true_year' => 
          array (
          ),
          'is_external' => 
          array (
          ),
        );




}

?>