<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in RecordPeople
  */
namespace DBCore\Bolapi;

use phpr\Database\Model;

class RecordPeople extends Model {

    const SCHEMA = 'bolapi';
    const TABLE = 'record_people';
    const AUTO_INCREMENT_COLUMN = 'record_people_uid';
    const PRIMARY_KEYS = 
        array (
          0 => 'record_people_uid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'record_people_uid',
          1 => 'record_uid',
          2 => 'key_survey',
        );

    public $record_people_uid = NULL;
    public $record_uid = NULL;
    public $pub_uid = NULL;
    public $fname = NULL;
    public $mname = NULL;
    public $lname = NULL;
    public $prefix = NULL;
    public $suffix = NULL;
    public $title = NULL;
    public $phone = NULL;
    public $phone_fax = NULL;
    public $phone_cell = NULL;
    public $phone_ext = NULL;
    public $is_contact = NULL;
    public $is_officer = NULL;
    public $email = NULL;
    public $photo = NULL;
    public $is_pvt_email = NULL;
    public $is_pvt_person = NULL;
    public $is_archive = NULL;
    public $key_survey = NULL;
    public $survey_flag = NULL;
    public $note = NULL;
    public $account_created = NULL;
    public $account_modified = NULL;
    public $date_created = NULL;
    public $date_modified = NULL;
    public $temp_id = NULL;
    public $DBColumnsArray = 
        array (
          'record_people_uid' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'record_uid' => 
          array (
          ),
          'pub_uid' => 
          array (
          ),
          'fname' => 
          array (
          ),
          'mname' => 
          array (
          ),
          'lname' => 
          array (
          ),
          'prefix' => 
          array (
          ),
          'suffix' => 
          array (
          ),
          'title' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'phone_fax' => 
          array (
          ),
          'phone_cell' => 
          array (
          ),
          'phone_ext' => 
          array (
          ),
          'is_contact' => 
          array (
          ),
          'is_officer' => 
          array (
          ),
          'email' => 
          array (
          ),
          'photo' => 
          array (
          ),
          'is_pvt_email' => 
          array (
          ),
          'is_pvt_person' => 
          array (
          ),
          'is_archive' => 
          array (
          ),
          'key_survey' => 
          array (
          ),
          'survey_flag' => 
          array (
          ),
          'note' => 
          array (
          ),
          'account_created' => 
          array (
          ),
          'account_modified' => 
          array (
          ),
          'date_created' => 
          array (
          ),
          'date_modified' => 
          array (
          ),
          'temp_id' => 
          array (
          ),
        );




}

?>