<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Regions
  */
namespace DBCore\Bolapi;

use phpr\Database\Model;

class Regions extends Model {

    const SCHEMA = 'bolapi';
    const TABLE = 'regions';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'region_uid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'region_uid',
        );

    public $region_uid = NULL;
    public $name = NULL;
    public $DBColumnsArray = 
        array (
          'region_uid' => 
          array (
            0 => 1,
          ),
          'name' => 
          array (
          ),
        );




}

?>