<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in RelevateDataHold
  */
namespace DBCore\Bolapi;

use phpr\Database\Model;

class RelevateDataHold extends Model {

    const SCHEMA = 'bolapi';
    const TABLE = 'relevate_data_hold';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'last_updated_usps',
        );

    public $id = NULL;
    public $import_uid = NULL;
    public $record_uid = NULL;
    public $pub_uid = NULL;
    public $year_id = NULL;
    public $sequence_number = NULL;
    public $reserved_2 = NULL;
    public $reserved_3 = NULL;
    public $reserved_4 = NULL;
    public $reserved_5 = NULL;
    public $client_company_name = NULL;
    public $client_address_1 = NULL;
    public $client_address_2 = NULL;
    public $client_city = NULL;
    public $client_state = NULL;
    public $client_zip = NULL;
    public $client_phone = NULL;
    public $company_name_matched = NULL;
    public $company_phone_number = NULL;
    public $abi_number = NULL;
    public $contact_first_name = NULL;
    public $contact_middle_initial = NULL;
    public $contact_last_name = NULL;
    public $contact_suffix = NULL;
    public $contact_title = NULL;
    public $contact_address = NULL;
    public $contact_city = NULL;
    public $contact_state = NULL;
    public $contact_full_postal_zip_code = NULL;
    public $is_active = NULL;
    public $is_duplicate = NULL;
    public $last_updated = NULL;
    public $date_created = NULL;
    public $client_address_1_usps = NULL;
    public $client_address_2_usps = NULL;
    public $client_address_3usps = NULL;
    public $client_city_usps = NULL;
    public $client_state_usps = NULL;
    public $client_zip_usps = NULL;
    public $client_zip4_usps = NULL;
    public $client_latitude = NULL;
    public $client_longitude = NULL;
    public $contact_address_1_usps = NULL;
    public $contact_address_2_usps = NULL;
    public $contact_address_3_usps = NULL;
    public $contact_city_usps = NULL;
    public $contact_state_usps = NULL;
    public $contact_zip_usps = NULL;
    public $contact_zip4_usps = NULL;
    public $contact_latitude = NULL;
    public $contact_longitude = NULL;
    public $last_updated_usps = NULL;
    public $contact_yahoo_quality_id = NULL;
    public $client_yahoo_quality_id = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'import_uid' => 
          array (
          ),
          'record_uid' => 
          array (
          ),
          'pub_uid' => 
          array (
          ),
          'year_id' => 
          array (
          ),
          'sequence_number' => 
          array (
          ),
          'reserved_2' => 
          array (
          ),
          'reserved_3' => 
          array (
          ),
          'reserved_4' => 
          array (
          ),
          'reserved_5' => 
          array (
          ),
          'client_company_name' => 
          array (
          ),
          'client_address_1' => 
          array (
          ),
          'client_address_2' => 
          array (
          ),
          'client_city' => 
          array (
          ),
          'client_state' => 
          array (
          ),
          'client_zip' => 
          array (
          ),
          'client_phone' => 
          array (
          ),
          'company_name_matched' => 
          array (
          ),
          'company_phone_number' => 
          array (
          ),
          'abi_number' => 
          array (
          ),
          'contact_first_name' => 
          array (
          ),
          'contact_middle_initial' => 
          array (
          ),
          'contact_last_name' => 
          array (
          ),
          'contact_suffix' => 
          array (
          ),
          'contact_title' => 
          array (
          ),
          'contact_address' => 
          array (
          ),
          'contact_city' => 
          array (
          ),
          'contact_state' => 
          array (
          ),
          'contact_full_postal_zip_code' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'is_duplicate' => 
          array (
          ),
          'last_updated' => 
          array (
          ),
          'date_created' => 
          array (
          ),
          'client_address_1_usps' => 
          array (
          ),
          'client_address_2_usps' => 
          array (
          ),
          'client_address_3usps' => 
          array (
          ),
          'client_city_usps' => 
          array (
          ),
          'client_state_usps' => 
          array (
          ),
          'client_zip_usps' => 
          array (
          ),
          'client_zip4_usps' => 
          array (
          ),
          'client_latitude' => 
          array (
          ),
          'client_longitude' => 
          array (
          ),
          'contact_address_1_usps' => 
          array (
          ),
          'contact_address_2_usps' => 
          array (
          ),
          'contact_address_3_usps' => 
          array (
          ),
          'contact_city_usps' => 
          array (
          ),
          'contact_state_usps' => 
          array (
          ),
          'contact_zip_usps' => 
          array (
          ),
          'contact_zip4_usps' => 
          array (
          ),
          'contact_latitude' => 
          array (
          ),
          'contact_longitude' => 
          array (
          ),
          'last_updated_usps' => 
          array (
          ),
          'contact_yahoo_quality_id' => 
          array (
          ),
          'client_yahoo_quality_id' => 
          array (
          ),
        );




}

?>