<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AdminUserRole
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AdminUserRole extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'admin_user_role';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
          1 => 'role_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'role_id',
        );

    public $user_id = NULL;
    public $role_id = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
          ),
          'role_id' => 
          array (
            0 => 1,
          ),
        );




}

?>