<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AdminUser
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AdminUser extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'admin_user';
    const AUTO_INCREMENT_COLUMN = 'user_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'user_name',
          2 => 'authenticate_from_ldap',
          3 => 'm_time',
        );

    public $user_id = NULL;
    public $user_name = NULL;
    public $first_name = NULL;
    public $last_name = NULL;
    public $email = NULL;
    public $phone = NULL;
    public $password = NULL;
    public $old_crypt_password = NULL;
    public $authenticate_from_ldap = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_name' => 
          array (
          ),
          'first_name' => 
          array (
          ),
          'last_name' => 
          array (
          ),
          'email' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'password' => 
          array (
          ),
          'old_crypt_password' => 
          array (
          ),
          'authenticate_from_ldap' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
        );




}

?>