<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AdminRole
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AdminRole extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'admin_role';
    const AUTO_INCREMENT_COLUMN = 'role_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'role_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'role_id',
          1 => 'role',
        );

    public $role_id = NULL;
    public $role = NULL;
    public $description = NULL;
    public $DBColumnsArray = 
        array (
          'role_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'role' => 
          array (
          ),
          'description' => 
          array (
          ),
        );




}

?>