<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AdOrder
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AdOrder extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'ad_order';
    const AUTO_INCREMENT_COLUMN = 'order_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'order_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'order_id',
          1 => 'm_time',
        );

    public $order_id = NULL;
    public $campaign_market = NULL;
    public $is_complete = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $description = NULL;
    public $client_id = NULL;
    public $is_approved = NULL;
    public $user = NULL;
    public $billing_contact_id = NULL;
    public $media_contact_id = NULL;
    public $attached_filename = NULL;
    public $doubleclick_order_number = NULL;
    public $notes = NULL;
    public $DBColumnsArray = 
        array (
          'order_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'campaign_market' => 
          array (
          ),
          'is_complete' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'description' => 
          array (
          ),
          'client_id' => 
          array (
          ),
          'is_approved' => 
          array (
          ),
          'user' => 
          array (
          ),
          'billing_contact_id' => 
          array (
          ),
          'media_contact_id' => 
          array (
          ),
          'attached_filename' => 
          array (
          ),
          'doubleclick_order_number' => 
          array (
          ),
          'notes' => 
          array (
          ),
        );




}

?>