<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AkamaiVersion
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AkamaiVersion extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'akamai_version';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
        );

    public $version = NULL;
    public $DBColumnsArray = 
        array (
          'version' => 
          array (
          ),
        );




}

?>