<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AkamaiRefreshRequest
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AkamaiRefreshRequest extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'akamai_refresh_request';
    const AUTO_INCREMENT_COLUMN = 'request_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'request_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'request_id',
        );

    public $request_id = NULL;
    public $user_name = NULL;
    public $request_time = NULL;
    public $is_complete = NULL;
    public $request = NULL;
    public $DBColumnsArray = 
        array (
          'request_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_name' => 
          array (
          ),
          'request_time' => 
          array (
          ),
          'is_complete' => 
          array (
          ),
          'request' => 
          array (
          ),
        );




}

?>