<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ApnsSubscriptionDeviceMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class ApnsSubscriptionDeviceMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'apns_subscription_device_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'subscription_id',
          1 => 'device_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'subscription_id',
          1 => 'device_id',
          2 => 'created_at',
        );

    public $subscription_id = NULL;
    public $device_id = NULL;
    public $settings = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'subscription_id' => 
          array (
            0 => 1,
          ),
          'device_id' => 
          array (
            0 => 1,
          ),
          'settings' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>