<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ApnsNotification
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class ApnsNotification extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'apns_notification';
    const AUTO_INCREMENT_COLUMN = 'notification_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'notification_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'notification_id',
          1 => 'subscription_id',
          2 => 'send_at',
          3 => 'payload',
          4 => 'last_completed_device_id',
          5 => 'is_sent',
          6 => 'created_at',
          7 => 'updated_at',
        );

    public $notification_id = NULL;
    public $subscription_id = NULL;
    public $send_at = NULL;
    public $payload = NULL;
    public $last_completed_device_id = NULL;
    public $is_sent = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'notification_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'subscription_id' => 
          array (
          ),
          'send_at' => 
          array (
          ),
          'payload' => 
          array (
          ),
          'last_completed_device_id' => 
          array (
          ),
          'is_sent' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>