<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ApnsSubscription
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class ApnsSubscription extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'apns_subscription';
    const AUTO_INCREMENT_COLUMN = 'subscription_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'subscription_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'subscription_id',
          1 => 'subscription_token',
          2 => 'description',
          3 => 'market_id',
          4 => 'created_at',
          5 => 'updated_at',
        );

    public $subscription_id = NULL;
    public $subscription_token = NULL;
    public $description = NULL;
    public $market_id = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'subscription_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'subscription_token' => 
          array (
          ),
          'description' => 
          array (
          ),
          'market_id' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>