<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AudienceClosedLoop
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AudienceClosedLoop extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'audience_closed_loop';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'user_id',
          2 => 'is_confirmed',
          3 => 'is_optin',
          4 => 'is_emailsent',
          5 => 'is_remindersent',
          6 => 'created_at',
          7 => 'updated_at',
        );

    public $id = NULL;
    public $user_id = NULL;
    public $email = NULL;
    public $sub_id = NULL;
    public $is_confirmed = NULL;
    public $zip_code = NULL;
    public $is_optin = NULL;
    public $is_emailsent = NULL;
    public $is_remindersent = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_id' => 
          array (
          ),
          'email' => 
          array (
          ),
          'sub_id' => 
          array (
          ),
          'is_confirmed' => 
          array (
          ),
          'zip_code' => 
          array (
          ),
          'is_optin' => 
          array (
          ),
          'is_emailsent' => 
          array (
          ),
          'is_remindersent' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>