<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in AustinSpace
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class AustinSpace extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'austin_space';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'c_time',
        );

    public $property_name = NULL;
    public $property_address = NULL;
    public $leasing_company = NULL;
    public $leasing_agent = NULL;
    public $agent_phone = NULL;
    public $agent_fax = NULL;
    public $property_sqft = NULL;
    public $sqft_avail = NULL;
    public $largest_sqft = NULL;
    public $small_sqft = NULL;
    public $rent_annual = NULL;
    public $floors = NULL;
    public $buildings = NULL;
    public $year_build = NULL;
    public $year_remodeled = NULL;
    public $zipcode_key = NULL;
    public $record_date = NULL;
    public $type = NULL;
    public $id = NULL;
    public $area = NULL;
    public $c_time = NULL;
    public $small_rent_annual = NULL;
    public $large_rent_annual = NULL;
    public $DBColumnsArray = 
        array (
          'property_name' => 
          array (
          ),
          'property_address' => 
          array (
          ),
          'leasing_company' => 
          array (
          ),
          'leasing_agent' => 
          array (
          ),
          'agent_phone' => 
          array (
          ),
          'agent_fax' => 
          array (
          ),
          'property_sqft' => 
          array (
          ),
          'sqft_avail' => 
          array (
          ),
          'largest_sqft' => 
          array (
          ),
          'small_sqft' => 
          array (
          ),
          'rent_annual' => 
          array (
          ),
          'floors' => 
          array (
          ),
          'buildings' => 
          array (
          ),
          'year_build' => 
          array (
          ),
          'year_remodeled' => 
          array (
          ),
          'zipcode_key' => 
          array (
          ),
          'record_date' => 
          array (
          ),
          'type' => 
          array (
          ),
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'area' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'small_rent_annual' => 
          array (
          ),
          'large_rent_annual' => 
          array (
          ),
        );




}

?>