<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BedrockProfilesCompany
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BedrockProfilesCompany extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'bedrock_profiles_company';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'slug',
          2 => 'name',
          3 => 'city',
          4 => 'state',
          5 => 'zip',
          6 => 'record_source',
          7 => 'acbj_org_id',
          8 => 'show_headlines_only',
        );

    public $id = NULL;
    public $slug = NULL;
    public $name = NULL;
    public $description = NULL;
    public $ticker = NULL;
    public $founded = NULL;
    public $industry = NULL;
    public $size = NULL;
    public $address1 = NULL;
    public $address2 = NULL;
    public $address3 = NULL;
    public $city = NULL;
    public $state = NULL;
    public $zip = NULL;
    public $organization_url = NULL;
    public $phone = NULL;
    public $sic = NULL;
    public $naics = NULL;
    public $record_source = NULL;
    public $last_story_date = NULL;
    public $acbj_org_id = NULL;
    public $show_headlines_only = NULL;
    public $dnbc_org_id = NULL;
    public $vendor4_org_id = NULL;
    public $linkedin_org_id = NULL;
    public $linkedin_url = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
          ),
          'slug' => 
          array (
          ),
          'name' => 
          array (
          ),
          'description' => 
          array (
          ),
          'ticker' => 
          array (
          ),
          'founded' => 
          array (
          ),
          'industry' => 
          array (
          ),
          'size' => 
          array (
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'address3' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'zip' => 
          array (
          ),
          'organization_url' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'sic' => 
          array (
          ),
          'naics' => 
          array (
          ),
          'record_source' => 
          array (
          ),
          'last_story_date' => 
          array (
          ),
          'acbj_org_id' => 
          array (
          ),
          'show_headlines_only' => 
          array (
          ),
          'dnbc_org_id' => 
          array (
          ),
          'vendor4_org_id' => 
          array (
          ),
          'linkedin_org_id' => 
          array (
          ),
          'linkedin_url' => 
          array (
          ),
        );




}

?>