<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BedrockProfilesCompanydupemap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BedrockProfilesCompanydupemap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'bedrock_profiles_companydupemap';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'dupe_acbj_org_id',
          2 => 'canon_acbj_org_id',
          3 => 'canon_slug',
        );

    public $id = NULL;
    public $dupe_acbj_org_id = NULL;
    public $canon_acbj_org_id = NULL;
    public $canon_slug = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
          ),
          'dupe_acbj_org_id' => 
          array (
          ),
          'canon_acbj_org_id' => 
          array (
          ),
          'canon_slug' => 
          array (
          ),
        );




}

?>