<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BiUAccount
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BiUAccount extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'bi_u_account';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'current_email',
          2 => 'tracked_at',
          3 => 'last_tracking_id',
        );

    public $user_id = NULL;
    public $current_email = NULL;
    public $current_name = NULL;
    public $tracked_at = NULL;
    public $last_tracking_id = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
          ),
          'current_email' => 
          array (
          ),
          'current_name' => 
          array (
          ),
          'tracked_at' => 
          array (
          ),
          'last_tracking_id' => 
          array (
          ),
        );




}

?>