<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BizbuysellFeatured
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BizbuysellFeatured extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'bizbuysell_featured';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'market',
          1 => 'listingid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'market',
          1 => 'listingid',
        );

    public $market = NULL;
    public $listingid = NULL;
    public $datecreated = NULL;
    public $dateexpires = NULL;
    public $primary_classification = NULL;
    public $primary_classification_description = NULL;
    public $headline = NULL;
    public $summary = NULL;
    public $description = NULL;
    public $asking_price = NULL;
    public $contact_name = NULL;
    public $phone = NULL;
    public $email = NULL;
    public $city = NULL;
    public $county = NULL;
    public $state = NULL;
    public $bbs_details_url = NULL;
    public $bbs_adresponse_url = NULL;
    public $bbs_photo_url = NULL;
    public $listing_type = NULL;
    public $DBColumnsArray = 
        array (
          'market' => 
          array (
            0 => 1,
          ),
          'listingid' => 
          array (
            0 => 1,
          ),
          'datecreated' => 
          array (
          ),
          'dateexpires' => 
          array (
          ),
          'primary_classification' => 
          array (
          ),
          'primary_classification_description' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'summary' => 
          array (
          ),
          'description' => 
          array (
          ),
          'asking_price' => 
          array (
          ),
          'contact_name' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'email' => 
          array (
          ),
          'city' => 
          array (
          ),
          'county' => 
          array (
          ),
          'state' => 
          array (
          ),
          'bbs_details_url' => 
          array (
          ),
          'bbs_adresponse_url' => 
          array (
          ),
          'bbs_photo_url' => 
          array (
          ),
          'listing_type' => 
          array (
          ),
        );




}

?>