<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BizspacePropertyMarketMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BizspacePropertyMarketMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'bizspace_property_market_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'property_id',
          1 => 'market_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'property_id',
          1 => 'market_id',
          2 => 'start_date',
          3 => 'end_date',
          4 => 'last_modified_by',
          5 => 'created_at',
          6 => 'updated_at',
        );

    public $property_id = NULL;
    public $market_id = NULL;
    public $start_date = NULL;
    public $end_date = NULL;
    public $last_modified_by = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'property_id' => 
          array (
            0 => 1,
          ),
          'market_id' => 
          array (
            0 => 1,
          ),
          'start_date' => 
          array (
          ),
          'end_date' => 
          array (
          ),
          'last_modified_by' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>