<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BookbuilderPub
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BookbuilderPub extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'bookbuilder_pub';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'pub_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'pub_id',
          1 => 'display_name',
          2 => 'is_active',
        );

    public $pub_id = NULL;
    public $market_id = NULL;
    public $display_name = NULL;
    public $is_active = NULL;
    public $DBColumnsArray = 
        array (
          'pub_id' => 
          array (
            0 => 1,
          ),
          'market_id' => 
          array (
          ),
          'display_name' => 
          array (
          ),
          'is_active' => 
          array (
          ),
        );




}

?>