<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BookbuilderDownload
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BookbuilderDownload extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'bookbuilder_download';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'bookbuilder_id',
          2 => 'ip_address',
          3 => 'date_downloaded',
        );

    public $id = NULL;
    public $bookbuilder_id = NULL;
    public $ip_address = NULL;
    public $user_agent = NULL;
    public $date_downloaded = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'bookbuilder_id' => 
          array (
          ),
          'ip_address' => 
          array (
          ),
          'user_agent' => 
          array (
          ),
          'date_downloaded' => 
          array (
          ),
        );




}

?>