<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in BurstNotification
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class BurstNotification extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'burst_notification';
    const AUTO_INCREMENT_COLUMN = 'notification_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'notification_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'notification_id',
          1 => 'video_id',
          2 => 'created_at',
        );

    public $notification_id = NULL;
    public $video_id = NULL;
    public $xmldoc = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'notification_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'video_id' => 
          array (
          ),
          'xmldoc' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>