<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CalendarListingBillboardTransactionMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CalendarListingBillboardTransactionMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'calendar_listing_billboard_transaction_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'billboard_id',
          1 => 'transaction_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'billboard_id',
          1 => 'transaction_id',
        );

    public $billboard_id = NULL;
    public $transaction_id = NULL;
    public $DBColumnsArray = 
        array (
          'billboard_id' => 
          array (
            0 => 1,
          ),
          'transaction_id' => 
          array (
            0 => 1,
          ),
        );




}

?>