<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CircDirectmailResponse
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CircDirectmailResponse extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'circ_directmail_response';
    const AUTO_INCREMENT_COLUMN = 'response_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'response_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'response_id',
          1 => 'm_time',
        );

    public $response_id = NULL;
    public $market = NULL;
    public $data = NULL;
    public $m_time = NULL;
    public $reported = NULL;
    public $c_date = NULL;
    public $DBColumnsArray = 
        array (
          'response_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'data' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'reported' => 
          array (
          ),
          'c_date' => 
          array (
          ),
        );




}

?>