<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CoProduct
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CoProduct extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'co_product';
    const AUTO_INCREMENT_COLUMN = 'product_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'product_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'product_id',
        );

    public $product_id = NULL;
    public $bizj_product_uid = NULL;
    public $coffer_id = NULL;
    public $display_order = NULL;
    public $c_time = NULL;
    public $price = NULL;
    public $promo_code = NULL;
    public $DBColumnsArray = 
        array (
          'product_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'bizj_product_uid' => 
          array (
          ),
          'coffer_id' => 
          array (
          ),
          'display_order' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'price' => 
          array (
          ),
          'promo_code' => 
          array (
          ),
        );




}

?>