<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CreDirectoryCategory
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CreDirectoryCategory extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'cre_directory_category';
    const AUTO_INCREMENT_COLUMN = 'category_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'category_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'category_id',
          1 => 'm_time',
        );

    public $category_id = NULL;
    public $description = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'category_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'description' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
        );




}

?>