<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CreDemographicsField
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CreDemographicsField extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'cre_demographics_field';
    const AUTO_INCREMENT_COLUMN = 'field_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'field_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'field_id',
          1 => 'm_time',
        );

    public $field_id = NULL;
    public $shortname = NULL;
    public $description = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'field_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'shortname' => 
          array (
          ),
          'description' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
        );




}

?>