<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CreListingType
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CreListingType extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'cre_listing_type';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'm_time',
        );

    public $listing_id = NULL;
    public $use_type_id = NULL;
    public $m_time = NULL;
    public $acbj_market = NULL;
    public $DBColumnsArray = 
        array (
          'listing_id' => 
          array (
          ),
          'use_type_id' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'acbj_market' => 
          array (
          ),
        );




}

?>