<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CrePhoto
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CrePhoto extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'cre_photo';
    const AUTO_INCREMENT_COLUMN = 'photo_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'photo_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'photo_id',
          1 => 'm_time',
        );

    public $photo_id = NULL;
    public $photo_url = NULL;
    public $listing_id = NULL;
    public $m_time = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'photo_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'photo_url' => 
          array (
          ),
          'listing_id' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>