<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CreSuite
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CreSuite extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'cre_suite';
    const AUTO_INCREMENT_COLUMN = 'suite_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'suite_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'suite_id',
          1 => 'm_time',
        );

    public $suite_id = NULL;
    public $floor = NULL;
    public $suitesize = NULL;
    public $availablesqft = NULL;
    public $maximumcontiguoussqft = NULL;
    public $minimumdivisiblesqft = NULL;
    public $leasetype = NULL;
    public $is_negotiable = NULL;
    public $dateavailable = NULL;
    public $vacant = NULL;
    public $status = NULL;
    public $modified_date = NULL;
    public $m_time = NULL;
    public $listing_id = NULL;
    public $c_time = NULL;
    public $leaserateloadfactor = NULL;
    public $pricepersqft = NULL;
    public $ceilingheight = NULL;
    public $dockdoors = NULL;
    public $suite_id_orig = NULL;
    public $annualleaserate = NULL;
    public $floors = NULL;
    public $leaseratetype = NULL;
    public $class = NULL;
    public $enhanced_expiration = NULL;
    public $lease_rate_low = NULL;
    public $lease_rate_high = NULL;
    public $acbj_market = NULL;
    public $is_enhanced = NULL;
    public $is_featured = NULL;
    public $active = NULL;
    public $ciepropertyurl = NULL;
    public $has_image = NULL;
    public $import_date = NULL;
    public $provider = NULL;
    public $DBColumnsArray = 
        array (
          'suite_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'floor' => 
          array (
          ),
          'suitesize' => 
          array (
          ),
          'availablesqft' => 
          array (
          ),
          'maximumcontiguoussqft' => 
          array (
          ),
          'minimumdivisiblesqft' => 
          array (
          ),
          'leasetype' => 
          array (
          ),
          'is_negotiable' => 
          array (
          ),
          'dateavailable' => 
          array (
          ),
          'vacant' => 
          array (
          ),
          'status' => 
          array (
          ),
          'modified_date' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'listing_id' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'leaserateloadfactor' => 
          array (
          ),
          'pricepersqft' => 
          array (
          ),
          'ceilingheight' => 
          array (
          ),
          'dockdoors' => 
          array (
          ),
          'suite_id_orig' => 
          array (
          ),
          'annualleaserate' => 
          array (
          ),
          'floors' => 
          array (
          ),
          'leaseratetype' => 
          array (
          ),
          'class' => 
          array (
          ),
          'enhanced_expiration' => 
          array (
          ),
          'lease_rate_low' => 
          array (
          ),
          'lease_rate_high' => 
          array (
          ),
          'acbj_market' => 
          array (
          ),
          'is_enhanced' => 
          array (
          ),
          'is_featured' => 
          array (
          ),
          'active' => 
          array (
          ),
          'ciepropertyurl' => 
          array (
          ),
          'has_image' => 
          array (
          ),
          'import_date' => 
          array (
          ),
          'provider' => 
          array (
          ),
        );




}

?>