<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CtCampaign
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CtCampaign extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'ct_campaign';
    const AUTO_INCREMENT_COLUMN = 'campaign_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'campaign_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'campaign_id',
        );

    public $campaign_id = NULL;
    public $source_site_id = NULL;
    public $dest_site_id = NULL;
    public $name = NULL;
    public $description = NULL;
    public $c_time = NULL;
    public $campaign_group_id = NULL;
    public $creative_id = NULL;
    public $DBColumnsArray = 
        array (
          'campaign_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'source_site_id' => 
          array (
          ),
          'dest_site_id' => 
          array (
          ),
          'name' => 
          array (
          ),
          'description' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'campaign_group_id' => 
          array (
          ),
          'creative_id' => 
          array (
          ),
        );




}

?>