<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CtClickTrack
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CtClickTrack extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'ct_click_track';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'c_time',
        );

    public $id = NULL;
    public $event_type = NULL;
    public $campaign_id = NULL;
    public $click_id = NULL;
    public $c_time = NULL;
    public $remote_ip = NULL;
    public $uin = NULL;
    public $user_agent = NULL;
    public $dest_url = NULL;
    public $referer = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'event_type' => 
          array (
          ),
          'campaign_id' => 
          array (
          ),
          'click_id' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'remote_ip' => 
          array (
          ),
          'uin' => 
          array (
          ),
          'user_agent' => 
          array (
          ),
          'dest_url' => 
          array (
          ),
          'referer' => 
          array (
          ),
        );




}

?>