<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CtClickSummary
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CtClickSummary extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'ct_click_summary';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $click_id = NULL;
    public $click_date = NULL;
    public $unique_hosts = NULL;
    public $description = NULL;
    public $url = NULL;
    public $click_count = NULL;
    public $campaign_id = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'click_id' => 
          array (
          ),
          'click_date' => 
          array (
          ),
          'unique_hosts' => 
          array (
          ),
          'description' => 
          array (
          ),
          'url' => 
          array (
          ),
          'click_count' => 
          array (
          ),
          'campaign_id' => 
          array (
          ),
        );




}

?>