<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in CwatchStats
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class CwatchStats extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'cwatch_stats';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'date',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'date',
        );

    public $date = NULL;
    public $sent = NULL;
    public $subscribers = NULL;
    public $one = NULL;
    public $two = NULL;
    public $three = NULL;
    public $four = NULL;
    public $five = NULL;
    public $six = NULL;
    public $seven = NULL;
    public $eight = NULL;
    public $nine = NULL;
    public $ten = NULL;
    public $DBColumnsArray = 
        array (
          'date' => 
          array (
            0 => 1,
          ),
          'sent' => 
          array (
          ),
          'subscribers' => 
          array (
          ),
          'one' => 
          array (
          ),
          'two' => 
          array (
          ),
          'three' => 
          array (
          ),
          'four' => 
          array (
          ),
          'five' => 
          array (
          ),
          'six' => 
          array (
          ),
          'seven' => 
          array (
          ),
          'eight' => 
          array (
          ),
          'nine' => 
          array (
          ),
          'ten' => 
          array (
          ),
        );




}

?>