<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DailyUpdateMail
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class DailyUpdateMail extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'daily_update_mail';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
        );

    public $market = NULL;
    public $active = NULL;
    public $ad_src = NULL;
    public $ad_href = NULL;
    public $ad_text = NULL;
    public $publisher = NULL;
    public $publisher_email = NULL;
    public $DBColumnsArray = 
        array (
          'market' => 
          array (
          ),
          'active' => 
          array (
          ),
          'ad_src' => 
          array (
          ),
          'ad_href' => 
          array (
          ),
          'ad_text' => 
          array (
          ),
          'publisher' => 
          array (
          ),
          'publisher_email' => 
          array (
          ),
        );




}

?>