<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DailyUpdateSend
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class DailyUpdateSend extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'daily_update_send';
    const AUTO_INCREMENT_COLUMN = 'daily_update_send_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'daily_update_send_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'daily_update_send_id',
        );

    public $daily_update_send_id = NULL;
    public $send_date = NULL;
    public $send_complete_time = NULL;
    public $total_sent = NULL;
    public $html_sent = NULL;
    public $text_sent = NULL;
    public $aol_sent = NULL;
    public $market = NULL;
    public $DBColumnsArray = 
        array (
          'daily_update_send_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'send_date' => 
          array (
          ),
          'send_complete_time' => 
          array (
          ),
          'total_sent' => 
          array (
          ),
          'html_sent' => 
          array (
          ),
          'text_sent' => 
          array (
          ),
          'aol_sent' => 
          array (
          ),
          'market' => 
          array (
          ),
        );




}

?>