<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DailyUpdateStorySent
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class DailyUpdateStorySent extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'daily_update_story_sent';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
        );

    public $story_id = NULL;
    public $sent_time = NULL;
    public $DBColumnsArray = 
        array (
          'story_id' => 
          array (
          ),
          'sent_time' => 
          array (
          ),
        );




}

?>