<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DailyUpdateSendLog
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class DailyUpdateSendLog extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'daily_update_send_log';
    const AUTO_INCREMENT_COLUMN = 'entry_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'entry_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'entry_id',
        );

    public $entry_id = NULL;
    public $market = NULL;
    public $c_time = NULL;
    public $status = NULL;
    public $DBColumnsArray = 
        array (
          'entry_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'status' => 
          array (
          ),
        );




}

?>