<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DeployedTemplate
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class DeployedTemplate extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'deployed_template';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'template_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'template_id',
          1 => 'template_name',
          2 => 'deployed_version',
          3 => 'exclude_section_css',
          4 => 'created_at',
          5 => 'updated_at',
        );

    public $template_id = NULL;
    public $template_name = NULL;
    public $deployed_version = NULL;
    public $template_css = NULL;
    public $template_js = NULL;
    public $exclude_section_css = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'template_id' => 
          array (
            0 => 1,
          ),
          'template_name' => 
          array (
          ),
          'deployed_version' => 
          array (
          ),
          'template_css' => 
          array (
          ),
          'template_js' => 
          array (
          ),
          'exclude_section_css' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>