<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DuEmailReportStats
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class DuEmailReportStats extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'du_email_report_stats';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $week_of = NULL;
    public $market = NULL;
    public $count_this_week = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'week_of' => 
          array (
          ),
          'market' => 
          array (
          ),
          'count_this_week' => 
          array (
          ),
        );




}

?>