<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EditionTicketSubscription
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class EditionTicketSubscription extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'edition_ticket_subscription';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $name = NULL;
    public $email = NULL;
    public $term = NULL;
    public $served = NULL;
    public $c_time = NULL;
    public $market = NULL;
    public $ticket_type = NULL;
    public $active = NULL;
    public $first_issue = NULL;
    public $next_issue = NULL;
    public $admin_user_name = NULL;
    public $redeemed = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'name' => 
          array (
          ),
          'email' => 
          array (
          ),
          'term' => 
          array (
          ),
          'served' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'market' => 
          array (
          ),
          'ticket_type' => 
          array (
          ),
          'active' => 
          array (
          ),
          'first_issue' => 
          array (
          ),
          'next_issue' => 
          array (
          ),
          'admin_user_name' => 
          array (
          ),
          'redeemed' => 
          array (
          ),
        );




}

?>