<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EditionTicketRecipient
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class EditionTicketRecipient extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'edition_ticket_recipient';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $market = NULL;
    public $email = NULL;
    public $is_sent = NULL;
    public $sent_time = NULL;
    public $c_time = NULL;
    public $edition_ticket_id = NULL;
    public $issue_date = NULL;
    public $ticket_type = NULL;
    public $subscription_id = NULL;
    public $remaining_issues = NULL;
    public $parameters = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'email' => 
          array (
          ),
          'is_sent' => 
          array (
          ),
          'sent_time' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'edition_ticket_id' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'ticket_type' => 
          array (
          ),
          'subscription_id' => 
          array (
          ),
          'remaining_issues' => 
          array (
          ),
          'parameters' => 
          array (
          ),
        );




}

?>