<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EvCategory
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class EvCategory extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'ev_category';
    const AUTO_INCREMENT_COLUMN = 'category_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'category_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'category_id',
          1 => 'category_name',
          2 => 'is_active',
          3 => 'is_topcategory',
        );

    public $category_id = NULL;
    public $category_name = NULL;
    public $is_active = NULL;
    public $is_topcategory = NULL;
    public $DBColumnsArray = 
        array (
          'category_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'category_name' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'is_topcategory' => 
          array (
          ),
        );




}

?>