<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EvEvent
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class EvEvent extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'ev_event';
    const AUTO_INCREMENT_COLUMN = 'event_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'event_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'event_id',
          1 => 'c_time',
          2 => 'admin_reg_notification',
          3 => 'm_time',
          4 => 'is_active',
          5 => 'is_registration_open',
          6 => 'is_soldout',
          7 => 'is_suspended',
          8 => 'is_cancelled',
          9 => 'is_invite_only',
          10 => 'close_registration',
          11 => 'has_admin_threshold_alert',
          12 => 'show_on_bizj_calendar',
          13 => 'has_nominations',
          14 => 'venue_can_support_autos',
          15 => 'has_sponsor_signage',
          16 => 'is_approx_date',
          17 => 'is_approx_time',
          18 => 'contact_only',
          19 => 'prefer_microsite',
          20 => 'has_sponsors',
          21 => 'has_single_sponsor_tier',
          22 => 'has_supplement',
          23 => 'is_supplement_handed_out',
          24 => 'market_owned',
          25 => 'is_custom_event',
          26 => 'event_type',
          27 => 'is_brand_extension',
        );

    public $event_id = NULL;
    public $title = NULL;
    public $owner = NULL;
    public $event_date = NULL;
    public $start_time = NULL;
    public $end_time = NULL;
    public $max_attendees = NULL;
    public $location_address = NULL;
    public $location_city = NULL;
    public $location_state = NULL;
    public $location_zip = NULL;
    public $contact_name = NULL;
    public $contact_title = NULL;
    public $contact_email = NULL;
    public $contact_phone = NULL;
    public $c_time = NULL;
    public $teaser = NULL;
    public $location_address_2 = NULL;
    public $dress_code = NULL;
    public $duration = NULL;
    public $cancel_policy = NULL;
    public $admin_reg_notification = NULL;
    public $m_time = NULL;
    public $expected_attendance = NULL;
    public $avg_past_attendance = NULL;
    public $number_years_held = NULL;
    public $marketing_start_date = NULL;
    public $marketing_duration_in_weeks = NULL;
    public $nomination_id = NULL;
    public $nomination_deadline = NULL;
    public $nomination_description = NULL;
    public $nomination_marketing_start_date = NULL;
    public $nomination_marketing_duration_in_weeks = NULL;
    public $marketing_includes = NULL;
    public $nomination_marketing_includes = NULL;
    public $map_href = NULL;
    public $sort_order = NULL;
    public $is_active = NULL;
    public $is_registration_open = NULL;
    public $is_soldout = NULL;
    public $is_suspended = NULL;
    public $is_cancelled = NULL;
    public $is_invite_only = NULL;
    public $close_registration = NULL;
    public $has_admin_threshold_alert = NULL;
    public $show_on_bizj_calendar = NULL;
    public $has_nominations = NULL;
    public $venue_can_support_autos = NULL;
    public $has_sponsor_signage = NULL;
    public $sponsor_signage_type_id = NULL;
    public $is_approx_date = NULL;
    public $is_approx_time = NULL;
    public $contact_only = NULL;
    public $microsite_url = NULL;
    public $prefer_microsite = NULL;
    public $skin = NULL;
    public $body_text = NULL;
    public $has_sponsors = NULL;
    public $has_single_sponsor_tier = NULL;
    public $has_supplement = NULL;
    public $is_supplement_handed_out = NULL;
    public $supplement_deadline = NULL;
    public $supplement_pub_date = NULL;
    public $market_owned = NULL;
    public $is_custom_event = NULL;
    public $event_type = NULL;
    public $custom_reminder_email = NULL;
    public $is_brand_extension = NULL;
    public $brand_extension_year = NULL;
    public $brand_id = NULL;
    public $redirect_event_id = NULL;
    public $sponsor_display_start_date = NULL;
    public $sponsor_display_end_date = NULL;
    public $admin_email = NULL;
    public $shipping_address = NULL;
    public $hashtag = NULL;
    public $notes = NULL;
    public $setup_time = NULL;
    public $modified_by = NULL;
    public $deleted_at = NULL;
    public $DBColumnsArray = 
        array (
          'event_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'title' => 
          array (
          ),
          'owner' => 
          array (
          ),
          'event_date' => 
          array (
          ),
          'start_time' => 
          array (
          ),
          'end_time' => 
          array (
          ),
          'max_attendees' => 
          array (
          ),
          'location_address' => 
          array (
          ),
          'location_city' => 
          array (
          ),
          'location_state' => 
          array (
          ),
          'location_zip' => 
          array (
          ),
          'contact_name' => 
          array (
          ),
          'contact_title' => 
          array (
          ),
          'contact_email' => 
          array (
          ),
          'contact_phone' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'teaser' => 
          array (
          ),
          'location_address_2' => 
          array (
          ),
          'dress_code' => 
          array (
          ),
          'duration' => 
          array (
          ),
          'cancel_policy' => 
          array (
          ),
          'admin_reg_notification' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'expected_attendance' => 
          array (
          ),
          'avg_past_attendance' => 
          array (
          ),
          'number_years_held' => 
          array (
          ),
          'marketing_start_date' => 
          array (
          ),
          'marketing_duration_in_weeks' => 
          array (
          ),
          'nomination_id' => 
          array (
          ),
          'nomination_deadline' => 
          array (
          ),
          'nomination_description' => 
          array (
          ),
          'nomination_marketing_start_date' => 
          array (
          ),
          'nomination_marketing_duration_in_weeks' => 
          array (
          ),
          'marketing_includes' => 
          array (
          ),
          'nomination_marketing_includes' => 
          array (
          ),
          'map_href' => 
          array (
          ),
          'sort_order' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'is_registration_open' => 
          array (
          ),
          'is_soldout' => 
          array (
          ),
          'is_suspended' => 
          array (
          ),
          'is_cancelled' => 
          array (
          ),
          'is_invite_only' => 
          array (
          ),
          'close_registration' => 
          array (
          ),
          'has_admin_threshold_alert' => 
          array (
          ),
          'show_on_bizj_calendar' => 
          array (
          ),
          'has_nominations' => 
          array (
          ),
          'venue_can_support_autos' => 
          array (
          ),
          'has_sponsor_signage' => 
          array (
          ),
          'sponsor_signage_type_id' => 
          array (
          ),
          'is_approx_date' => 
          array (
          ),
          'is_approx_time' => 
          array (
          ),
          'contact_only' => 
          array (
          ),
          'microsite_url' => 
          array (
          ),
          'prefer_microsite' => 
          array (
          ),
          'skin' => 
          array (
          ),
          'body_text' => 
          array (
          ),
          'has_sponsors' => 
          array (
          ),
          'has_single_sponsor_tier' => 
          array (
          ),
          'has_supplement' => 
          array (
          ),
          'is_supplement_handed_out' => 
          array (
          ),
          'supplement_deadline' => 
          array (
          ),
          'supplement_pub_date' => 
          array (
          ),
          'market_owned' => 
          array (
          ),
          'is_custom_event' => 
          array (
          ),
          'event_type' => 
          array (
          ),
          'custom_reminder_email' => 
          array (
          ),
          'is_brand_extension' => 
          array (
          ),
          'brand_extension_year' => 
          array (
          ),
          'brand_id' => 
          array (
          ),
          'redirect_event_id' => 
          array (
          ),
          'sponsor_display_start_date' => 
          array (
          ),
          'sponsor_display_end_date' => 
          array (
          ),
          'admin_email' => 
          array (
          ),
          'shipping_address' => 
          array (
          ),
          'hashtag' => 
          array (
          ),
          'notes' => 
          array (
          ),
          'setup_time' => 
          array (
          ),
          'modified_by' => 
          array (
          ),
          'deleted_at' => 
          array (
          ),
        );




}

?>