<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in EvEventMediaMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class EvEventMediaMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'ev_event_media_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'event_id',
          1 => 'media_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'event_id',
          1 => 'media_id',
        );

    public $event_id = NULL;
    public $media_id = NULL;
    public $ord = NULL;
    public $url = NULL;
    public $title = NULL;
    public $caption = NULL;
    public $art_credit = NULL;
    public $crop_data = NULL;
    public $DBColumnsArray = 
        array (
          'event_id' => 
          array (
            0 => 1,
          ),
          'media_id' => 
          array (
            0 => 1,
          ),
          'ord' => 
          array (
          ),
          'url' => 
          array (
          ),
          'title' => 
          array (
          ),
          'caption' => 
          array (
          ),
          'art_credit' => 
          array (
          ),
          'crop_data' => 
          array (
          ),
        );




}

?>