<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in FindwhatRobotIpAddr
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class FindwhatRobotIpAddr extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'findwhat_robot_ip_addr';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'ip_addr',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'ip_addr',
          1 => 'c_time',
        );

    public $ip_addr = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'ip_addr' => 
          array (
            0 => 1,
          ),
          'c_time' => 
          array (
          ),
        );




}

?>