<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in GeoIpAddress
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class GeoIpAddress extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'geo_ip_address';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'ip_numeric',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'ip_numeric',
          1 => 'ip_string',
          2 => 'analysis_level',
          3 => 'created_at',
          4 => 'updated_at',
        );

    public $ip_numeric = NULL;
    public $ip_string = NULL;
    public $country_code = NULL;
    public $region_code = NULL;
    public $region_name = NULL;
    public $city_name = NULL;
    public $phone_area_code = NULL;
    public $postal_code = NULL;
    public $metro_code = NULL;
    public $latitude = NULL;
    public $longitude = NULL;
    public $host_name = NULL;
    public $org_name = NULL;
    public $analysis_level = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'ip_numeric' => 
          array (
            0 => 1,
          ),
          'ip_string' => 
          array (
          ),
          'country_code' => 
          array (
          ),
          'region_code' => 
          array (
          ),
          'region_name' => 
          array (
          ),
          'city_name' => 
          array (
          ),
          'phone_area_code' => 
          array (
          ),
          'postal_code' => 
          array (
          ),
          'metro_code' => 
          array (
          ),
          'latitude' => 
          array (
          ),
          'longitude' => 
          array (
          ),
          'host_name' => 
          array (
          ),
          'org_name' => 
          array (
          ),
          'analysis_level' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>