<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in HeaderPromos
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class HeaderPromos extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'header_promos';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $market = NULL;
    public $url = NULL;
    public $text = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'url' => 
          array (
          ),
          'text' => 
          array (
          ),
        );




}

?>