<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in HomeListingVersion
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class HomeListingVersion extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'home_listing_version';
    const AUTO_INCREMENT_COLUMN = 'home_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'home_id',
          1 => 'version',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'home_id',
          1 => 'is_active',
          2 => 'is_new',
          3 => 'is_complete',
          4 => 'is_approved',
          5 => 'is_reduced',
          6 => 'agent_id',
          7 => 'agency_id',
          8 => 'market_id',
          9 => 'start_date',
          10 => 'end_date',
          11 => 'price',
          12 => 'listing_url',
          13 => 'bedroom_count',
          14 => 'full_bath_count',
          15 => 'half_bath_count',
          16 => 'house_size',
          17 => 'lot_size',
          18 => 'lot_size_unit',
          19 => 'photo_count',
          20 => 'votes',
          21 => 'disable_email_notification',
          22 => 'disable_article_generation',
          23 => 'last_modified_by',
          24 => 'created_at',
          25 => 'updated_at',
          26 => 'version',
        );

    public $home_id = NULL;
    public $is_active = NULL;
    public $is_new = NULL;
    public $is_complete = NULL;
    public $is_approved = NULL;
    public $is_reduced = NULL;
    public $agent_id = NULL;
    public $agency_id = NULL;
    public $market_id = NULL;
    public $feature_date = NULL;
    public $start_date = NULL;
    public $end_date = NULL;
    public $title = NULL;
    public $home_type = NULL;
    public $description = NULL;
    public $gallery_description = NULL;
    public $neighborhood = NULL;
    public $address1 = NULL;
    public $address2 = NULL;
    public $city = NULL;
    public $state = NULL;
    public $postal_code = NULL;
    public $price = NULL;
    public $listing_url = NULL;
    public $page_id = NULL;
    public $page_url = NULL;
    public $special_category_id = NULL;
    public $bedroom_count = NULL;
    public $full_bath_count = NULL;
    public $half_bath_count = NULL;
    public $house_size = NULL;
    public $lot_size = NULL;
    public $lot_size_unit = NULL;
    public $gallery_id = NULL;
    public $photo_count = NULL;
    public $tease_photo_url = NULL;
    public $tease_photo_crops = NULL;
    public $votes = NULL;
    public $weekly_winner_start_date = NULL;
    public $monthly_winner_start_date = NULL;
    public $additional_email_notifications = NULL;
    public $disable_email_notification = NULL;
    public $disable_article_generation = NULL;
    public $last_modified_by = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $version = NULL;
    public $DBColumnsArray = 
        array (
          'home_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'is_active' => 
          array (
          ),
          'is_new' => 
          array (
          ),
          'is_complete' => 
          array (
          ),
          'is_approved' => 
          array (
          ),
          'is_reduced' => 
          array (
          ),
          'agent_id' => 
          array (
          ),
          'agency_id' => 
          array (
          ),
          'market_id' => 
          array (
          ),
          'feature_date' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'end_date' => 
          array (
          ),
          'title' => 
          array (
          ),
          'home_type' => 
          array (
          ),
          'description' => 
          array (
          ),
          'gallery_description' => 
          array (
          ),
          'neighborhood' => 
          array (
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'postal_code' => 
          array (
          ),
          'price' => 
          array (
          ),
          'listing_url' => 
          array (
          ),
          'page_id' => 
          array (
          ),
          'page_url' => 
          array (
          ),
          'special_category_id' => 
          array (
          ),
          'bedroom_count' => 
          array (
          ),
          'full_bath_count' => 
          array (
          ),
          'half_bath_count' => 
          array (
          ),
          'house_size' => 
          array (
          ),
          'lot_size' => 
          array (
          ),
          'lot_size_unit' => 
          array (
          ),
          'gallery_id' => 
          array (
          ),
          'photo_count' => 
          array (
          ),
          'tease_photo_url' => 
          array (
          ),
          'tease_photo_crops' => 
          array (
          ),
          'votes' => 
          array (
          ),
          'weekly_winner_start_date' => 
          array (
          ),
          'monthly_winner_start_date' => 
          array (
          ),
          'additional_email_notifications' => 
          array (
          ),
          'disable_email_notification' => 
          array (
          ),
          'disable_article_generation' => 
          array (
          ),
          'last_modified_by' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'version' => 
          array (
            0 => 1,
          ),
        );




}

?>