<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in HomeListingMediaMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class HomeListingMediaMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'home_listing_media_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'home_id',
          1 => 'image_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'home_id',
          1 => 'image_id',
        );

    public $home_id = NULL;
    public $image_id = NULL;
    public $media_id = NULL;
    public $ord = NULL;
    public $title = NULL;
    public $caption = NULL;
    public $DBColumnsArray = 
        array (
          'home_id' => 
          array (
            0 => 1,
          ),
          'image_id' => 
          array (
            0 => 1,
          ),
          'media_id' => 
          array (
          ),
          'ord' => 
          array (
          ),
          'title' => 
          array (
          ),
          'caption' => 
          array (
          ),
        );




}

?>