<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in IDirectoryListing
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class IDirectoryListing extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'i_directory_listing';
    const AUTO_INCREMENT_COLUMN = 'listing_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'listing_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'listing_id',
          1 => 'market',
          2 => 'listing',
          3 => 'url',
          4 => 'phone',
          5 => 'email',
          6 => 'description',
        );

    public $listing_id = NULL;
    public $market = NULL;
    public $listing = NULL;
    public $url = NULL;
    public $phone = NULL;
    public $email = NULL;
    public $description = NULL;
    public $DBColumnsArray = 
        array (
          'listing_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'listing' => 
          array (
          ),
          'url' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'email' => 
          array (
          ),
          'description' => 
          array (
          ),
        );




}

?>