<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Image
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class Image extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'image';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'c_time',
          2 => 'rev_time',
          3 => 'obj_id',
        );

    public $id = NULL;
    public $c_time = NULL;
    public $revision = NULL;
    public $rev_time = NULL;
    public $caption = NULL;
    public $width = NULL;
    public $height = NULL;
    public $img_type = NULL;
    public $data_id = NULL;
    public $deleted = NULL;
    public $obj_id = NULL;
    public $obj_type = NULL;
    public $byline = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'c_time' => 
          array (
          ),
          'revision' => 
          array (
          ),
          'rev_time' => 
          array (
          ),
          'caption' => 
          array (
          ),
          'width' => 
          array (
          ),
          'height' => 
          array (
          ),
          'img_type' => 
          array (
          ),
          'data_id' => 
          array (
          ),
          'deleted' => 
          array (
          ),
          'obj_id' => 
          array (
          ),
          'obj_type' => 
          array (
          ),
          'byline' => 
          array (
          ),
        );




}

?>