<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ImageData
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class ImageData extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'image_data';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'image_id',
        );

    public $id = NULL;
    public $data = NULL;
    public $image_id = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'data' => 
          array (
          ),
          'image_id' => 
          array (
          ),
        );




}

?>