<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in IndustryTopicEmailPromo
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class IndustryTopicEmailPromo extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'industry_topic_email_promo';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'market_id',
          2 => 'ref_type',
          3 => 'ref_id',
          4 => 'email_product_id',
        );

    public $id = NULL;
    public $market_id = NULL;
    public $ref_type = NULL;
    public $ref_id = NULL;
    public $email_product_id = NULL;
    public $promo_headline = NULL;
    public $promo_text = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market_id' => 
          array (
          ),
          'ref_type' => 
          array (
          ),
          'ref_id' => 
          array (
          ),
          'email_product_id' => 
          array (
          ),
          'promo_headline' => 
          array (
          ),
          'promo_text' => 
          array (
          ),
        );




}

?>