<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in JobListingPromoEmail
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class JobListingPromoEmail extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'job_listing_promo_email';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'job_listing_id',
          1 => 'product_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'job_listing_id',
          1 => 'product_id',
        );

    public $job_listing_id = NULL;
    public $product_id = NULL;
    public $DBColumnsArray = 
        array (
          'job_listing_id' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
            0 => 1,
          ),
        );




}

?>