<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in JobListingTransaction
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class JobListingTransaction extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'job_listing_transaction';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'job_listing_id',
          1 => 'transaction_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'job_listing_id',
          1 => 'transaction_id',
        );

    public $job_listing_id = NULL;
    public $transaction_id = NULL;
    public $DBColumnsArray = 
        array (
          'job_listing_id' => 
          array (
            0 => 1,
          ),
          'transaction_id' => 
          array (
            0 => 1,
          ),
        );




}

?>