<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in JobProviderAttListing
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class JobProviderAttListing extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'job_provider_att_listing';
    const AUTO_INCREMENT_COLUMN = 'job_listing_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'job_listing_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'job_listing_id',
          1 => 'company_name',
          2 => 'job_title',
          3 => 'created_at',
        );

    public $job_listing_id = NULL;
    public $job_id = NULL;
    public $tagline = NULL;
    public $date_posted = NULL;
    public $job_board = NULL;
    public $company_name = NULL;
    public $job_zip_code = NULL;
    public $job_title = NULL;
    public $job_description = NULL;
    public $job_url = NULL;
    public $is_featured = NULL;
    public $logo_url = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'job_listing_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'job_id' => 
          array (
          ),
          'tagline' => 
          array (
          ),
          'date_posted' => 
          array (
          ),
          'job_board' => 
          array (
          ),
          'company_name' => 
          array (
          ),
          'job_zip_code' => 
          array (
          ),
          'job_title' => 
          array (
          ),
          'job_description' => 
          array (
          ),
          'job_url' => 
          array (
          ),
          'is_featured' => 
          array (
          ),
          'logo_url' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>