<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in JobSectionFrontLogo
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class JobSectionFrontLogo extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'job_section_front_logo';
    const AUTO_INCREMENT_COLUMN = 'job_section_front_logo_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'job_section_front_logo_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'job_section_front_logo_id',
          1 => 'job_section_front_id',
          2 => 'url',
          3 => 'html',
          4 => 'sort_order',
        );

    public $job_section_front_logo_id = NULL;
    public $job_section_front_id = NULL;
    public $url = NULL;
    public $image_id = NULL;
    public $html = NULL;
    public $sort_order = NULL;
    public $start_date = NULL;
    public $end_date = NULL;
    public $DBColumnsArray = 
        array (
          'job_section_front_logo_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'job_section_front_id' => 
          array (
          ),
          'url' => 
          array (
          ),
          'image_id' => 
          array (
          ),
          'html' => 
          array (
          ),
          'sort_order' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'end_date' => 
          array (
          ),
        );




}

?>