<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in JournalSubscriber
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class JournalSubscriber extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'journal_subscriber';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'subscriber_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'subscriber_id',
          1 => 'is_temporary',
          2 => 'updated_at',
        );

    public $subscriber_id = NULL;
    public $user_id = NULL;
    public $first_name = NULL;
    public $last_name = NULL;
    public $address1 = NULL;
    public $address2 = NULL;
    public $city = NULL;
    public $state = NULL;
    public $zip = NULL;
    public $is_temporary = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'subscriber_id' => 
          array (
            0 => 1,
          ),
          'user_id' => 
          array (
          ),
          'first_name' => 
          array (
          ),
          'last_name' => 
          array (
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'zip' => 
          array (
          ),
          'is_temporary' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>