<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in JstSummary
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class JstSummary extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'jst_summary';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $log_date = NULL;
    public $page = NULL;
    public $section = NULL;
    public $element = NULL;
    public $count = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'log_date' => 
          array (
          ),
          'page' => 
          array (
          ),
          'section' => 
          array (
          ),
          'element' => 
          array (
          ),
          'count' => 
          array (
          ),
        );




}

?>