<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in LocalMarketNav
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class LocalMarketNav extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'local_market_nav';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'market',
          2 => 'c_time',
          3 => 'date',
        );

    public $id = NULL;
    public $market = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $date = NULL;
    public $anchor = NULL;
    public $url = NULL;
    public $position = NULL;
    public $inactive = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'date' => 
          array (
          ),
          'anchor' => 
          array (
          ),
          'url' => 
          array (
          ),
          'position' => 
          array (
          ),
          'inactive' => 
          array (
          ),
        );




}

?>