<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in LocalMarketPromo
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class LocalMarketPromo extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'local_market_promo';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $market = NULL;
    public $date = NULL;
    public $promo_text = NULL;
    public $image_id = NULL;
    public $url = NULL;
    public $headline = NULL;
    public $headline_style = NULL;
    public $disabled = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'date' => 
          array (
          ),
          'promo_text' => 
          array (
          ),
          'image_id' => 
          array (
          ),
          'url' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'headline_style' => 
          array (
          ),
          'disabled' => 
          array (
          ),
        );




}

?>