<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MarketCustomFormNominationResults
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class MarketCustomFormNominationResults extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'market_custom_form_nomination_results';
    const AUTO_INCREMENT_COLUMN = 'entry_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'entry_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'entry_id',
        );

    public $entry_id = NULL;
    public $form_id = NULL;
    public $award_name = NULL;
    public $market = NULL;
    public $your_name = NULL;
    public $your_company = NULL;
    public $your_address = NULL;
    public $your_email = NULL;
    public $nominee_name = NULL;
    public $nominee_company = NULL;
    public $nominee_address = NULL;
    public $nominee_email = NULL;
    public $comments = NULL;
    public $your_phone = NULL;
    public $nominee_phone = NULL;
    public $date_received = NULL;
    public $custom_fields = NULL;
    public $your_first_name = NULL;
    public $your_last_name = NULL;
    public $nominee_first_name = NULL;
    public $nominee_last_name = NULL;
    public $DBColumnsArray = 
        array (
          'entry_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'form_id' => 
          array (
          ),
          'award_name' => 
          array (
          ),
          'market' => 
          array (
          ),
          'your_name' => 
          array (
          ),
          'your_company' => 
          array (
          ),
          'your_address' => 
          array (
          ),
          'your_email' => 
          array (
          ),
          'nominee_name' => 
          array (
          ),
          'nominee_company' => 
          array (
          ),
          'nominee_address' => 
          array (
          ),
          'nominee_email' => 
          array (
          ),
          'comments' => 
          array (
          ),
          'your_phone' => 
          array (
          ),
          'nominee_phone' => 
          array (
          ),
          'date_received' => 
          array (
          ),
          'custom_fields' => 
          array (
          ),
          'your_first_name' => 
          array (
          ),
          'your_last_name' => 
          array (
          ),
          'nominee_first_name' => 
          array (
          ),
          'nominee_last_name' => 
          array (
          ),
        );




}

?>