<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MediaMetadata
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class MediaMetadata extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'media_metadata';
    const AUTO_INCREMENT_COLUMN = 'meta_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'meta_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'meta_id',
          1 => 'media_id',
          2 => 'ord',
          3 => 'meta_name',
          4 => 'meta_value',
        );

    public $meta_id = NULL;
    public $media_id = NULL;
    public $ord = NULL;
    public $meta_name = NULL;
    public $meta_value = NULL;
    public $DBColumnsArray = 
        array (
          'meta_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'media_id' => 
          array (
          ),
          'ord' => 
          array (
          ),
          'meta_name' => 
          array (
          ),
          'meta_value' => 
          array (
          ),
        );




}

?>