<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MomBatch
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class MomBatch extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'mom_batch';
    const AUTO_INCREMENT_COLUMN = 'batch_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'batch_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'batch_id',
          1 => 'created_at',
        );

    public $batch_id = NULL;
    public $generated_by = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'batch_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'generated_by' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>