<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MostRead
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class MostRead extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'most_read';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'site',
          2 => 'use_flag',
          3 => 'c_time',
          4 => 'image_count',
        );

    public $id = NULL;
    public $site = NULL;
    public $market_code = NULL;
    public $object_type = NULL;
    public $object_uid = NULL;
    public $page_id = NULL;
    public $views = NULL;
    public $use_flag = NULL;
    public $c_time = NULL;
    public $image_count = NULL;
    public $group_type = NULL;
    public $group_id = NULL;
    public $published_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'site' => 
          array (
          ),
          'market_code' => 
          array (
          ),
          'object_type' => 
          array (
          ),
          'object_uid' => 
          array (
          ),
          'page_id' => 
          array (
          ),
          'views' => 
          array (
          ),
          'use_flag' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'image_count' => 
          array (
          ),
          'group_type' => 
          array (
          ),
          'group_id' => 
          array (
          ),
          'published_at' => 
          array (
          ),
        );




}

?>