<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in MostViewedStoriesIndustry
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class MostViewedStoriesIndustry extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'most_viewed_stories_industry';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'story_id',
        );

    public $id = NULL;
    public $vertical_topic_id = NULL;
    public $vertical_subtopic_id = NULL;
    public $story_id = NULL;
    public $views = NULL;
    public $story_date = NULL;
    public $headline = NULL;
    public $issue_date = NULL;
    public $slug = NULL;
    public $story_type = NULL;
    public $default_skin = NULL;
    public $subhead = NULL;
    public $pub = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'vertical_topic_id' => 
          array (
          ),
          'vertical_subtopic_id' => 
          array (
          ),
          'story_id' => 
          array (
          ),
          'views' => 
          array (
          ),
          'story_date' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'slug' => 
          array (
          ),
          'story_type' => 
          array (
          ),
          'default_skin' => 
          array (
          ),
          'subhead' => 
          array (
          ),
          'pub' => 
          array (
          ),
        );




}

?>