<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NetprospexIndustriesMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class NetprospexIndustriesMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'netprospex_industries_map';
    const AUTO_INCREMENT_COLUMN = 'map_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'map_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'map_id',
        );

    public $map_id = NULL;
    public $netprospex_id = NULL;
    public $vertical_topic_id = NULL;
    public $DBColumnsArray = 
        array (
          'map_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'netprospex_id' => 
          array (
          ),
          'vertical_topic_id' => 
          array (
          ),
        );




}

?>