<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NetprospexFeatured
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class NetprospexFeatured extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'netprospex_featured';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'label',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'market',
          1 => 'id',
          2 => 'type',
          3 => 'label',
        );

    public $market = NULL;
    public $id = NULL;
    public $type = NULL;
    public $label = NULL;
    public $DBColumnsArray = 
        array (
          'market' => 
          array (
          ),
          'id' => 
          array (
          ),
          'type' => 
          array (
          ),
          'label' => 
          array (
            0 => 1,
          ),
        );




}

?>