<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NetprospexMarketData
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class NetprospexMarketData extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'netprospex_market_data';
    const AUTO_INCREMENT_COLUMN = 'market_data_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'market_data_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'market_data_id',
        );

    public $market_data_id = NULL;
    public $brand = NULL;
    public $marketSID = NULL;
    public $personCount = NULL;
    public $consolidatedLabel = NULL;
    public $DBColumnsArray = 
        array (
          'market_data_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'brand' => 
          array (
          ),
          'marketSID' => 
          array (
          ),
          'personCount' => 
          array (
          ),
          'consolidatedLabel' => 
          array (
          ),
        );




}

?>