<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NewsleBio
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class NewsleBio extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'newsle_bio';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'market_id',
          2 => 'newsle_uid',
          3 => 'bio_name',
          4 => 'is_photo_approved',
          5 => 'is_active',
          6 => 'created_at',
          7 => 'updated_at',
        );

    public $id = NULL;
    public $market_id = NULL;
    public $newsle_uid = NULL;
    public $bio_name = NULL;
    public $profile_url = NULL;
    public $photo_url = NULL;
    public $is_photo_approved = NULL;
    public $biography = NULL;
    public $json_data = NULL;
    public $is_active = NULL;
    public $newsle_updated_at = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market_id' => 
          array (
          ),
          'newsle_uid' => 
          array (
          ),
          'bio_name' => 
          array (
          ),
          'profile_url' => 
          array (
          ),
          'photo_url' => 
          array (
          ),
          'is_photo_approved' => 
          array (
          ),
          'biography' => 
          array (
          ),
          'json_data' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'newsle_updated_at' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>