<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in NominationQuestion
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class NominationQuestion extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'nomination_question';
    const AUTO_INCREMENT_COLUMN = 'question_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'question_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'question_id',
          1 => 'nomination_id',
          2 => 'question_type',
          3 => 'position',
          4 => 'required',
          5 => 'created_at',
          6 => 'updated_at',
        );

    public $question_id = NULL;
    public $nomination_id = NULL;
    public $question_text = NULL;
    public $question_type = NULL;
    public $paragraph_size = NULL;
    public $choices = NULL;
    public $help_text = NULL;
    public $position = NULL;
    public $required = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'question_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'nomination_id' => 
          array (
          ),
          'question_text' => 
          array (
          ),
          'question_type' => 
          array (
          ),
          'paragraph_size' => 
          array (
          ),
          'choices' => 
          array (
          ),
          'help_text' => 
          array (
          ),
          'position' => 
          array (
          ),
          'required' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>