<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in OBolProducts
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class OBolProducts extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'o_bol_products';
    const AUTO_INCREMENT_COLUMN = 'product_uid';
    const PRIMARY_KEYS = 
        array (
          0 => 'product_uid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'product_uid',
        );

    public $product_uid = NULL;
    public $active = NULL;
    public $market = NULL;
    public $description = NULL;
    public $price = NULL;
    public $sku = NULL;
    public $is_shippable = NULL;
    public $publication_month = NULL;
    public $c_time = NULL;
    public $media_type = NULL;
    public $city = NULL;
    public $is_taxable = NULL;
    public $download_directory = NULL;
    public $release_date = NULL;
    public $is_stocked = NULL;
    public $filename = NULL;
    public $region_code = NULL;
    public $copyright = NULL;
    public $electronic_product_id = NULL;
    public $tc_sku = NULL;
    public $is_custom = NULL;
    public $pub_month = NULL;
    public $pub_year = NULL;
    public $multiview_product_id = NULL;
    public $DBColumnsArray = 
        array (
          'product_uid' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'active' => 
          array (
          ),
          'market' => 
          array (
          ),
          'description' => 
          array (
          ),
          'price' => 
          array (
          ),
          'sku' => 
          array (
          ),
          'is_shippable' => 
          array (
          ),
          'publication_month' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'media_type' => 
          array (
          ),
          'city' => 
          array (
          ),
          'is_taxable' => 
          array (
          ),
          'download_directory' => 
          array (
          ),
          'release_date' => 
          array (
          ),
          'is_stocked' => 
          array (
          ),
          'filename' => 
          array (
          ),
          'region_code' => 
          array (
          ),
          'copyright' => 
          array (
          ),
          'electronic_product_id' => 
          array (
          ),
          'tc_sku' => 
          array (
          ),
          'is_custom' => 
          array (
          ),
          'pub_month' => 
          array (
          ),
          'pub_year' => 
          array (
          ),
          'multiview_product_id' => 
          array (
          ),
        );




}

?>