<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ODemographicsOrder
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class ODemographicsOrder extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'o_demographics_order';
    const AUTO_INCREMENT_COLUMN = 'demographics_order_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'demographics_order_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'demographics_order_id',
          1 => 'user_id',
        );

    public $demographics_order_id = NULL;
    public $user_id = NULL;
    public $contact_email = NULL;
    public $billing_full_name = NULL;
    public $billing_company = NULL;
    public $billing_address_1 = NULL;
    public $billing_address_2 = NULL;
    public $billing_city = NULL;
    public $billing_state = NULL;
    public $billing_postal_code = NULL;
    public $billing_country_code = NULL;
    public $billing_phone = NULL;
    public $purchase_tax = NULL;
    public $purchase_subtotal = NULL;
    public $purchase_total = NULL;
    public $avs_code = NULL;
    public $bank_auth_code = NULL;
    public $purchase_time = NULL;
    public $product_id = NULL;
    public $product_desc = NULL;
    public $quantity = NULL;
    public $cardholder_name = NULL;
    public $cc_number_hidden = NULL;
    public $cc_exp_month = NULL;
    public $cc_exp_year = NULL;
    public $cybercash_order_id = NULL;
    public $cc_type = NULL;
    public $DBColumnsArray = 
        array (
          'demographics_order_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_id' => 
          array (
          ),
          'contact_email' => 
          array (
          ),
          'billing_full_name' => 
          array (
          ),
          'billing_company' => 
          array (
          ),
          'billing_address_1' => 
          array (
          ),
          'billing_address_2' => 
          array (
          ),
          'billing_city' => 
          array (
          ),
          'billing_state' => 
          array (
          ),
          'billing_postal_code' => 
          array (
          ),
          'billing_country_code' => 
          array (
          ),
          'billing_phone' => 
          array (
          ),
          'purchase_tax' => 
          array (
          ),
          'purchase_subtotal' => 
          array (
          ),
          'purchase_total' => 
          array (
          ),
          'avs_code' => 
          array (
          ),
          'bank_auth_code' => 
          array (
          ),
          'purchase_time' => 
          array (
          ),
          'product_id' => 
          array (
          ),
          'product_desc' => 
          array (
          ),
          'quantity' => 
          array (
          ),
          'cardholder_name' => 
          array (
          ),
          'cc_number_hidden' => 
          array (
          ),
          'cc_exp_month' => 
          array (
          ),
          'cc_exp_year' => 
          array (
          ),
          'cybercash_order_id' => 
          array (
          ),
          'cc_type' => 
          array (
          ),
        );




}

?>