<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in OFbookProducts
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class OFbookProducts extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'o_fbook_products';
    const AUTO_INCREMENT_COLUMN = 'product_uid';
    const PRIMARY_KEYS = 
        array (
          0 => 'product_uid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'product_uid',
        );

    public $product_uid = NULL;
    public $active = NULL;
    public $description = NULL;
    public $description_long = NULL;
    public $price = NULL;
    public $sku = NULL;
    public $is_shippable = NULL;
    public $c_time = NULL;
    public $is_taxable = NULL;
    public $is_stocked = NULL;
    public $production = NULL;
    public $DBColumnsArray = 
        array (
          'product_uid' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'active' => 
          array (
          ),
          'description' => 
          array (
          ),
          'description_long' => 
          array (
          ),
          'price' => 
          array (
          ),
          'sku' => 
          array (
          ),
          'is_shippable' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'is_taxable' => 
          array (
          ),
          'is_stocked' => 
          array (
          ),
          'production' => 
          array (
          ),
        );




}

?>