<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Page
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class Page extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'page';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'page_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'page_id',
          1 => 'site',
          2 => 'path',
          3 => 'slug',
          4 => 'issue_date',
          5 => 'release_time',
          6 => 'created_at',
          7 => 'updated_at',
          8 => 'rev_number',
          9 => 'headline',
          10 => 'is_premium',
          11 => 'is_native',
          12 => 'type_id',
          13 => 'allow_syndication',
        );

    public $page_id = NULL;
    public $site = NULL;
    public $path = NULL;
    public $slug = NULL;
    public $issue_date = NULL;
    public $release_time = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $rev_number = NULL;
    public $headline = NULL;
    public $short_headline = NULL;
    public $is_premium = NULL;
    public $is_native = NULL;
    public $journal_id = NULL;
    public $type_id = NULL;
    public $parent_page_id = NULL;
    public $published_at = NULL;
    public $revised_at = NULL;
    public $allow_syndication = NULL;
    public $DBColumnsArray = 
        array (
          'page_id' => 
          array (
            0 => 1,
          ),
          'site' => 
          array (
          ),
          'path' => 
          array (
          ),
          'slug' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'release_time' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'rev_number' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'short_headline' => 
          array (
          ),
          'is_premium' => 
          array (
          ),
          'is_native' => 
          array (
          ),
          'journal_id' => 
          array (
          ),
          'type_id' => 
          array (
          ),
          'parent_page_id' => 
          array (
          ),
          'published_at' => 
          array (
          ),
          'revised_at' => 
          array (
          ),
          'allow_syndication' => 
          array (
          ),
        );




}

?>