<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PageCmsLink
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PageCmsLink extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'page_cms_link';
    const AUTO_INCREMENT_COLUMN = 'page_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'page_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'page_id',
          1 => 'reserve_time',
          2 => 'type_id',
          3 => 'source',
        );

    public $page_id = NULL;
    public $reserve_time = NULL;
    public $publish_time = NULL;
    public $revision_time = NULL;
    public $delete_time = NULL;
    public $delete_issue_date = NULL;
    public $url = NULL;
    public $headline = NULL;
    public $type_id = NULL;
    public $source = NULL;
    public $DBColumnsArray = 
        array (
          'page_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'reserve_time' => 
          array (
          ),
          'publish_time' => 
          array (
          ),
          'revision_time' => 
          array (
          ),
          'delete_time' => 
          array (
          ),
          'delete_issue_date' => 
          array (
          ),
          'url' => 
          array (
          ),
          'headline' => 
          array (
          ),
          'type_id' => 
          array (
          ),
          'source' => 
          array (
          ),
        );




}

?>