<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PageCorrection
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PageCorrection extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'page_correction';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'page_id',
          2 => 'market_code',
          3 => 'correction',
          4 => 'is_daily',
          5 => 'created_at',
        );

    public $id = NULL;
    public $page_id = NULL;
    public $market_code = NULL;
    public $correction = NULL;
    public $is_daily = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'page_id' => 
          array (
          ),
          'market_code' => 
          array (
          ),
          'correction' => 
          array (
          ),
          'is_daily' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>