<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PBookoflists
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PBookoflists extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'p_bookoflists_2005';
    const AUTO_INCREMENT_COLUMN = 'bookoflists_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'bookoflists_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'bookoflists_id',
        );

    public $bookoflists_id = NULL;
    public $market = NULL;
    public $deadline = NULL;
    public $material_due = NULL;
    public $publish_date = NULL;
    public $phone = NULL;
    public $email = NULL;
    public $advertiser = NULL;
    public $num_images = NULL;
    public $initials = NULL;
    public $filename = NULL;
    public $DBColumnsArray = 
        array (
          'bookoflists_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'market' => 
          array (
          ),
          'deadline' => 
          array (
          ),
          'material_due' => 
          array (
          ),
          'publish_date' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'email' => 
          array (
          ),
          'advertiser' => 
          array (
          ),
          'num_images' => 
          array (
          ),
          'initials' => 
          array (
          ),
          'filename' => 
          array (
          ),
        );




}

?>