<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PCbsmwHeadlines
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PCbsmwHeadlines extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'p_cbsmw_headlines';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'guid',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'guid',
          1 => 'harvest_time',
        );

    public $guid = NULL;
    public $headline = NULL;
    public $url = NULL;
    public $column_name = NULL;
    public $author = NULL;
    public $industry = NULL;
    public $issues = NULL;
    public $abstract = NULL;
    public $channel = NULL;
    public $symbols = NULL;
    public $c_time = NULL;
    public $u_time = NULL;
    public $harvest_time = NULL;
    public $display_order = NULL;
    public $active = NULL;
    public $DBColumnsArray = 
        array (
          'guid' => 
          array (
            0 => 1,
          ),
          'headline' => 
          array (
          ),
          'url' => 
          array (
          ),
          'column_name' => 
          array (
          ),
          'author' => 
          array (
          ),
          'industry' => 
          array (
          ),
          'issues' => 
          array (
          ),
          'abstract' => 
          array (
          ),
          'channel' => 
          array (
          ),
          'symbols' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'u_time' => 
          array (
          ),
          'harvest_time' => 
          array (
          ),
          'display_order' => 
          array (
          ),
          'active' => 
          array (
          ),
        );




}

?>