<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PPromoBizbuzz
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PPromoBizbuzz extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'p_promo_bizbuzz';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
        );

    public $id = NULL;
    public $headline = NULL;
    public $url = NULL;
    public $sponsor_name = NULL;
    public $sponsor_url = NULL;
    public $is_microsoft = NULL;
    public $url_market = NULL;
    public $description = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'headline' => 
          array (
          ),
          'url' => 
          array (
          ),
          'sponsor_name' => 
          array (
          ),
          'sponsor_url' => 
          array (
          ),
          'is_microsoft' => 
          array (
          ),
          'url_market' => 
          array (
          ),
          'description' => 
          array (
          ),
        );




}

?>