<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PPromoFiftyfiftyExclusion
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PPromoFiftyfiftyExclusion extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'p_promo_fiftyfifty_exclusion';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
        );
    const NON_NULL_COLUMNS = 
        array (
        );

    public $id = NULL;
    public $market = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
          ),
          'market' => 
          array (
          ),
        );




}

?>