<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PulseResponseData
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PulseResponseData extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'pulse_response_data';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'response_id',
          1 => 'question_id',
          2 => 'option_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'response_id',
          1 => 'question_id',
          2 => 'option_id',
          3 => 'ord',
          4 => 'created_at',
        );

    public $response_id = NULL;
    public $question_id = NULL;
    public $option_id = NULL;
    public $ord = NULL;
    public $created_at = NULL;
    public $response = NULL;
    public $DBColumnsArray = 
        array (
          'response_id' => 
          array (
            0 => 1,
          ),
          'question_id' => 
          array (
            0 => 1,
          ),
          'option_id' => 
          array (
            0 => 1,
          ),
          'ord' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'response' => 
          array (
          ),
        );




}

?>