<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in PWomenNonprofit
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class PWomenNonprofit extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'p_women_nonprofit';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'm_time',
        );

    public $id = NULL;
    public $title = NULL;
    public $description = NULL;
    public $m_time = NULL;
    public $url = NULL;
    public $market = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'title' => 
          array (
          ),
          'description' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'url' => 
          array (
          ),
          'market' => 
          array (
          ),
        );




}

?>