<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in RichmanProject
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class RichmanProject extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'richman_project';
    const AUTO_INCREMENT_COLUMN = 'project_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'project_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'project_id',
          1 => 'm_time',
        );

    public $project_id = NULL;
    public $est_end_date = NULL;
    public $name = NULL;
    public $description = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'project_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'est_end_date' => 
          array (
          ),
          'name' => 
          array (
          ),
          'description' => 
          array (
          ),
          'm_time' => 
          array (
          ),
        );




}

?>