<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in ScoopRequests
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class ScoopRequests extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'scoop_requests';
    const AUTO_INCREMENT_COLUMN = 'request_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'request_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'request_id',
          1 => 'c_time',
        );

    public $request_id = NULL;
    public $string = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'request_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'string' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>