<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SectionTypeTemplateMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SectionTypeTemplateMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'section_type_template_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'section_id',
          1 => 'type_id',
          2 => 'skin',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'section_id',
          1 => 'type_id',
          2 => 'skin',
          3 => 'created_at',
          4 => 'updated_at',
        );

    public $section_id = NULL;
    public $type_id = NULL;
    public $skin = NULL;
    public $template_id = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'section_id' => 
          array (
            0 => 1,
          ),
          'type_id' => 
          array (
            0 => 1,
          ),
          'skin' => 
          array (
            0 => 1,
          ),
          'template_id' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>