<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SocmadCompanyVote
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SocmadCompanyVote extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'socmad_company_vote';
    const AUTO_INCREMENT_COLUMN = 'vote_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'vote_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'vote_id',
          1 => 'socmad_id',
          2 => 'user_id',
          3 => 'bracket_id',
          4 => 'size_category',
          5 => 'ip_address',
          6 => 'vote_date',
          7 => 'voted_at',
        );

    public $vote_id = NULL;
    public $socmad_id = NULL;
    public $user_id = NULL;
    public $bracket_id = NULL;
    public $size_category = NULL;
    public $ip_address = NULL;
    public $vote_date = NULL;
    public $voted_at = NULL;
    public $DBColumnsArray = 
        array (
          'vote_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'socmad_id' => 
          array (
          ),
          'user_id' => 
          array (
          ),
          'bracket_id' => 
          array (
          ),
          'size_category' => 
          array (
          ),
          'ip_address' => 
          array (
          ),
          'vote_date' => 
          array (
          ),
          'voted_at' => 
          array (
          ),
        );




}

?>