<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SpecialEditionSections
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SpecialEditionSections extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'special_edition_sections';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'title',
          2 => 'c_time',
          3 => 'market',
        );

    public $id = NULL;
    public $title = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $issue_date = NULL;
    public $active = NULL;
    public $market = NULL;
    public $order = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'title' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'issue_date' => 
          array (
          ),
          'active' => 
          array (
          ),
          'market' => 
          array (
          ),
          'order' => 
          array (
          ),
        );




}

?>