<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SportsTeamBackup
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SportsTeamBackup extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'sports_team_backup';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'league',
          2 => 'abbrev',
          3 => 'city',
          4 => 'name',
        );

    public $id = NULL;
    public $league = NULL;
    public $abbrev = NULL;
    public $city = NULL;
    public $market = NULL;
    public $name = NULL;
    public $conference = NULL;
    public $division = NULL;
    public $address = NULL;
    public $add_city = NULL;
    public $state = NULL;
    public $zip = NULL;
    public $phone = NULL;
    public $fax = NULL;
    public $website = NULL;
    public $facility = NULL;
    public $ownerships = NULL;
    public $media = NULL;
    public $executive = NULL;
    public $email = NULL;
    public $sponsors = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'league' => 
          array (
          ),
          'abbrev' => 
          array (
          ),
          'city' => 
          array (
          ),
          'market' => 
          array (
          ),
          'name' => 
          array (
          ),
          'conference' => 
          array (
          ),
          'division' => 
          array (
          ),
          'address' => 
          array (
          ),
          'add_city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'zip' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'fax' => 
          array (
          ),
          'website' => 
          array (
          ),
          'facility' => 
          array (
          ),
          'ownerships' => 
          array (
          ),
          'media' => 
          array (
          ),
          'executive' => 
          array (
          ),
          'email' => 
          array (
          ),
          'sponsors' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>