<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SportsTeamDownloads
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SportsTeamDownloads extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'sports_team_downloads';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'transaction_id',
          1 => 'product_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'transaction_id',
          1 => 'product_id',
        );

    public $transaction_id = NULL;
    public $product_id = NULL;
    public $number_of_downloads = NULL;
    public $DBColumnsArray = 
        array (
          'transaction_id' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
            0 => 1,
          ),
          'number_of_downloads' => 
          array (
          ),
        );




}

?>