<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SubsAddressChange
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SubsAddressChange extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'subs_address_change';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'handled',
        );

    public $id = NULL;
    public $subscriber_id = NULL;
    public $firstname = NULL;
    public $lastname = NULL;
    public $firmname = NULL;
    public $title = NULL;
    public $address1 = NULL;
    public $address2 = NULL;
    public $city = NULL;
    public $state = NULL;
    public $zip = NULL;
    public $phone = NULL;
    public $old_firstname = NULL;
    public $old_lastname = NULL;
    public $old_firmname = NULL;
    public $old_address1 = NULL;
    public $old_address2 = NULL;
    public $old_city = NULL;
    public $old_state = NULL;
    public $old_zip = NULL;
    public $old_phone = NULL;
    public $handled = NULL;
    public $handled_time = NULL;
    public $handled_user = NULL;
    public $c_time = NULL;
    public $market = NULL;
    public $user_id = NULL;
    public $interface = NULL;
    public $effective_date = NULL;
    public $email = NULL;
    public $fax = NULL;
    public $stamp = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'subscriber_id' => 
          array (
          ),
          'firstname' => 
          array (
          ),
          'lastname' => 
          array (
          ),
          'firmname' => 
          array (
          ),
          'title' => 
          array (
          ),
          'address1' => 
          array (
          ),
          'address2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'zip' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'old_firstname' => 
          array (
          ),
          'old_lastname' => 
          array (
          ),
          'old_firmname' => 
          array (
          ),
          'old_address1' => 
          array (
          ),
          'old_address2' => 
          array (
          ),
          'old_city' => 
          array (
          ),
          'old_state' => 
          array (
          ),
          'old_zip' => 
          array (
          ),
          'old_phone' => 
          array (
          ),
          'handled' => 
          array (
          ),
          'handled_time' => 
          array (
          ),
          'handled_user' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'market' => 
          array (
          ),
          'user_id' => 
          array (
          ),
          'interface' => 
          array (
          ),
          'effective_date' => 
          array (
          ),
          'email' => 
          array (
          ),
          'fax' => 
          array (
          ),
          'stamp' => 
          array (
          ),
        );




}

?>