<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SupressedEmail
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SupressedEmail extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'supressed_email';
    const AUTO_INCREMENT_COLUMN = 'supressed_email_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'supressed_email_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'supressed_email_id',
        );

    public $supressed_email_id = NULL;
    public $email = NULL;
    public $c_time = NULL;
    public $source = NULL;
    public $DBColumnsArray = 
        array (
          'supressed_email_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'email' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'source' => 
          array (
          ),
        );




}

?>