<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SyndapiPartner
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SyndapiPartner extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'syndapi_partner';
    const AUTO_INCREMENT_COLUMN = 'partner_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'partner_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'partner_id',
          1 => 'partner_name',
          2 => 'quota_connection_limit',
          3 => 'api_key',
          4 => 'is_active',
          5 => 'created_at',
          6 => 'updated_at',
        );

    public $partner_id = NULL;
    public $partner_name = NULL;
    public $quota_connection_limit = NULL;
    public $api_key = NULL;
    public $start_date = NULL;
    public $end_date = NULL;
    public $expires_at = NULL;
    public $is_active = NULL;
    public $delivery_notes = NULL;
    public $contract_notes = NULL;
    public $bizj_contact = NULL;
    public $public_url = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'partner_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'partner_name' => 
          array (
          ),
          'quota_connection_limit' => 
          array (
          ),
          'api_key' => 
          array (
          ),
          'start_date' => 
          array (
          ),
          'end_date' => 
          array (
          ),
          'expires_at' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'delivery_notes' => 
          array (
          ),
          'contract_notes' => 
          array (
          ),
          'bizj_contact' => 
          array (
          ),
          'public_url' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>