<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in SyndicateStats
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class SyndicateStats extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'syndicate_stats';
    const AUTO_INCREMENT_COLUMN = 'stats_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'stats_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'stats_id',
          1 => 'stats_name',
          2 => 'stats_short_name',
          3 => 'adapter_name',
          4 => 'modified_time',
        );

    public $stats_id = NULL;
    public $stats_name = NULL;
    public $stats_short_name = NULL;
    public $adapter_name = NULL;
    public $adapter_arguments = NULL;
    public $stats_description = NULL;
    public $created_time = NULL;
    public $modified_time = NULL;
    public $DBColumnsArray = 
        array (
          'stats_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'stats_name' => 
          array (
          ),
          'stats_short_name' => 
          array (
          ),
          'adapter_name' => 
          array (
          ),
          'adapter_arguments' => 
          array (
          ),
          'stats_description' => 
          array (
          ),
          'created_time' => 
          array (
          ),
          'modified_time' => 
          array (
          ),
        );




}

?>