<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in TopPrivateCompanyDeloitte
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class TopPrivateCompanyDeloitte extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'top_private_company_deloitte';
    const AUTO_INCREMENT_COLUMN = 'office_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'office_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'office_id',
          1 => 'city_id',
          2 => 'contact_name',
          3 => 'created_at',
          4 => 'updated_at',
        );

    public $office_id = NULL;
    public $city_id = NULL;
    public $contact_name = NULL;
    public $full_address = NULL;
    public $phone_number = NULL;
    public $email = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'office_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'city_id' => 
          array (
          ),
          'contact_name' => 
          array (
          ),
          'full_address' => 
          array (
          ),
          'phone_number' => 
          array (
          ),
          'email' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>