<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in Treecam
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class Treecam extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'treecam';
    const AUTO_INCREMENT_COLUMN = 'view';
    const PRIMARY_KEYS = 
        array (
          0 => 'view',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'view',
          1 => 'm_time',
        );

    public $view = NULL;
    public $m_time = NULL;
    public $DBColumnsArray = 
        array (
          'view' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'm_time' => 
          array (
          ),
        );




}

?>