<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in TweetList
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class TweetList extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'tweet_list';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'handle',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'handle',
          1 => 'created_at',
          2 => 'updated_at',
        );

    public $handle = NULL;
    public $display_name = NULL;
    public $tweets = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'handle' => 
          array (
            0 => 1,
          ),
          'display_name' => 
          array (
          ),
          'tweets' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>