<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UAccountTracking
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UAccountTracking extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_account_tracking';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'user_id',
          2 => 'created_at',
        );

    public $id = NULL;
    public $user_id = NULL;
    public $tracking_data = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_id' => 
          array (
          ),
          'tracking_data' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>