<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UAccount
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UAccount extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_account';
    const AUTO_INCREMENT_COLUMN = 'user_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'uin',
          2 => 'c_time',
          3 => 'm_time',
          4 => 'is_new_from_allbiz',
          5 => 'has_confirmed_email',
          6 => 'has_undeliverable_email',
          7 => 'undeliverable_email_count',
          8 => 'has_html_email',
          9 => 'may_email_features',
          10 => 'never_share_email',
          11 => 'receive_partner_email',
          12 => 'comp_access',
          13 => 'source_id',
          14 => 'use_external_auth',
          15 => 'is_archived',
          16 => 'has_suppressed_email',
          17 => 'has_comments_moderated',
          18 => 'has_comments_bozoed',
        );

    public $user_id = NULL;
    public $uin = NULL;
    public $c_time = NULL;
    public $m_time = NULL;
    public $email = NULL;
    public $password = NULL;
    public $first_name = NULL;
    public $last_name = NULL;
    public $gender = NULL;
    public $postal_code = NULL;
    public $country_code = NULL;
    public $company_name = NULL;
    public $company_address = NULL;
    public $company_address2 = NULL;
    public $company_city = NULL;
    public $company_state = NULL;
    public $company_postal_code = NULL;
    public $business_type_id = NULL;
    public $employee_count = NULL;
    public $job_title_id = NULL;
    public $job_title = NULL;
    public $subscriber_info_id = NULL;
    public $income_level_id = NULL;
    public $is_new_from_allbiz = NULL;
    public $has_confirmed_email = NULL;
    public $has_undeliverable_email = NULL;
    public $undeliverable_email_count = NULL;
    public $has_html_email = NULL;
    public $may_email_features = NULL;
    public $never_share_email = NULL;
    public $receive_partner_email = NULL;
    public $comp_access = NULL;
    public $source_id = NULL;
    public $email_domain = NULL;
    public $undeliverable_time = NULL;
    public $use_external_auth = NULL;
    public $last_login = NULL;
    public $is_archived = NULL;
    public $has_suppressed_email = NULL;
    public $has_comments_moderated = NULL;
    public $has_comments_bozoed = NULL;
    public $registration_ip_address = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'uin' => 
          array (
          ),
          'c_time' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'email' => 
          array (
          ),
          'password' => 
          array (
          ),
          'first_name' => 
          array (
          ),
          'last_name' => 
          array (
          ),
          'gender' => 
          array (
          ),
          'postal_code' => 
          array (
          ),
          'country_code' => 
          array (
          ),
          'company_name' => 
          array (
          ),
          'company_address' => 
          array (
          ),
          'company_address2' => 
          array (
          ),
          'company_city' => 
          array (
          ),
          'company_state' => 
          array (
          ),
          'company_postal_code' => 
          array (
          ),
          'business_type_id' => 
          array (
          ),
          'employee_count' => 
          array (
          ),
          'job_title_id' => 
          array (
          ),
          'job_title' => 
          array (
          ),
          'subscriber_info_id' => 
          array (
          ),
          'income_level_id' => 
          array (
          ),
          'is_new_from_allbiz' => 
          array (
          ),
          'has_confirmed_email' => 
          array (
          ),
          'has_undeliverable_email' => 
          array (
          ),
          'undeliverable_email_count' => 
          array (
          ),
          'has_html_email' => 
          array (
          ),
          'may_email_features' => 
          array (
          ),
          'never_share_email' => 
          array (
          ),
          'receive_partner_email' => 
          array (
          ),
          'comp_access' => 
          array (
          ),
          'source_id' => 
          array (
          ),
          'email_domain' => 
          array (
          ),
          'undeliverable_time' => 
          array (
          ),
          'use_external_auth' => 
          array (
          ),
          'last_login' => 
          array (
          ),
          'is_archived' => 
          array (
          ),
          'has_suppressed_email' => 
          array (
          ),
          'has_comments_moderated' => 
          array (
          ),
          'has_comments_bozoed' => 
          array (
          ),
          'registration_ip_address' => 
          array (
          ),
        );




}

?>