<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UCompanyWatchCompanies
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UCompanyWatchCompanies extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_company_watch_companies';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
          1 => 'company',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'c_time',
          2 => 'company',
        );

    public $user_id = NULL;
    public $c_time = NULL;
    public $company = NULL;
    public $reconOrgId = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
          ),
          'c_time' => 
          array (
          ),
          'company' => 
          array (
            0 => 1,
          ),
          'reconOrgId' => 
          array (
          ),
        );




}

?>