<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UDma
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UDma extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_dma';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'dma',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'dma',
        );

    public $dma = NULL;
    public $market = NULL;
    public $states = NULL;
    public $households = NULL;
    public $rank = NULL;
    public $percent = NULL;
    public $DBColumnsArray = 
        array (
          'dma' => 
          array (
            0 => 1,
          ),
          'market' => 
          array (
          ),
          'states' => 
          array (
          ),
          'households' => 
          array (
          ),
          'rank' => 
          array (
          ),
          'percent' => 
          array (
          ),
        );




}

?>