<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UEmailReturnMessage
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UEmailReturnMessage extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_email_return_message';
    const AUTO_INCREMENT_COLUMN = 'message_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'message_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'message_id',
          1 => 'user_id',
          2 => 'is_gzipped',
        );

    public $message_id = NULL;
    public $user_id = NULL;
    public $return_type = NULL;
    public $email_type_id = NULL;
    public $action = NULL;
    public $is_gzipped = NULL;
    public $received_time = NULL;
    public $message = NULL;
    public $DBColumnsArray = 
        array (
          'message_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_id' => 
          array (
          ),
          'return_type' => 
          array (
          ),
          'email_type_id' => 
          array (
          ),
          'action' => 
          array (
          ),
          'is_gzipped' => 
          array (
          ),
          'received_time' => 
          array (
          ),
          'message' => 
          array (
          ),
        );




}

?>