<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UJobPosition
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UJobPosition extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_job_position';
    const AUTO_INCREMENT_COLUMN = 'job_title_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'job_title_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'job_title_id',
          1 => 'description',
          2 => 'is_active',
          3 => 'ord',
        );

    public $job_title_id = NULL;
    public $description = NULL;
    public $is_active = NULL;
    public $ord = NULL;
    public $DBColumnsArray = 
        array (
          'job_title_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'description' => 
          array (
          ),
          'is_active' => 
          array (
          ),
          'ord' => 
          array (
          ),
        );




}

?>