<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UPhoneNumbers
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UPhoneNumbers extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_phone_numbers';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'user_id',
          1 => 'm_time',
        );

    public $user_id = NULL;
    public $phone = NULL;
    public $fax = NULL;
    public $cell = NULL;
    public $m_time = NULL;
    public $c_time = NULL;
    public $DBColumnsArray = 
        array (
          'user_id' => 
          array (
            0 => 1,
          ),
          'phone' => 
          array (
          ),
          'fax' => 
          array (
          ),
          'cell' => 
          array (
          ),
          'm_time' => 
          array (
          ),
          'c_time' => 
          array (
          ),
        );




}

?>