<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UReceivedMailMessage
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UReceivedMailMessage extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_received_mail_message';
    const AUTO_INCREMENT_COLUMN = 'message_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'message_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'message_id',
          1 => 'batch_time',
          2 => 'is_processed',
        );

    public $message_id = NULL;
    public $batch_time = NULL;
    public $message = NULL;
    public $return_type = NULL;
    public $user_id = NULL;
    public $is_processed = NULL;
    public $DBColumnsArray = 
        array (
          'message_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'batch_time' => 
          array (
          ),
          'message' => 
          array (
          ),
          'return_type' => 
          array (
          ),
          'user_id' => 
          array (
          ),
          'is_processed' => 
          array (
          ),
        );




}

?>