<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in UserMediaUpload
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class UserMediaUpload extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'user_media_upload';
    const AUTO_INCREMENT_COLUMN = 'media_upload_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'media_upload_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'media_upload_id',
          1 => 'extension',
          2 => 'source_application',
          3 => 'media_data',
          4 => 'is_archivable',
          5 => 'created_at',
        );

    public $media_upload_id = NULL;
    public $user_id = NULL;
    public $filename = NULL;
    public $extension = NULL;
    public $source_application = NULL;
    public $media_data = NULL;
    public $is_archivable = NULL;
    public $created_at = NULL;
    public $DBColumnsArray = 
        array (
          'media_upload_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'user_id' => 
          array (
          ),
          'filename' => 
          array (
          ),
          'extension' => 
          array (
          ),
          'source_application' => 
          array (
          ),
          'media_data' => 
          array (
          ),
          'is_archivable' => 
          array (
          ),
          'created_at' => 
          array (
          ),
        );




}

?>