<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in USubscriptionScrubReport
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class USubscriptionScrubReport extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_subscription_scrub_report';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'campaign_date',
          1 => 'product_id',
          2 => 'action',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'campaign_date',
          1 => 'product_id',
          2 => 'action',
          3 => 'added',
          4 => 'is_undeliverable',
          5 => 'is_leaving',
          6 => 'is_staying',
          7 => 'scrubbed',
        );

    public $campaign_date = NULL;
    public $product_id = NULL;
    public $action = NULL;
    public $added = NULL;
    public $is_undeliverable = NULL;
    public $is_leaving = NULL;
    public $is_staying = NULL;
    public $scrubbed = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'campaign_date' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
            0 => 1,
          ),
          'action' => 
          array (
            0 => 1,
          ),
          'added' => 
          array (
          ),
          'is_undeliverable' => 
          array (
          ),
          'is_leaving' => 
          array (
          ),
          'is_staying' => 
          array (
          ),
          'scrubbed' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>