<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in USubscriptionOptinLog
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class USubscriptionOptinLog extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_subscription_optin_log';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'subscription_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'subscription_id',
          1 => 'product_id',
          2 => 'user_id',
          3 => 'source_id',
          4 => 'uin',
          5 => 'ip_address',
          6 => 'optin_at',
        );

    public $subscription_id = NULL;
    public $product_id = NULL;
    public $user_id = NULL;
    public $market_id = NULL;
    public $source_id = NULL;
    public $uin = NULL;
    public $ip_address = NULL;
    public $optin_at = NULL;
    public $DBColumnsArray = 
        array (
          'subscription_id' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
          ),
          'user_id' => 
          array (
          ),
          'market_id' => 
          array (
          ),
          'source_id' => 
          array (
          ),
          'uin' => 
          array (
          ),
          'ip_address' => 
          array (
          ),
          'optin_at' => 
          array (
          ),
        );




}

?>