<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in USubscriptionScrub
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class USubscriptionScrub extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_subscription_scrub';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'campaign_date',
          1 => 'product_id',
          2 => 'user_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'subscription_id',
          1 => 'campaign_date',
          2 => 'product_id',
          3 => 'user_id',
          4 => 'opt_in_time',
        );

    public $subscription_id = NULL;
    public $campaign_date = NULL;
    public $product_id = NULL;
    public $user_id = NULL;
    public $is_undeliverable = NULL;
    public $is_leaving = NULL;
    public $is_staying = NULL;
    public $opt_in_time = NULL;
    public $opt_out_time = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'subscription_id' => 
          array (
          ),
          'campaign_date' => 
          array (
            0 => 1,
          ),
          'product_id' => 
          array (
            0 => 1,
          ),
          'user_id' => 
          array (
            0 => 1,
          ),
          'is_undeliverable' => 
          array (
          ),
          'is_leaving' => 
          array (
          ),
          'is_staying' => 
          array (
          ),
          'opt_in_time' => 
          array (
          ),
          'opt_out_time' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>