<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in USubscriptionActivity
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class USubscriptionActivity extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'u_subscription_activity';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'subscription_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'subscription_id',
        );

    public $subscription_id = NULL;
    public $open_count = NULL;
    public $last_open_time = NULL;
    public $click_count = NULL;
    public $last_click_time = NULL;
    public $DBColumnsArray = 
        array (
          'subscription_id' => 
          array (
            0 => 1,
          ),
          'open_count' => 
          array (
          ),
          'last_open_time' => 
          array (
          ),
          'click_count' => 
          array (
          ),
          'last_click_time' => 
          array (
          ),
        );




}

?>