<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in VerticalTopic
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class VerticalTopic extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'vertical_topic';
    const AUTO_INCREMENT_COLUMN = 'vertical_topic_id';
    const PRIMARY_KEYS = 
        array (
          0 => 'vertical_topic_id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'vertical_topic_id',
          1 => 'vertical_topic',
          2 => 'vertical_topic_string',
        );

    public $vertical_topic_id = NULL;
    public $vertical_topic = NULL;
    public $vertical_topic_string = NULL;
    public $DBColumnsArray = 
        array (
          'vertical_topic_id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'vertical_topic' => 
          array (
          ),
          'vertical_topic_string' => 
          array (
          ),
        );




}

?>