<?php
/**
  * @author jrobinson (robotically)
  * @date 2016/01/28
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in XmlSiteMap
  */
namespace DBCore\Bizj;

use phpr\Database\Model;

class XmlSiteMap extends Model {

    const SCHEMA = 'bizj';
    const TABLE = 'xml_site_map';
    const AUTO_INCREMENT_COLUMN = '';
    const PRIMARY_KEYS = 
        array (
          0 => 'site',
          1 => 'map_name',
          2 => 'content_type',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'site',
          1 => 'map_name',
          2 => 'content_type',
          3 => 'content',
          4 => 'created_at',
          5 => 'updated_at',
        );

    public $site = NULL;
    public $map_name = NULL;
    public $content_type = NULL;
    public $content = NULL;
    public $content_length = NULL;
    public $created_at = NULL;
    public $updated_at = NULL;
    public $DBColumnsArray = 
        array (
          'site' => 
          array (
            0 => 1,
          ),
          'map_name' => 
          array (
            0 => 1,
          ),
          'content_type' => 
          array (
            0 => 1,
          ),
          'content' => 
          array (
          ),
          'content_length' => 
          array (
          ),
          'created_at' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
        );




}

?>